-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNEB3JlcXVpcmUEZ2FtZRFSZXBsaWNhdGVkU3RvcmFnZQRMb2FkBUVudW1zBlJhcml0eQdEZWZhdWx0BkxlZ2FjeQZDb21tb24IVW5jb21tb24EUmFyZQdMaW1pdGVkCUxlZ2VuZGFyeQRFcGljCFNwZWN0cnVtCEFydGlmYWN0BlJlYXBlcgxIb2xpZGF5RXZlbnQJQ2hyaXN0bWFzDVN0UGF0cmlja3NEYXkLQ2VsZWJyYXRpb24GU3ByaW5nCUhhbGxvd2Vlbg1WYWxlbnRpbmVzRGF5BkVhc3RlcgZBdXR1bW4ITmV3WWVhcnMGU3VtbWVyDFRoYW5rc2dpdmluZwZXaW50ZXIHSW1hZ2VJZAROYW1lB09mZnNhbGUPVHJhZGluZ0Rpc2FibGVkBUVtcHR5BWVtcHR5C0Jhc2ljIENhYmluC2Jhc2ljX2NhYmluCUNvaW5QcmljZQhHZW1QcmljZQ5Ob3J0aGVybiBDYWJpbg5ub3J0aGVybl9jYWJpbgxGb3Jlc3QgQ2FiaW4MZm9yZXN0X2NhYmluC1ByZW1pdW1Pbmx5BlNhbG9vbgZzYWxvb24PVmljdG9yaWFuIENhYmluD3ZpY3Rvcmlhbl9jYWJpbhBXYXRjaHRvd2VyIENhYmluEHdhdGNodG93ZXJfY2FiaW4LU25vdyBDYXN0bGULc25vd19jYXN0bGUNRGlyZXdpY2sgVGVudA1kaXJld2lja190ZW50EUdpbmdlcmJyZWFkIENhYmluEWdpbmdlcmJyZWFkX2NhYmluDk1lcmNoYW50IENhYmluDm1lcmNoYW50X2NhYmluD01pbmVzaGFmdCBDYWJpbg9taW5lc2hhZnRfY2FiaW4NSGF1bnRlZCBNYW5vcg1oYXVudGVkX21hbm9yEEtyYW1wdXMgV29ya3Nob3AQa3JhbXB1c193b3Jrc2hvcAVFdmVudAZCdXJyb3cGYnVycm93AAEcAAABAgCFA6MAAACkAAEAAAAAQKQDAwAAACBATQIDPwQAAABNAQJ+BQAAAJ8AAgJSAQAAbwIGAJ8BAgJNAwHyBwAAAE0CAzoIAAAATQQB8gcAAABNAwRtCQAAAE0FAfIHAAAATQQFcwoAAABNBgHyBwAAAE0FBpYLAAAATQcB8gcAAABNBgenDAAAAE0IAfIHAAAATQcIJg0AAABNCQHyBwAAAE0ICbkOAAAATQoB8gcAAABNCQq8DwAAAE0LAfIHAAAATQoLqRAAAABNDAHyBwAAAE0LDJARAAAATQ0B8gcAAABNDA1EEgAAAE0OAQUTAAAATQ0OrRQAAABNDwEFEwAAAE0OD68VAAAATRABBRMAAABNDxD0FgAAAE0RAQUTAAAATRARIhcAAABNEgEFEwAAAE0REmkYAAAATRMBBRMAAABNEhNfGQAAAE0UAQUTAAAATRMUERoAAABNFQEFEwAAAE0UFWEbAAAATRYBBRMAAABNFRaYHAAAAE0XAQUTAAAATRYXMh0AAABNGAEFEwAAAE0XGOoeAAAATRkBBRMAAABNGBlFHwAAAP8ZBQAAAAAA4hokADADGvIHAAAAjBsAADAbGpYgAAAAbxslADAbGrohAAAAqRsBADAbGv4iAAAAqRsBADAbGqIjAAAAMBoZrSYAAADiGiQAMAMa8gcAAABvGycAMBsaliAAAABvGygAMBsauiEAAACpGwEAMBsa/iIAAACpGwEAMBsaoiMAAAAwGhkiKQAAAOIaLAAwAxryBwAAAG8bLQAwGxqWIAAAAIwbMHUwGxoRKgAAAIwbkAEwGxpJKwAAAG8bLgAwGxq6IQAAADAaGfYvAAAA4hosADADGvIHAAAAbxswADAbGpYgAAAAbxsxADAbGhEqAAAAjBvCATAbGkkrAAAAbxsyADAbGrohAAAAMBoZijMAAADiGjUAMAMa8gcAAABvGzYAMBsaliAAAABvGzcAMBsaESoAAACMG1cCMBsaSSsAAABvGzgAMBsauiEAAACpGwEAMBsarDQAAAAwGhnSOQAAAOIaOgAwAxryBwAAAG8bOwAwGxqWIAAAAIwb5wMwGxpJKwAAAG8bPAAwGxq6IQAAADAaGZU9AAAA4hosADADGvIHAAAAbxs+ADAbGpYgAAAAbxs/ADAbGhEqAAAAjBsqAzAbGkkrAAAAbxtAADAbGrohAAAAMBoZaEEAAADiGkIAMAca8gcAAABvG0MAMBsaliAAAABvG0QAMBsaESoAAACMG+4CMBsaSSsAAABvG0UAMBsauiEAAACpGwEAMBsa/iIAAAAwGhk5RgAAAOIaQgAwBxryBwAAAG8bRwAwGxqWIAAAAG8bRAAwGxoRKgAAAIwb7gIwGxpJKwAAAG8bSAAwGxq6IQAAAKkbAQAwGxr+IgAAADAaGZtJAAAA4hpCADAHGvIHAAAAbxtKADAbGpYgAAAAbxtEADAbGhEqAAAAjBvuAjAbGkkrAAAAbxtLADAbGrohAAAAqRsBADAbGv4iAAAAMBoZqkwAAADiGiQAMAka8gcAAABvG00AMBsaliAAAABvG04AMBsauiEAAACpGwEAMBsa/iIAAACpGwEAMBsaoiMAAAAwGhlMTwAAAOIaUAAwAxryBwAAAG8bUQAwGxqWIAAAAG8bUgAwGxq6IQAAAG8bUwAwGxoRKgAAAIwbXgEwGxpJKwAAADAaGVhUAAAA4hpCADAHGvIHAAAAbxtVADAbGpYgAAAAbxtEADAbGhEqAAAAjBvuAjAbGkkrAAAAbxtWADAbGrohAAAAqRsBADAbGv4iAAAAMBoZplcAAADiGlgAMAca8gcAAABvG1kAMBsaliAAAABvG0QAMBsaESoAAACMG+4CMBsaSSsAAABvG1oAMBsauiEAAACpGwEAMBsa/iIAAACpGwAAMBsaoiMAAAAwGhmpWwAAAOIaXQAwBxryBwAAAG8bXgAwGxqWIAAAADATGjZcAAAAbxtfADAbGhEqAAAAjBv0ATAbGkkrAAAAbxtgADAbGrohAAAAqRsBADAbGv4iAAAAqRsAADAbGqIjAAAAMBoZtWEAAACCGQIAYgMBBAAAAEADAgQAACBAAwMDBAMFAwYDBwMIAwkDCgMLAwwDDQMOAw8DEAMRAxIDEwMUAxUDFgMXAxgDGQMaAxsDHAMdAx4DHwMgAyEDIgUFByAhIiMDIwMkAgAAgJQdCPlBAyUDJgMnAygFBQcgKishAgAAcIEdCPlBAykDKgIAALB8SZ35QQIAAAAAABfhQAMrAywDLQUGByAqKyE0AgAA4HRJnflBAgAAAAAATO1AAy4DLwUEByArIQIAAJCBSZ35QQMwAzECAADgIbFDBUICAAAAAIDG80ADMgMzBQYHICorISICAACgBJoeBkICAAAAAAAX8UADNAM1AgAACGvIJwxCAzYDNwIAAJgx6SQNQgM4AzkCAADUOJ/gEEIDOgM7BQUHICEqKwJAIpY2yLraQgM8AgAAAAAAauhAAz0CAJQwLWtN2UIDPgM/BQcHICorISIjAoD9JxvfptlCA0ADQQNCBQgHIFwqKyEiIwJAgdwxx9bTQgIAAAAAAPnlQANDA0QAAQABGAAAAAAAAAAAAAABAAAEAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAQAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAEAAAABAAAAAQAAAAIAAgAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAQAAAAAAogsB7BCECwGN4AQrwsEd09ITFpiQz2vt

-- Decompiler will be improved VERY SOON!
-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2025-12-11 01:05:54
-- Luau version 6, Types version 3
-- Time taken: 0.006223 seconds

local var1 = require(game.ReplicatedStorage.Load)("Enums")
local Legacy = var1.Rarity.Legacy
local Limited = var1.Rarity.Limited
return {
	empty = {
		Rarity = Legacy;
		ImageId = 0;
		Name = "Empty";
		Offsale = true;
		TradingDisabled = true;
	};
	basic_cabin = {
		Rarity = Legacy;
		ImageId = 6719396168;
		Name = "Basic Cabin";
		Offsale = true;
		TradingDisabled = true;
	};
	northern_cabin = {
		Rarity = Legacy;
		ImageId = 6719395863;
		CoinPrice = 30000;
		GemPrice = 400;
		Name = "Northern Cabin";
	};
	forest_cabin = {
		Rarity = Legacy;
		ImageId = 6875813835;
		CoinPrice = 35000;
		GemPrice = 450;
		Name = "Forest Cabin";
	};
	saloon = {
		Rarity = Legacy;
		ImageId = 6875813710;
		CoinPrice = 60000;
		GemPrice = 599;
		Name = "Saloon";
		PremiumOnly = true;
	};
	victorian_cabin = {
		Rarity = Legacy;
		ImageId = 6875813913;
		GemPrice = 999;
		Name = "Victorian Cabin";
	};
	watchtower_cabin = {
		Rarity = Legacy;
		ImageId = 11416249404;
		CoinPrice = 81000;
		GemPrice = 810;
		Name = "Watchtower Cabin";
	};
	snow_castle = {
		Rarity = Limited;
		ImageId = 11875336340;
		CoinPrice = 70000;
		GemPrice = 750;
		Name = "Snow Castle";
		Offsale = true;
	};
	direwick_tent = {
		Rarity = Limited;
		ImageId = 15115816289;
		CoinPrice = 70000;
		GemPrice = 750;
		Name = "Direwick Tent";
		Offsale = true;
	};
	gingerbread_cabin = {
		Rarity = Limited;
		ImageId = 15646664243;
		CoinPrice = 70000;
		GemPrice = 750;
		Name = "Gingerbread Cabin";
		Offsale = true;
	};
	merchant_cabin = {
		Rarity = var1.Rarity.Epic;
		ImageId = 18122001973;
		Name = "Merchant Cabin";
		Offsale = true;
		TradingDisabled = true;
	};
	mineshaft_cabin = {
		Rarity = Legacy;
		ImageId = 117558101039241;
		Name = "Mineshaft Cabin";
		CoinPrice = 50000;
		GemPrice = 350;
	};
	haunted_manor = {
		Rarity = Limited;
		ImageId = 111281205199440;
		CoinPrice = 70000;
		GemPrice = 750;
		Name = "Haunted Manor";
		Offsale = true;
	};
	krampus_workshop = {
		Rarity = Limited;
		ImageId = 112817993457654;
		CoinPrice = 70000;
		GemPrice = 750;
		Name = "Krampus Workshop";
		Offsale = true;
		TradingDisabled = false;
	};
	burrow = {
		Rarity = Limited;
		ImageId = 87252743451141;
		Event = var1.HolidayEvent.Easter;
		CoinPrice = 45000;
		GemPrice = 500;
		Name = "Burrow";
		Offsale = true;
		TradingDisabled = false;
	};
}