-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgPNAgdyZXF1aXJlBGdhbWURUmVwbGljYXRlZFN0b3JhZ2UETG9hZAlDb25zdGFudHMJd29ya3NwYWNlCVNhbGVFdmVudAxHZXRBdHRyaWJ1dGUFVGFibGUGVGl0bGVzDU9uZVRpbWVSZXdhcmQEX3QyOQt3ZWFwb25zXzEwMARfdDMwCmtpbGxlcnNfMjUEX3QzMQhjYWJpbnNfNQVDb2lucwJYUARzdGFiBGtpbGwEX3QyMwhraWxsXzEwMARfdDI0CWtpbGxfMTAwMARfdDI1CmtpbGxfMTAwMDAGZXNjYXBlBF90MzIPZXNjYXBlX2VhY2hfbWFwBF90MjAKZXNjYXBlXzEwMARfdDIxC2VzY2FwZV8xMDAwBF90MjIMZXNjYXBlXzEwMDAwBnJldml2ZQRfdDE3CnJldml2ZV8xMDAEX3QxOAtyZXZpdmVfMTAwMARfdDE5DHJldml2ZV8xMDAwMARsb290BF90MjYIbG9vdF8xMDAEX3QyNwlsb290XzEwMDAEX3QyOApsb290XzEwMDAwA3dpbgRHZW1zEmNvbGxlY3RfbG9vdF9kYWlseRRyZXZpdmVfcGxheWVyc19kYWlseQxlc2NhcGVfZGFpbHkSdGVhbV9lc2NhcGVzX2RhaWx5EXBsYXlfM19tYXBzX2RhaWx5CnZvdGVfZGFpbHkJd2luX2RhaWx5BkJhZGdlcwplc2NhcGVkXzEwCnJldml2ZWRfMTALZGVmZWF0ZWRfMTATbG9vdF90cmVhc3VyZV9jaGVzdAVJdGVtcw1vcmFuZ2Vfc2x5Y2VyB0xldmVsIDIHUmVjaXBlcxBTbGluZ2luZyBTbGFzaGVyEnJlY2lwZV9pcm9uX3NseWNlcgdMZXZlbCA1DE1hc2tlZCBNeWVycxNyZWNpcGVfc3RlZWxfc2x5Y2VyCExldmVsIDEwDU1hc2tlZCBLaWxsZXIITGV2ZWwgMTMDX3Q3F3JlY2lwZV9yZWNsYWltZWRfc2x5Y2VyCExldmVsIDE1FXJlY2lwZV9mcmlnaWRfZnJvc3RhcghMZXZlbCAyMAxSZWQgU2NyZWFtZXIITGV2ZWwgMjUDX3Q4GHJlY2lwZV9ydW5lX29mX2NhdGFjbHlzbRhyZWNpcGVfdG9ybWVudGVkX3BpY2theGUITGV2ZWwgMzARcmVjaXBlX2dvbGRlbl9zdW4ITGV2ZWwgMzUMcmVhY3Rvcl9jb3JlF3JlY2lwZV9vYXRoX29mX2RhcmtuZXNzCExldmVsIDQwA190ORhyZWNpcGVfcm9zZV9nb2xkX2Jsb3Nzb20ITGV2ZWwgNDUdcmVjaXBlX21vbHRlbl9yYWlscm9hZF93cmVuY2gITGV2ZWwgNTAITGV2ZWwgNTUEX3QxMBlyZWNpcGVfcmFkaW9hY3RpdmVfc2x5Y2VyCExldmVsIDYwCExldmVsIDY1CExldmVsIDcwBF90MTETcmVjaXBlX3NlYXJpbmdfcnVuZQhMZXZlbCA3NQhMZXZlbCA4MAhMZXZlbCA4NQRfdDEyCExldmVsIDkwCExldmVsIDkzCExldmVsIDk3BF90MTMJTGV2ZWwgMTAwBF90MTQMTGV2ZWwgMTAwIFIxEGV4Y2x1c2l2ZV9zbHljZXINR3JvdXAgS25pZmUgMRB0aGVfZ3JvdXBfZWZmb3J0DUdyb3VwIEtuaWZlIDIRMTAwMF9kZWdyZWVfa25pZmUVcmVjaXBlX25veGl1bV92dWxjYW5pA1ZJUA5tZXJjaGFudF9jYWJpbgRfdDQ0ClRyYWRpbmdWSVAKcmVkX3NseWNlcg1lbWVyYWxkX2RyZWFtFXNhcHBoaXJlX3NwYXJrbGVfdGltZQtTdGFydGVyUGFjawlQYXBhIFJvbmkIUGFwYVJvbmkGVm9sZGFyEnZvbGRhcl9saWdodF9zd29yZAxWb2xkYXJCdW5kbGUFRHJlYWQUY29ycnVwdGVkX2RyZWFkYmxhZGULRHJlYWRCdW5kbGUIS3JpbmdsZXIOa3JpbmdsZXJzX2hvb2sOS3JpbmdsZXJCdW5kbGUGTWFsdnVzDG1hbHZ1c19rbmlmZQxNYWx2dXNCdW5kbGUNU2VhcmluZyBHdWFyZA1zZWFyaW5nX3N3b3JkElNlYXJpbmdHdWFyZEJ1bmRsZQlNci4gUmlzdXMMcmlzdXNfc2lja2xlDU1yUmlzdXNCdW5kbGUNTGF5ZmEgQXNod2VsbA9hc2h3ZWxsX2NsZWF2ZXISTGF5ZmFBc2h3ZWxsQnVuZGxlCEdyaW1zbGV5EGdyaW1zbGV5c19idXN0ZXIOR3JpbXNsZXlCdW5kbGUHTWVzc2FnZRJwcmVtaXVtX3NseWNlcjIwMjM1WW91IGdvdCBhIDIwMjMgbGltaXRlZCBrbmlmZSBiZWNhdXNlIHlvdSBvd24gUHJlbWl1bS5aTGltaXRlZCBpdGVtcyBhcmUgdmFsdWFibGUgc28gbWFrZSBzdXJlIHlvdSBrbm93IHRoZSB2YWx1ZSBvZiB0aGlzIGl0ZW0gYmVmb3JlIHRyYWRpbmcgaXQuEnByZW1pdW1fc2x5Y2VyMjAyNDVZb3UgZ290IGEgMjAyNCBsaW1pdGVkIGtuaWZlIGJlY2F1c2UgeW91IG93biBQcmVtaXVtLhJwcmVtaXVtX3NseWNlcjIwMjU1WW91IGdvdCBhIDIwMjUgbGltaXRlZCBrbmlmZSBiZWNhdXNlIHlvdSBvd24gUHJlbWl1bS4RQ29ycnVwdCBQYXBhIFJvbmkTY2hhcnJlZF9yb2xsaW5nX3BpbgNDUFIMRGl2aW5lX0N1cGlkC2N1cGlkX3NwZWFyEERpdmluZSBDdXBpZCBUb3lYSW4gY2VsZWJyYXRpb24gb2YgdGhlIHJlbGVhc2Ugb2YgU1RLIFJlbWFzdGVyZWQsIGhlcmUncyAxMDAgR2Vtcy4gVGhhbmsgeW91IGZvciBwbGF5aW5nIQxzdGtyX3JlbGVhc2UXbWlsbGlvbnRoX3NseWNlcl9yZXdhcmQ5SW4gY2VsZWJyYXRpb24gb2YgMSBtaWxsaW9uIHZvdGVzISBUaGFuayB5b3UgZm9yIHBsYXlpbmchC3RyYW5jZV9mYW5nQkhhcHB5IGxhdGUgRWFzdGVyIGFuZCBTdC5QYXRyaWNrJ3MgRGF5LCB0aGFuayB5b3UgYWxsIGZvciBwbGF5aW5nIQt4cF9ib29zdF8xaA1mcmVlX3hwX2Jvb3N0Em1pbnR5X2hvbGlkYXlfaG9vay/wn46FIE1lcnJ5IENocmlzdG1hcyBhbmQgaGFwcHkgaG9saWRheXMhIOKdhO+4jw5jaHJpc3RtYXNfMjAyMgRfdDMzE3NjYXZlbmdlcl9odW50XzIwMjIMaG9sbG93X2hlYXJ0BF90MzQOdmFsZW50aW5lXzIwMjMIY29kZV9yZWQOY29kZV9yZWRfYXdhcmQMbWV0YWxfc2Vhc29uBF90MzUJbWV0YWxsaWNhDm9vcHNpZV9kYWlzaWVzFG9vcHNpZV9kYWlzaWVzX2F3YXJkD2NoYXJjb2FsX3NseWNlchhyZWNpcGVfbW90aGVybG9kZV9zbHljZXILbWluaW5nX2NvZGUMdW5kZWFkX2NhbmR5E2hhbGxvd2Vlbl8yMDI0X2NvZGUPRGlyZXdpY2tUaWNrZXRzDmZyaWVuZF9xdWVzdF8yDXN0ZXBfcmlnaHRfdXANd2VsbF9vZl9zb3VscxJ1bmxvY2tpbmdfbGFudGVybnMMY2FuZHlfcGFyYWRlEWRlYWRfZnJlZF9xdWVzdF8yDlByb2ZpbGVCYW5uZXJzFUZsb3RzYW0gRGlyZXdpY2sgMjAyNBVhbGxzZWVpbmdfZ3JhdmVfc3BhZGUSZXZlbnRfZGlyZXdpY2syMDI0BF90NDYQZmVzdGl2YWxfZmllbmRfMg5naG9zdGx5X3NseWNlchFoYWxsb3doZWVsX29yYW5nZRFoYWxsb3doZWVsX3B1cnBsZRNkaXJld2lja19jaGVzdF8yMDI0EGhhbGxvd2hlZWxfYmxhY2sQY3Vyc2VkX3NjYWxseXdhZxBoYWxsb3doZWVsX3doaXRlFnJ1ZG9scGhfZ29sZGVuX3JhdmFnZXIEX3Q0MRN3ZWVrX29mX2Zlc3Rpdml0aWVzBF90NDIOdGlzX3RoZV9zZWFzb24PYnVpbGRfYV9zbm93bWFuCXN0b2NrcGlsZQ9jb29raWVfY3J1bWJsZXMRZ2luZ2VyYnJlYWRfY2FiaW4Rd2ludGVyX2NyYXRlXzIwMjMEX3Q0MxRzYW50YXNfbGl0dGxlX2hlbHBlchBob2xpZGF5X3NwbGludGVyG/CfjoUgSGFwcHkgSG9saWRheXMhIOKdhO+4jxB3aW50ZXJfMjAyM19jb2RlDWVsZWN0cm9zbHljZXIIdGhlX2h1bnQQZWxlY3Ryb3NseWNlcl9zYwxoaWdoX3ZvbHRhZ2UWbWFjaGluZV9kYWdnZXJfY2F1dGlvbhZtYWNoaW5lX2RhZ2dlcl93YXJuaW5nE3NseWNlX29mX3ByaWRlXzIwMjQPcHJpZGVfMjAyNF9jb2RlEWlyaWRlc2NlbnRfc2x5Y2VyFmlyaWRlc2NlbnRfc2x5Y2VyX2NvZGUQVGhlR2FtZXMyMDI0R2VtMRBUaGVHYW1lczIwMjRHZW0yEFRoZUdhbWVzMjAyNEdlbTMQVGhlR2FtZXMyMDI0R2VtNBBUaGVHYW1lczIwMjRHZW01ElRoZUdhbWVzMjAyNFF1ZXN0MRJUaGVHYW1lczIwMjRRdWVzdDISVGhlR2FtZXMyMDI0UXVlc3QzEnVuaXR5X29mX3RoZV9nYW1lcxtUaGVHYW1lczIwMjRRdWVzdENvbXBsZXRpb24QYmVqZXdlbGVkX3NseWNlchlUaGVHYW1lczIwMjRHZW1Db21wbGV0aW9uEnJlY3ljbGVkX2RyYWlucGlwZRpjcmVhdGVkX3JlY3ljbGVkX2RyYWlucGlwZRljcmVhdGVkX2lyaWRlc2NlbnRfc2x5Y2VyGHJlY2lwZV9pcmlkZXNjZW50X3NseWNlch9yZWNpcGVfaXJpZGVzY2VudF9zbHljZXJfcmV3YXJkC2lyb25fc2x5Y2VyE2NyZWF0ZWRfaXJvbl9zbHljZXIMc3RlZWxfc2x5Y2VyFGNyZWF0ZWRfc3RlZWxfc2x5Y2VyEHJlY2xhaW1lZF9zbHljZXIYY3JlYXRlZF9yZWNsYWltZWRfc2x5Y2VyD3JhaWxyb2FkX3dyZW5jaBdjcmVhdGVkX3JhaWxyb2FkX3dyZW5jaA5mcmlnaWRfZnJvc3RhchZjcmVhdGVkX2ZyaWdpZF9mcm9zdGFyEXJ1bmVfb2ZfY2F0YWNseXNtGWNyZWF0ZWRfcnVuZV9vZl9jYXRhY2x5c20KZ29sZGVuX3N1bhJjcmVhdGVkX2dvbGRlbl9zdW4Qb2F0aF9vZl9kYXJrbmVzcxhjcmVhdGVkX29hdGhfb2ZfZGFya25lc3MRcm9zZV9nb2xkX2Jsb3Nzb20ZY3JlYXRlZF9yb3NlX2dvbGRfYmxvc3NvbRZtb2x0ZW5fcmFpbHJvYWRfd3JlbmNoHmNyZWF0ZWRfbW9sdGVuX3JhaWxyb2FkX3dyZW5jaBJyYWRpb2FjdGl2ZV9zbHljZXIaY3JlYXRlZF9yYWRpb2FjdGl2ZV9zbHljZXIMc2VhcmluZ19ydW5lFGNyZWF0ZWRfc2VhcmluZ19ydW5lDm5veGl1bV92dWxjYW5pFmNyZWF0ZWRfbm94aXVtX3Z1bGNhbmkKc3VwZXJfY3lhbhJjcmVhdGVkX3N1cGVyX2N5YW4Sc2FwcGhpcmVfbG9uZ3N3b3JkGmNyZWF0ZWRfc2FwcGhpcmVfbG9uZ3N3b3JkFWVuaGFuY2VkX2Jhc2ViYWxsX2JhdB1jcmVhdGVkX2VuaGFuY2VkX2Jhc2ViYWxsX2JhdA9yaW5nc19vZl9zYXR1cm4XY3JlYXRlZF9yaW5nc19vZl9zYXR1cm4LbGlnaHRfYmxhZGUTY3JlYXRlZF9saWdodF9ibGFkZRBzaGF0dGVyZWRfcGxhbmV0GGNyZWF0ZWRfc2hhdHRlcmVkX3BsYW5ldBdpbGx1bWluYXRlZF9saWdodF9ibGFkZR9jcmVhdGVkX2lsbHVtaW5hdGVkX2xpZ2h0X2JsYWRlCnZvaWRfYmxhZGUSY3JlYXRlZF92b2lkX2JsYWRlC2Nyb3duX2pld2VsE2NyZWF0ZWRfY3Jvd25famV3ZWwKc2hhZG93dmVpbBJjcmVhdGVkX3NoYWRvd3ZlaWwJZGFlbW9uaXVtEWNyZWF0ZWRfZGFlbW9uaXVtC2RlYXRoX2FkZGVyE2NyZWF0ZWRfZGVhdGhfYWRkZXIRbW90aGVybG9kZV9zbHljZXIZY3JlYXRlZF9tb3RoZXJsb2RlX3NseWNlcgxnb2xkX3BpY2theGUUY3JlYXRlZF9nb2xkX3BpY2theGURdG9ybWVudGVkX3BpY2theGUZY3JlYXRlZF90b3JtZW50ZWRfcGlja2F4ZRJwcm9zcGVjdG9yX2tob3Blc2gaY3JlYXRlZF9wcm9zcGVjdG9yX2tob3Blc2gOZWxlbWVudF9vZl9pY2UXY29sbGVjdF9sb290XzEwMF9yZXdhcmQQZWxlbWVudF9vZl9lYXJ0aBhyZXZpdmVfcGxheWVyc181MF9yZXdhcmQPZWxlbWVudF9vZl93aW5kEGVzY2FwZV8xMF9yZXdhcmQPZWxlbWVudF9vZl9maXJlEGtpbGxzXzEwMF9yZXdhcmQUZWxlbWVudF9vZl9saWdodG5pbmcQd2lubmVyXzI1X3Jld2FyZA5SZXdhcmRPdmVycmlkZQpTZXJ2ZXJUeXBlBXBhaXJzCERlZXBDb3B5D0NPSU5fTVVMVElQTElFUgABDgAAAQAA+BGjAAAApAABAAAAAECkAwMAAAAgQE0CAz8EAAAATQECfgUAAACfAAICUgEAAG8CBgCfAQICpAIIAAAAcEBvBAkAvAICEgoAAACfAgMCUgMAAG8ECwCfAwIC/wQJAAAAAADiBQ4A/wYAAAEAAABvBw8AxQYHAgEAAAAwBgUYDAAAAKkGAQAwBgUnDQAAADAFBD0QAAAA4gUOAP8GAAABAAAAbwcRAMUGBwIBAAAAMAYFGAwAAACpBgEAMAYFJw0AAAAwBQRYEgAAAOIFDgD/BgAAAQAAAG8HEwDFBgcCAQAAADAGBRgMAAAAqQYBADAGBScNAAAAMAUEYhQAAADiBRcAjAYFADAGBYcVAAAAjAYFADAGBS4WAAAAMAUEChgAAADiBRcAjAYUADAGBYcVAAAAjAYeADAGBS4WAAAAMAUEQhkAAADiBQ4A/wYAAAEAAABvBxoAxQYHAgEAAAAwBgUYDAAAAKkGAQAwBgUnDQAAADAFBPYbAAAA4gUOAP8GAAABAAAAbwccAMUGBwIBAAAAMAYFGAwAAACpBgEAMAYFJw0AAAAwBQSAHQAAAOIFDgD/BgAAAQAAAG8HHgDFBgcCAQAAADAGBRgMAAAAqQYBADAGBScNAAAAMAUElR8AAADiBRcAjAYUADAGBYcVAAAAjAZGADAGBS4WAAAAMAUEtCAAAADiBQ4A/wYAAAEAAABvByEAxQYHAgEAAAAwBgUYDAAAAKkGAQAwBgUnDQAAADAFBI0iAAAA4gUOAP8GAAABAAAAbwcjAMUGBwIBAAAAMAYFGAwAAACpBgEAMAYFJw0AAAAwBQSWJAAAAOIFDgD/BgAAAQAAAG8HJQDFBgcCAQAAADAGBRgMAAAAqQYBADAGBScNAAAAMAUEcCYAAADiBQ4A/wYAAAEAAABvBycAxQYHAgEAAAAwBgUYDAAAAKkGAQAwBgUnDQAAADAFBKMoAAAA4gUXAIwGBQAwBgWHFQAAAIwGBQAwBgUuFgAAADAFBI4pAAAA4gUOAP8GAAABAAAAbwcqAMUGBwIBAAAAMAYFGAwAAACpBgEAMAYFJw0AAAAwBQSTKwAAAOIFDgD/BgAAAQAAAG8HLADFBgcCAQAAADAGBRgMAAAAqQYBADAGBScNAAAAMAUEly0AAADiBQ4A/wYAAAEAAABvBy4AxQYHAgEAAAAwBgUYDAAAAKkGAQAwBgUnDQAAADAFBDQvAAAA4gUwAIwGAQAwBgUuFgAAADAFBIoxAAAA4gUOAP8GAAABAAAAbwcyAMUGBwIBAAAAMAYFGAwAAACpBgEAMAYFJw0AAAAwBQSvMwAAAOIFDgD/BgAAAQAAAG8HNADFBgcCAQAAADAGBRgMAAAAqQYBADAGBScNAAAAMAUEvTUAAADiBQ4A/wYAAAEAAABvBzYAxQYHAgEAAAAwBgUYDAAAAKkGAQAwBgUnDQAAADAFBHM3AAAA4gUXAIwGZAAwBgWHFQAAAIwGlgAwBgUuFgAAADAFBKI4AAAA4gU6AIwGAQAwBgWVOQAAAIwGMgAwBgUuFgAAADAFBKE7AAAA4gU6AIwGAQAwBgWVOQAAAIwGMgAwBgUuFgAAADAFBIw8AAAA4gU6AIwGAQAwBgWVOQAAAIwGMgAwBgUuFgAAADAFBI09AAAA4gU6AIwGAQAwBgWVOQAAAIwGMgAwBgUuFgAAADAFBOQ+AAAA4gU6AIwGAQAwBgWVOQAAAIwGSwAwBgUuFgAAADAFBDo/AAAA4gU6AIwGAQAwBgWVOQAAAIwGSwAwBgUuFgAAADAFBFpAAAAA4gU6AIwGAQAwBgWVOQAAAIwGSwAwBgUuFgAAADAFBD1BAAAA4gVDAP8GAAABAAAAbwdEAMUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQSzRQAAAOIFQwD/BgAAAQAAAG8HRgDFBgcCAQAAADAGBftCAAAAqQYBADAGBScNAAAAMAUE0kcAAADiBUMA/wYAAAEAAABvB0gAxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBFBJAAAA4gVKAIwGlgAwBgWHFQAAAKkGAQAwBgUnDQAAADAFBMVLAAAA4gVNAP8GAQAAAAAAjAcBADAHBnVOAAAAMAYFOEwAAACpBgEAMAYFJw0AAAAwBQRpTwAAAOIFUQD/BgEAAAAAAIwHAQAwBwY9UgAAADAGBThMAAAA/wYAAAEAAABvB1MAxQYHAgEAAAAwBgVFUAAAAP8GAAABAAAAbwdUAMUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQSgVQAAAOIFUQD/BgEAAAAAAIwHAQAwBwZMVgAAADAGBThMAAAA/wYAAAEAAABvB1cAxQYHAgEAAAAwBgVFUAAAAP8GAAABAAAAbwdYAMUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQRzWQAAAOIFTQD/BgEAAAAAAIwHAQAwBwanWgAAADAGBThMAAAAqQYBADAGBScNAAAAMAUEJ1sAAADiBVwA/wYAAAEAAABvB10AxQYHAgEAAAAwBgX7QgAAAP8GAAABAAAAbwdeAMUGBwIBAAAAMAYFGAwAAAD/BgAAAQAAAG8HXwDFBgcCAQAAADAGBUVQAAAAqQYBADAGBScNAAAAMAUEk2AAAADiBWEA/wYAAAEAAABvB2IAxQYHAgEAAAAwBgX7QgAAAP8GAAABAAAAbwdjAMUGBwIBAAAAMAYFRVAAAACpBgEAMAYFJw0AAAAwBQTzZAAAAOIFZQD/BgEAAAAAAIwHAQAwBwbcZgAAADAGBThMAAAA/wYAAAEAAABvB2cAxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBORoAAAA4gVpAP8GAAABAAAAbwdqAMUGBwIBAAAAMAYFGAwAAAD/BgAAAQAAAG8HawDFBgcCAQAAADAGBftCAAAA/wYAAAIAAABvB2wAbwhtAMUGBwMBAAAAMAYFRVAAAACpBgEAMAYFJw0AAAAwBQSAbgAAAOIFYQD/BgAAAQAAAG8HbwDFBgcCAQAAADAGBftCAAAA/wYAAAEAAABvB3AAxQYHAgEAAAAwBgVFUAAAAKkGAQAwBgUnDQAAADAFBKlxAAAA4gVRAP8GAQAAAAAAjAcBADAHBtxyAAAAMAYFOEwAAAD/BgAAAQAAAG8HcwDFBgcCAQAAADAGBUVQAAAA/wYAAAEAAABvB3QAxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBKt1AAAA4gVpAP8GAAABAAAAbwd2AMUGBwIBAAAAMAYFGAwAAAD/BgAAAQAAAG8HdwDFBgcCAQAAADAGBftCAAAA/wYAAAEAAABvB3gAxQYHAgEAAAAwBgVFUAAAAKkGAQAwBgUnDQAAADAFBLt5AAAA4gVhAP8GAAABAAAAbwd6AMUGBwIBAAAAMAYF+0IAAAD/BgAAAQAAAG8HewDFBgcCAQAAADAGBUVQAAAAqQYBADAGBScNAAAAMAUE0nwAAADiBUMA/wYAAAEAAABvB30AxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBOF+AAAA4gVpAP8GAAABAAAAbwd/AMUGBwIBAAAAMAYFGAwAAAD/BgAAAQAAAG8HgADFBgcCAQAAADAGBftCAAAA/wYAAAEAAABvB4EAxQYHAgEAAAAwBgVFUAAAAKkGAQAwBgUnDQAAADAFBE+CAAAA4gVDAP8GAAABAAAAbweDAMUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQRJhAAAAOIFQwD/BgAAAQAAAG8HhQDFBgcCAQAAADAGBftCAAAAqQYBADAGBScNAAAAMAUEnIYAAADiBWkA/wYAAAEAAABvB4cAxQYHAgEAAAAwBgUYDAAAAP8GAAABAAAAbweIAMUGBwIBAAAAMAYF+0IAAAD/BgAAAQAAAG8HiQDFBgcCAQAAADAGBUVQAAAAqQYBADAGBScNAAAAMAUETooAAADiBUMA/wYAAAEAAABvB4sAxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBGiMAAAA4gVDAP8GAAABAAAAbweNAMUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQR9jgAAAOIFjwD/BgAAAQAAAG8HkADFBgcCAQAAADAGBRgMAAAA/wYAAAEAAABvB5EAxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBFWSAAAA4gVDAP8GAAABAAAAbweTAMUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQTtlAAAAOIFQwD/BgAAAQAAAG8HlQDFBgcCAQAAADAGBftCAAAAqQYBADAGBScNAAAAMAUEu5YAAADiBY8A/wYAAAEAAABvB5cAxQYHAgEAAAAwBgUYDAAAAP8GAAABAAAAbweYAMUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQSImQAAAOIFjwD/BgAAAQAAAG8HmgDFBgcCAQAAADAGBRgMAAAA/wYAAAEAAABvB5sAxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBEacAAAA4gVNAP8GAQAAAAAAjAcBADAHBoudAAAAMAYFOEwAAACpBgEAMAYFJw0AAAAwBQTMngAAAOIFTQD/BgEAAAAAAIwHAQAwBwZynwAAADAGBThMAAAAqQYBADAGBScNAAAAMAUE2qAAAADiBaEAjAboAzAGBYcVAAAA/wYBAAAAAACMBwEAMAcGd6IAAAAwBgU4TAAAAP8GAAABAAAAbwejAMUGBwIBAAAAMAYFRVAAAACpBgAAMAYFJw0AAAAwBQTJpAAAAOIFpQD/BgEAAAAAAIwHAQAwBwZMpgAAADAGBThMAAAA/wYAAAEAAABvB6cAxQYHAgEAAAAwBgUYDAAAAKkGAQAwBgUnDQAAADAFBDyoAAAA4gVNAP8GAwAAAAAAjAcBADAHBjepAAAAjAcBADAHBraqAAAAjAcBADAHBqmrAAAAMAYFOEwAAACpBgAAMAYFJw0AAAAwBQRGrAAAAOIFTQD/BgEAAAAAAIwHAQAwBwZ8rQAAADAGBThMAAAAqQYAADAGBScNAAAAMAUEda4AAADiBU0A/wYCAAAAAACMBwEAMAcGaq8AAACMBwEAMAcGT7AAAAAwBgU4TAAAAKkGAAAwBgUnDQAAADAFBIuxAAAA4gVNAP8GAgAAAAAAjAcBADAHBm+yAAAAjAcBADAHBtezAAAAMAYFOEwAAACpBgAAMAYFJw0AAAAwBQQjtAAAAOIFTQD/BgIAAAAAAIwHAQAwBwb5tQAAAIwHAQAwBwYmtgAAADAGBThMAAAAqQYAADAGBScNAAAAMAUExrcAAADiBU0A/wYCAAAAAACMBwEAMAcGhLgAAACMBwEAMAcGJbkAAAAwBgU4TAAAAKkGAAAwBgUnDQAAADAFBEW6AAAA4gVNAP8GAgAAAAAAjAcBADAHBli7AAAAjAcBADAHBi+8AAAAMAYFOEwAAACpBgAAMAYFJw0AAAAwBQR6vQAAAOIFTQD/BgIAAAAAAIwHAQAwBwbavgAAAIwHAQAwBwbYvwAAADAGBThMAAAAqQYAADAGBScNAAAAMAUEQcAAAADiBU0A/wYCAAAAAACMBwEAMAcGwMEAAACMBwEAMAcGtcIAAAAwBgU4TAAAAKkGAAAwBgUnDQAAADAFBP3DAAAA4gVNAP8GAgAAAAAAjAcBADAHBlnEAAAAjAcBADAHBkTFAAAAMAYFOEwAAACpBgAAMAYFJw0AAAAwBQTLxgAAAOIFyAD/BgEAAAAAAIwHAQAwBwZWyQAAADAGBThMAAAA/wYAAAIAAABvB8oAbwjLAMUGBwMBAAAAMAYF+McAAACpBgEAMAYFJw0AAAAwBQRWyQAAAOIFyAD/BgEAAAAAAIwHAQAwBwYjzAAAADAGBThMAAAA/wYAAAIAAABvB80AbwjLAMUGBwMBAAAAMAYF+McAAACpBgEAMAYFJw0AAAAwBQQjzAAAAOIFyAD/BgEAAAAAAIwHAQAwBwaczgAAADAGBThMAAAA/wYAAAIAAABvB88AbwjLAMUGBwMBAAAAMAYF+McAAACpBgEAMAYFJw0AAAAwBQSczgAAAOIFTQD/BgIAAAAAAIwHAQAwBwa50AAAAIwHAQAwBwbr0QAAADAGBThMAAAAqQYBADAGBScNAAAAMAUEQ9IAAADiBU0A/wYCAAAAAACMBwEAMAcGmtMAAACMBwEAMAcGddQAAAAwBgU4TAAAAKkGAQAwBgUnDQAAADAFBAXVAAAA4gXWAIwGZAAwBgWVOQAAAG8G1wAwBgX4xwAAAKkGAQAwBgUnDQAAADAFBPbYAAAA4gXIAP8GAQAAAAAAjAcBADAHBvTZAAAAMAYFOEwAAABvBtoAMAYF+McAAACpBgEAMAYFJw0AAAAwBQT02QAAAOIFyAD/BgEAAAAAAIwHAQAwBwYz2wAAADAGBThMAAAAbwbcADAGBfjHAAAAqQYBADAGBScNAAAAMAUEM9sAAADiBd0A/wYBAAAAAACMBwEAMAcGh94AAAAwBgU4TAAAADAFBAzfAAAA4gXIAP8GAQAAAAAAjAcBADAHBorgAAAAMAYFOEwAAABvBuEAMAYF+McAAACpBgEAMAYFJw0AAAAwBQQA4gAAAOIFDgD/BgAAAQAAAG8H4wDFBgcCAQAAADAGBRgMAAAAqQYBADAGBScNAAAAMAUEW+QAAADiBaUA/wYBAAAAAACMBwEAMAcGseUAAAAwBgU4TAAAAP8GAAABAAAAbwfmAMUGBwIBAAAAMAYFGAwAAACpBgEAMAYFJw0AAAAwBQQF5wAAAOIFTQD/BgEAAAAAAIwHAQAwBwZp6AAAADAGBThMAAAAqQYBADAGBScNAAAAMAUEIOkAAADiBeoA/wYBAAAAAACMBwEAMAcGQesAAAAwBgU4TAAAAP8GAAABAAAAbwfsAMUGBwIBAAAAMAYFGAwAAAD/BgAAAQAAAG8H7QDFBgcCAQAAADAGBftCAAAAqQYBADAGBScNAAAAMAUEJe4AAADiBU0A/wYBAAAAAACMBwEAMAcGDe8AAAAwBgU4TAAAAKkGAQAwBgUnDQAAADAFBCDwAAAA4gXxAP8GAQAAAAAAjAcBADAHBqnyAAAAMAYFOEwAAAD/BgAAAQAAAG8H8wDFBgcCAQAAADAGBUVQAAAAqQYBADAGBScNAAAAMAUE/PQAAADiBU0A/wYBAAAAAACMBwEAMAcGQvUAAAAwBgU4TAAAAKkGAQAwBgUnDQAAADAFBNb2AAAA4gX4AIwGBQAwBgWF9wAAAKkGAQAwBgUnDQAAADAFBDP5AAAA4gX4AIwGBQAwBgWF9wAAAKkGAQAwBgUnDQAAADAFBMz6AAAA4gX4AIwGBQAwBgWF9wAAAKkGAQAwBgUnDQAAADAFBF/7AAAA4gX4AIwGBQAwBgWF9wAAAKkGAQAwBgUnDQAAADAFBHf8AAAA4gX4AIwGBQAwBgWF9wAAAKkGAQAwBgUnDQAAADAFBN/9AAAA4gX4AIwGBQAwBgWF9wAAAKkGAQAwBgUnDQAAADAFBHD+AAAA4gUAAf8GAgAAAAAAjAcBADAHBhABAQAAjAcBADAHBtkCAQAAMAYFOEwAAAD/BgAAAQAAAG8HAwHFBgcCAQAAADAGBVH/AAAA/wYAAAEAAABvBwQBxQYHAgEAAAAwBgUYDAAAAP8GAAABAAAAbwcFAcUGBwIBAAAAMAYF+0IAAACMBgoAMAYFhfcAAACpBgEAMAYFJw0AAAAwBQQDBgEAAOIFTQD/BgEAAAAAAIwHAQAwBwa7BwEAADAGBThMAAAAqQYBADAGBScNAAAAMAUEuwcBAADiBQgBjAYUADAGBYcVAAAAMAUEugkBAADiBd0A/wYBAAAAAACMBwEAMAcGh94AAAAwBgU4TAAAADAFBDsKAQAA4gXdAP8GAQAAAAAAjAcBADAHBpYLAQAAMAYFOEwAAAAwBQTvDAEAAOIF3QD/BgEAAAAAAIwHAQAwBwYODQEAADAGBThMAAAAMAUENQ4BAADiBU0A/wYBAAAAAACMBwEAMAcGQA8BAAAwBgU4TAAAAKkGAQAwBgUnDQAAADAFBEAPAQAA4gUQAf8GAAABAAAAbwcRAcUGBwIBAAAAMAYFGAwAAACMBgoAMAYFlTkAAACpBgEAMAYFJw0AAAAwBQRbEgEAAOIFEAH/BgAAAQAAAG8HEwHFBgcCAQAAADAGBRgMAAAAjAYKADAGBZU5AAAAqQYBADAGBScNAAAAMAUEExQBAADiBRUBjAYKADAGBZU5AAAAqQYBADAGBScNAAAAMAUEqRYBAADiBRUBjAYKADAGBZU5AAAAqQYBADAGBScNAAAAMAUE+xcBAADiBRUBjAYKADAGBZU5AAAAqQYBADAGBScNAAAAMAUELxgBAADiBaUA/wYCAAAAAACMBwEAMAcGqhkBAACMBwUAMAcG1RoBAAAwBgU4TAAAAP8GAAABAAAAbwcbAcUGBwIBAAAAMAYFGAwAAACpBgEAMAYFJw0AAAAwBQQCHAEAAOIFyAD/BgEAAAAAAIwHAQAwBwYAHQEAADAGBThMAAAAbwYeATAGBfjHAAAAqQYBADAGBScNAAAAMAUErB8BAADiBU0A/wYBAAAAAACMBwEAMAcG1yABAAAwBgU4TAAAAKkGAQAwBgUnDQAAADAFBJUhAQAA4gUiAf8GAQAAAAAAjAcBADAHBg8jAQAAMAYFOEwAAACMBugDMAYFLhYAAACpBgEAMAYFJw0AAAAwBQT2JAEAAOIFTQD/BgEAAAAAAIwHAQAwBwZsJQEAADAGBThMAAAAqQYBADAGBScNAAAAMAUEbCUBAADiBU0A/wYBAAAAAACMBwEAMAcGfiYBAAAwBgU4TAAAAKkGAQAwBgUnDQAAADAFBH4mAQAA4gVNAP8GAQAAAAAAjAcBADAHBtUnAQAAMAYFOEwAAACpBgEAMAYFJw0AAAAwBQQSKAEAAOIFTQD/BgEAAAAAAIwHAQAwBwa5KQEAADAGBThMAAAAqQYBADAGBScNAAAAMAUE3yoBAADiBWUA/wYAAAAAAAAwBgU4TAAAAP8GAAABAAAAbwcrAcUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQTJLAEAAOIFZQD/BgAAAAAAADAGBThMAAAA/wYAAAEAAABvBy0BxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBOMuAQAA4gVlAP8GAAAAAAAAMAYFOEwAAAD/BgAAAQAAAG8HLwHFBgcCAQAAADAGBftCAAAAqQYBADAGBScNAAAAMAUEnzABAADiBWUA/wYAAAAAAAAwBgU4TAAAAP8GAAABAAAAbwcxAcUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQRwMgEAAOIFZQD/BgAAAAAAADAGBThMAAAA/wYAAAEAAABvBzMBxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBNU0AQAA4gVlAP8GAAAAAAAAMAYFOEwAAAD/BgAAAQAAAG8HNQHFBgcCAQAAADAGBftCAAAAqQYBADAGBScNAAAAMAUETTYBAADiBWUA/wYAAAAAAAAwBgU4TAAAAP8GAAABAAAAbwc3AcUGBwIBAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQSgOAEAAOIFZQD/BgAAAAAAADAGBThMAAAA/wYAAAEAAABvBzkBxQYHAgEAAAAwBgX7QgAAAKkGAQAwBgUnDQAAADAFBFQ6AQAA4gVlAP8GAQAAAAAAjAcBADAHBtw7AQAAMAYFOEwAAAD/BgAAAAAAADAGBftCAAAAqQYBADAGBScNAAAAMAUEiDwBAADiBWUA/wYBAAAAAACMBwEAMAcGOT0BAAAwBgU4TAAAAP8GAAAAAAAAMAYF+0IAAACpBgEAMAYFJw0AAAAwBQTBPgEAAOIF3QD/BgEAAAAAAIwHAQAwBwZnPwEAADAGBThMAAAAMAUEX0ABAADiBd0A/wYBAAAAAACMBwEAMAcGuSkBAAAwBgU4TAAAADAFBI1BAQAA4gVCAf8GAAABAAAAbwdDAcUGBwIBAAAAMAYFRVAAAACpBgEAMAYFJw0AAAAwBQS3RAEAAOIF3QD/BgEAAAAAAIwHAQAwBwYjRQEAADAGBThMAAAAMAUETUYBAADiBd0A/wYBAAAAAACMBwEAMAcGL0cBAAAwBgU4TAAAADAFBPVIAQAA4gXdAP8GAQAAAAAAjAcBADAHBrVJAQAAMAYFOEwAAAAwBQSoSgEAAOIF3QD/BgEAAAAAAIwHAQAwBwaNSwEAADAGBThMAAAAMAUEx0wBAADiBd0A/wYBAAAAAACMBwEAMAcGUE0BAAAwBgU4TAAAADAFBHhOAQAA4gXdAP8GAQAAAAAAjAcBADAHBpdPAQAAMAYFOEwAAAAwBQQAUAEAAOIF3QD/BgEAAAAAAIwHAQAwBwZiUQEAADAGBThMAAAAMAUEWFIBAADiBd0A/wYBAAAAAACMBwEAMAcGUFMBAAAwBgU4TAAAADAFBOJUAQAA4gXdAP8GAQAAAAAAjAcBADAHBu1VAQAAMAYFOEwAAAAwBQRMVgEAAOIF3QD/BgEAAAAAAIwHAQAwBwb3VwEAADAGBThMAAAAMAUEU1gBAADiBd0A/wYBAAAAAACMBwEAMAcGulkBAAAwBgU4TAAAADAFBMlaAQAA4gXdAP8GAQAAAAAAjAcBADAHBiFbAQAAMAYFOEwAAAAwBQRFXAEAAOIF3QD/BgEAAAAAAIwHAQAwBwaNXQEAADAGBThMAAAAMAUEyF4BAADiBd0A/wYBAAAAAACMBwEAMAcG2V8BAAAwBgU4TAAAADAFBH9gAQAA4gXdAP8GAQAAAAAAjAcBADAHBq5hAQAAMAYFOEwAAAAwBQTbYgEAAOIF3QD/BgEAAAAAAIwHAQAwBwa1YwEAADAGBThMAAAAMAUE6GQBAADiBd0A/wYBAAAAAACMBwEAMAcGImUBAAAwBgU4TAAAADAFBDtmAQAA4gXdAP8GAQAAAAAAjAcBADAHBlZnAQAAMAYFOEwAAAAwBQQ9aAEAAOIF3QD/BgEAAAAAAIwHAQAwBwbiaQEAADAGBThMAAAAMAUEHmoBAADiBd0A/wYBAAAAAACMBwEAMAcGRGsBAAAwBgU4TAAAADAFBNFsAQAA4gXdAP8GAQAAAAAAjAcBADAHBt1tAQAAMAYFOEwAAAAwBQRUbgEAAOIF3QD/BgEAAAAAAIwHAQAwBwbzbwEAADAGBThMAAAAMAUEvnABAADiBd0A/wYBAAAAAACMBwEAMAcGMnEBAAAwBgU4TAAAADAFBHVyAQAA4gXdAP8GAQAAAAAAjAcBADAHBmxzAQAAMAYFOEwAAAAwBQT2dAEAAOIF3QD/BgEAAAAAAIwHAQAwBwbPdQEAADAGBThMAAAAMAUE3XYBAADiBd0A/wYBAAAAAACMBwEAMAcGLncBAAAwBgU4TAAAADAFBBt4AQAA4gXdAP8GAQAAAAAAjAcBADAHBuh5AQAAMAYFOEwAAAAwBQS+egEAAOIF3QD/BgEAAAAAAIwHAQAwBwZ3ewEAADAGBThMAAAAMAUE1nwBAADiBd0A/wYBAAAAAACMBwEAMAcGi30BAAAwBgU4TAAAADAFBG5+AQAA4gXdAP8GAQAAAAAAjAcBADAHBkF/AQAAMAYFOEwAAAAwBQTzgAEAAOIF3QD/BgEAAAAAAIwHAQAwBwZmgQEAADAGBThMAAAAMAUEFYIBAADiBd0A/wYBAAAAAACMBwEAMAcGO4MBAAAwBgU4TAAAADAFBCCEAQAA4gXdAP8GAQAAAAAAjAcBADAHBiWFAQAAMAYFOEwAAAAwBQQ6hgEAAOIF3QD/BgEAAAAAAIwHAQAwBwZEhwEAADAGBThMAAAAMAUEVYgBAABNBgEyiQEAAE0HAciKAQAAhwUGBw4FDACkBowBAACwWFIHBQCfBgIEFwYFAE0LA4WNAQAAUgwKAJ8LAgJqCwQJbgb6/wIAAACkBowBAACwWFIHBACfBgIEFwYLAE0LCocVAAAADgsIAIcLBAlNDAuHFQAAAE0NAU+OAQAACQwMDTAMC4cVAAAAbgb0/wIAAACCBAIAjwMDAQQAAABAAwIEAAAgQAMDAwQDBQMGBAAAcEADBwMIAwkDCgMLBQIMDQMMAw0DDgMPAxADEQMSAxMFAhUWAxQDFQMWAxcDGAMZAxoDGwMcAx0DHgMfAyADIQMiAyMDJAMlAyYDJwMoAykDKgMrBQEWAywDLQMuAy8DMAMxAzIDMwM0BQI5FgM1AzYDNwM4AzkDOgM7AzwFAkINAgAAAAxaqN9BAz0CAABASFuo30EDPgIAAIBIW6jfQQM/BQIVDQNAA0EFAkwNA0IDQwNEBQRMUEINA0UDRgIAAMBIW6jfQQNHA0gDSQIAAABJW6jfQQNKA0sDTAUEQgxQDQIAAEBJW6jfQQNNA04DTwUDQlANAgAAgElbqN9BA1ADUQUDTEINA1ICAADASVuo30EDUwUEDEJQDQNUAgAAACBeqN9BA1UDVgNXAgAAwIBiqN9BA1gDWQNaA1sCAAAAgWKo30EDXANdAgAAAIJkqN9BA14DXwIAAMCCZKjfQQNgA2ECAABAg2So30EDYgNjAgAAgINkqN9BA2QDZQIAAMCDZKjfQQNmAgAAAGSvqN9BA2cDaAIAAEBkr6jfQQNpA2oCAADAAj2830EDawIAAMADPbzfQQNsBQMMQg0DbQIAAAAFPbzfQQNuAgAAAAY9vN9BA28CAABABj2830EDcANxAgAAgAc9vN9BA3IDcwIAAIAJPbzfQQN0A3UDdgN3A3gFBBVMUA0DeQN6A3sFA0wMDQN8A30DfgN/A4ABA4EBA4IBA4MBA4QBA4UBA4YBA4cBA4gBA4kBA4oBA4sBA4wBA40BA44BA48BA5ABA5EBA5IBA5MBA5QBA5UBA5YBA5cBA5gBA5kBA5oBA5sBA5wBA50BBQNMxwENA54BA58BA6ABA6EBA6IBA6MBA6QBA6UBA6YBA6cBA6gBA6kBA6oBBQM5xwENA6sBA6wBA60BA64BA68BA7ABBQFMA7EBA7IBA7MBA7QBA7UBA7YBA7cBA7gBA7kBA7oBA7sBA7wBBQRMDEINA70BA74BAgAAgKuR8t9BA78BA8ABA8EBBQNMUA0DwgEDwwEDxAEDxQEDxgEDxwEFAvcBDQPIAQPJAQPKAQPLAQPMAQPNAQPOAQUGTP8BDEL3AQ0DzwED0AED0QED0gECEGSBo0WqJkMD0wED1AEFARUD1QED1gED1wED2AED2QED2gED2wEFAww5DQPcAQPdAQPeAQPfAQUCOQ0D4AED4QED4gED4wED5AED5QED5gED5wED6AED6QED6gED6wEFA0wWDQPsAQPtAQPuAQPvAQPwAQPxAQPyAQPzAQIsK2JjkcAtQwP0AQIwsQNcyscMQwP1AQJ0I4eFJYUcQwP2AQLg2v1APa4LQwP3AQJQO/l/lNIbQwP4AQJGCdTUpx0kQwP5AQLY6q2j0GAUQwP6AQIQAaO3//oJQwP7AQP8AQP9AQP+AQP/AQOAAgOBAgOCAgUCUA0DgwIDhAIDhQIDhgIDhwIDiAIDiQIDigIDiwIDjAIDjQIDjgIDjwIDkAIDkQIDkgIDkwIDlAIDlQIDlgIDlwIDmAIDmQIDmgIDmwIDnAIDnQIDngIDnwIDoAIDoQIDogIDowIDpAIDpQIDpgIDpwIDqAIDqQIDqgIDqwIDrAIDrQIDrgIDrwIDsAIDsQIDsgIDswIDtAIDtQIDtgIDtwIDuAIDuQIDugIDuwIDvAIDvQIDvgIDvwIDwAIDwQIDwgIDwwIDxAIDxQIDxgIDxwIDyAIDyQIDygIDywIEAACwWAPMAgPNAgABAAEIAAAAAAAAAAAAAAEAAAEAAAAAAAEAACEAAgEAAAAAAAABAAD+AAQBAAAAAAAAAQAA/gAEAQAAAAAAAAEAAP4ABAEAAAEAAP4ABgEAAAEAAP4ABAEAAAAAAAABAAD+AAQBAAAAAAAAAQAA/gAEAQAAAAAAAAEAAP4ABQEAAAEAAP4ABAEAAAAAAAABAAD+AAQBAAAAAAAAAQAA/gAEAQAAAAAAAAEAAP4ABAEAAAAAAAABAAD+AAUBAAABAAD+AAQBAAAAAAAAAQAA/gAEAQAAAAAAAAEAAP4ABAEAAAAAAAABAAD+AAUBAAD/AAMBAAAAAAAAAQAA/gAEAQAAAAAAAIsAAP4ABAEAAAAAAAABAAD+AAUBAAABAAD+AAYBAAABAAD+AAQBAAABAAD+AAQCAAABAAD9AAUBAAABAAD+AAgBAAABAAD+AAQBAAABAAD+AAQBAAABAAD+AAgBAAAAAAAAAQAA/gAFAQAAAAAAAAEAAP4ABQEAAAAAAAABAAD+AAQBAAABAAD+AAgBAAEAAP8AAwAA/AAGAQABAAD/AAMAAAAAAAABAAAAAAAAAQAA+gAIAQABAAD/AAMAAAAAAAABAAAAAAAAAQAA+gAIAQABAAD/AAMAAPwABgEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAPwABgEAAAAAAAABAACUAAAAAQAA/QAFAQABAAD/AAMAAAAAAAABAAD7AAcBAAAAAAAAAQAAAAAAAAEAAAAAAAAAAQAA/AAGAQAAAAAAAAEAAAAAAAABAAD9AAUBAAEAAP8AAwAAAAAAAAEAAAAAAAABAAD6AAgBAAAAAAAAAQAAAAAAAAEAAAAAAAABAAD8AAYBAAAAAAAAAQAAAAAAAAEAAP0ABQEAAAAAAAABAAD+AAQBAAAAAAAAAQAAAAAAAAEAAAAAAAABAAD8AAYBAAAAAAAAAQAA/gAEAQAAAAAAAAEAAP4ABAEAAAAAAAABAAAAAAAAAQAAAAAAAAEAAPwABgEAAAAAAAABAAD+vgQBAAAAAAAAAQAA/gAEAQAAAAAAAAEAAAAAAAABAAD9AAUBAAAAAAAAAQAA/gAEAQAAAAAAAAEAAP4ABAEAAAAAAAABAAAAAAAAAQAA/QAFAQAAAAAAAAEAAAAAAAABAAD9AAgBAAEAAP8AAwAA/AAHAQABAAD/AAMAAPwACgEAAAEAAQAA/wADAAAAAAAAAQAA+gAIAQABAAD/AAMAAAAAAAABAAD7AAcBAAEAAAEAAAEAAP0ABQAA+gAIAQABAAD/AAMAAPwABgEAAQAAAQAA/gAEAAD7AAcBAAEAAAEAAP4ABAAA+wAHAQABAAABAAD+AAQAAPsABwEAAQAAAZsA/gAEAAD7AAgBAAEAAAEAAP4ABAAA+wAHAQABAAABAAD+AAQAAPsABwEAAQAAAQAA/gAEAAD7AAcBAAEAAAEAAP4ABAAA+wAKAQABAAD/AAMAAAAAAAAAAQAA+wAIAQABAAD/AAMAAAAAAAAAAQAA+wAIAQABAAD/AAMAAAAAAAAAAQAA+wAKAQABAAABAAD+AAQAAPsABwEAAQAAAQAA/gAEAAD7AAoBAAABAAABAAD9AAUBAAEAAP8AAwAAAQAA+wAHAQABAAD/AAMAAAEAAPsACAEAAQAA/wD/AAgBAAEAAP8AAwAAAQAA+wAIAQAAAAAAAAEAAP4ABQEAAQCF/wADAAAAAAAAAQAA+wAHAQABAAD/AAMAAPwABgEAAQAA/wADAAAAAAAAAQAAAAAAAAEAAPoACAEAAQAA/wADAAD8AAYBAAEAAP8AAwAAAAAAAAEAAPsARgEAAQAA/wADAAD8AAgBAAABAAD+AAQBAAABAAD+AAQBAAABAAD+AAQBAAABAAD+AAQBAAABAAD+AAQBAAABAAD+AAQBAAEAAAEAAP4ABAAAAAAAAAEAAAAAAAABAAAAAAAAAQAAAQAA9wANAQABAAD/AAMAAPwACgEAAP8AAwEAAQAA/wD/AAUBAAEAAP8A/wAFAQABAAD/AP8ACAEAAQAA/wADAAD8UwYBAAAAAAAAAQAAAQAA/QAFAQAAAAAAAAEAAAEAAP0ABQEAAAEAAP4ABAEAAAEAAP4ABAEAAAEAAP4ABAEAAQAAAQAA/gAEAAAAAAAAAQAA+gAIAQABAAD/AAMAAAEAAPsACQEAAQAA/wAEAAD7AAgBAAEAAP8AAwAAAQAA+wAIAQABAAD/AAMAAPwABgEAAQAA/wADAAD8AAcBAAEAAP8AAwAA/AAHAQABAAD/AAMAAPwACAEAAAACAAAAAAAAAQAA/AAGAQAAAAIAAAAAAAABAAD8AAYBAAAAAgAAAAAAAAEAAPwABgEAAAACAAAAAAAAAQAA/AAGAQAAAAIAAI8AAAABAAD8AAYBAAAAAgAAAAAAAAEAAPwABgEAAAACAAAAAAAAAQAA/AAGAQAAAAIAAAAAAAABAAD8AAYBAAEAAP8AAwAAAAEAAPsABwEAAQAA/wADAAAAAQAA+wAKAQABAAD/AP8ABgEAAQAA/wD/AAYBAAAAAAAAAQAA/gAFAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP9+BgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAgBAAEAAP8A/wAGAQABAAD/AP8ABgEAAQAA/wD/AAYBAAEAAP8A/wAGAQABAAD/AP8ACQAAAAABAQAAAAABAAAAAP8ABQAAAAABAAABAAAAAAAAAP4ABwEAAAB2AAAAbAAAAEIAAABlAAAAewAAAK0AAABxAAAAggAAAAAAd9VWPJ7r0mhduxzbRejDrQfNQUhFETw9

-- Decompiler will be improved VERY SOON!
-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2025-12-11 01:05:52
-- Luau version 6, Types version 3
-- Time taken: 0.039879 seconds

local Load = require(game.ReplicatedStorage.Load)
local var9_result1_2 = Load("Constants")
local var9_result1 = Load("Table")
local module = {
	weapons_100 = {
		Titles = {"_t29"};
		OneTimeReward = true;
	};
	killers_25 = {
		Titles = {"_t30"};
		OneTimeReward = true;
	};
	cabins_5 = {
		Titles = {"_t31"};
		OneTimeReward = true;
	};
	stab = {
		Coins = 5;
		XP = 5;
	};
	kill = {
		Coins = 20;
		XP = 30;
	};
	kill_100 = {
		Titles = {"_t23"};
		OneTimeReward = true;
	};
	kill_1000 = {
		Titles = {"_t24"};
		OneTimeReward = true;
	};
	kill_10000 = {
		Titles = {"_t25"};
		OneTimeReward = true;
	};
	escape = {
		Coins = 20;
		XP = 70;
	};
	escape_each_map = {
		Titles = {"_t32"};
		OneTimeReward = true;
	};
	escape_100 = {
		Titles = {"_t20"};
		OneTimeReward = true;
	};
	escape_1000 = {
		Titles = {"_t21"};
		OneTimeReward = true;
	};
	escape_10000 = {
		Titles = {"_t22"};
		OneTimeReward = true;
	};
	revive = {
		Coins = 5;
		XP = 5;
	};
	revive_100 = {
		Titles = {"_t17"};
		OneTimeReward = true;
	};
	revive_1000 = {
		Titles = {"_t18"};
		OneTimeReward = true;
	};
	revive_10000 = {
		Titles = {"_t19"};
		OneTimeReward = true;
	};
	loot = {
		XP = 1;
	};
	loot_100 = {
		Titles = {"_t26"};
		OneTimeReward = true;
	};
	loot_1000 = {
		Titles = {"_t27"};
		OneTimeReward = true;
	};
	loot_10000 = {
		Titles = {"_t28"};
		OneTimeReward = true;
	};
	win = {
		Coins = 100;
		XP = 150;
	};
	collect_loot_daily = {
		Gems = 1;
		XP = 50;
	};
	revive_players_daily = {
		Gems = 1;
		XP = 50;
	};
	escape_daily = {
		Gems = 1;
		XP = 50;
	};
	team_escapes_daily = {
		Gems = 1;
		XP = 50;
	};
	play_3_maps_daily = {
		Gems = 1;
		XP = 75;
	};
	vote_daily = {
		Gems = 1;
		XP = 75;
	};
	win_daily = {
		Gems = 1;
		XP = 75;
	};
	escaped_10 = {
		Badges = {2124507184};
		OneTimeReward = true;
	};
	revived_10 = {
		Badges = {2124508449};
		OneTimeReward = true;
	};
	defeated_10 = {
		Badges = {2124508450};
		OneTimeReward = true;
	};
	loot_treasure_chest = {
		Coins = 150;
		OneTimeReward = true;
	};
	["Level 2"] = {
		Items = {
			orange_slycer = 1;
		};
		OneTimeReward = true;
	};
	["Level 5"] = {
		Items = {
			["Slinging Slasher"] = 1;
		};
		Recipes = {"recipe_iron_slycer"};
		Badges = {2124508451};
		OneTimeReward = true;
	};
	["Level 10"] = {
		Items = {
			["Masked Myers"] = 1;
		};
		Recipes = {"recipe_steel_slycer"};
		Badges = {2124508452};
		OneTimeReward = true;
	};
	["Level 13"] = {
		Items = {
			["Masked Killer"] = 1;
		};
		OneTimeReward = true;
	};
	["Level 15"] = {
		Badges = {2124508453};
		Titles = {"_t7"};
		Recipes = {"recipe_reclaimed_slycer"};
		OneTimeReward = true;
	};
	["Level 20"] = {
		Badges = {2124508454};
		Recipes = {"recipe_frigid_frostar"};
		OneTimeReward = true;
	};
	["Level 25"] = {
		Items = {
			["Red Screamer"] = 1;
		};
		Badges = {2124508455};
		OneTimeReward = true;
	};
	["Level 30"] = {
		Titles = {"_t8"};
		Badges = {2124511360};
		Recipes = {"recipe_rune_of_cataclysm", "recipe_tormented_pickaxe"};
		OneTimeReward = true;
	};
	["Level 35"] = {
		Badges = {2124515843};
		Recipes = {"recipe_golden_sun"};
		OneTimeReward = true;
	};
	["Level 40"] = {
		Items = {
			reactor_core = 1;
		};
		Recipes = {"recipe_oath_of_darkness"};
		Badges = {2124515844};
		OneTimeReward = true;
	};
	["Level 45"] = {
		Titles = {"_t9"};
		Badges = {2124517896};
		Recipes = {"recipe_rose_gold_blossom"};
		OneTimeReward = true;
	};
	["Level 50"] = {
		Badges = {2124517899};
		Recipes = {"recipe_molten_railroad_wrench"};
		OneTimeReward = true;
	};
	["Level 55"] = {
		Badges = {2124517901};
		OneTimeReward = true;
	};
	["Level 60"] = {
		Titles = {"_t10"};
		Badges = {2124517902};
		Recipes = {"recipe_radioactive_slycer"};
		OneTimeReward = true;
	};
	["Level 65"] = {
		Badges = {2124517903};
		OneTimeReward = true;
	};
	["Level 70"] = {
		Badges = {2124594576};
		OneTimeReward = true;
	};
	["Level 75"] = {
		Titles = {"_t11"};
		Badges = {2124594577};
		Recipes = {"recipe_searing_rune"};
		OneTimeReward = true;
	};
	["Level 80"] = {
		Badges = {2129720331};
		OneTimeReward = true;
	};
	["Level 85"] = {
		Badges = {2129720335};
		OneTimeReward = true;
	};
	["Level 90"] = {
		Titles = {"_t12"};
		Badges = {2129720340};
		OneTimeReward = true;
	};
	["Level 93"] = {
		Badges = {2129720344};
		OneTimeReward = true;
	};
	["Level 97"] = {
		Badges = {2129720345};
		OneTimeReward = true;
	};
	["Level 100"] = {
		Titles = {"_t13"};
		Badges = {2129720350};
		OneTimeReward = true;
	};
	["Level 100 R1"] = {
		Titles = {"_t14"};
		Badges = {2129720358};
		OneTimeReward = true;
	};
	["Group Knife 1"] = {
		Items = {
			exclusive_slycer = 1;
		};
		OneTimeReward = true;
	};
	["Group Knife 2"] = {
		Items = {
			the_group_effort = 1;
		};
		OneTimeReward = true;
	};
	VIP = {
		Coins = 1000;
		Items = {
			["1000_degree_knife"] = 1;
		};
		Recipes = {"recipe_noxium_vulcani"};
		OneTimeReward = false;
	};
	TradingVIP = {
		Items = {
			merchant_cabin = 1;
		};
		Titles = {"_t44"};
		OneTimeReward = true;
	};
	StarterPack = {
		Items = {
			red_slycer = 1;
			emerald_dream = 1;
			sapphire_sparkle_time = 1;
		};
		OneTimeReward = false;
	};
	PapaRoni = {
		Items = {
			["Papa Roni"] = 1;
		};
		OneTimeReward = false;
	};
	VoldarBundle = {
		Items = {
			Voldar = 1;
			voldar_light_sword = 1;
		};
		OneTimeReward = false;
	};
	DreadBundle = {
		Items = {
			Dread = 1;
			corrupted_dreadblade = 1;
		};
		OneTimeReward = false;
	};
	KringlerBundle = {
		Items = {
			Kringler = 1;
			kringlers_hook = 1;
		};
		OneTimeReward = false;
	};
	MalvusBundle = {
		Items = {
			Malvus = 1;
			malvus_knife = 1;
		};
		OneTimeReward = false;
	};
	SearingGuardBundle = {
		Items = {
			["Searing Guard"] = 1;
			searing_sword = 1;
		};
		OneTimeReward = false;
	};
	MrRisusBundle = {
		Items = {
			["Mr. Risus"] = 1;
			risus_sickle = 1;
		};
		OneTimeReward = false;
	};
	LayfaAshwellBundle = {
		Items = {
			["Layfa Ashwell"] = 1;
			ashwell_cleaver = 1;
		};
		OneTimeReward = false;
	};
	GrimsleyBundle = {
		Items = {
			Grimsley = 1;
			grimsleys_buster = 1;
		};
		OneTimeReward = false;
	};
	premium_slycer2023 = {
		Items = {
			premium_slycer2023 = 1;
		};
		Message = {"You got a 2023 limited knife because you own Premium.", "Limited items are valuable so make sure you know the value of this item before trading it."};
		OneTimeReward = true;
	};
	premium_slycer2024 = {
		Items = {
			premium_slycer2024 = 1;
		};
		Message = {"You got a 2024 limited knife because you own Premium.", "Limited items are valuable so make sure you know the value of this item before trading it."};
		OneTimeReward = true;
	};
	premium_slycer2025 = {
		Items = {
			premium_slycer2025 = 1;
		};
		Message = {"You got a 2025 limited knife because you own Premium.", "Limited items are valuable so make sure you know the value of this item before trading it."};
		OneTimeReward = true;
	};
	CPR = {
		Items = {
			["Corrupt Papa Roni"] = 1;
			charred_rolling_pin = 1;
		};
		OneTimeReward = true;
	};
	["Divine Cupid Toy"] = {
		Items = {
			Divine_Cupid = 1;
			cupid_spear = 1;
		};
		OneTimeReward = true;
	};
	stkr_release = {
		Gems = 100;
		Message = "In celebration of the release of STK Remastered, here's 100 Gems. Thank you for playing!";
		OneTimeReward = true;
	};
	millionth_slycer_reward = {
		Items = {
			millionth_slycer_reward = 1;
		};
		Message = "In celebration of 1 million votes! Thank you for playing!";
		OneTimeReward = true;
	};
	trance_fang = {
		Items = {
			trance_fang = 1;
		};
		Message = "Happy late Easter and St.Patrick's Day, thank you all for playing!";
		OneTimeReward = true;
	};
	free_xp_boost = {
		Items = {
			xp_boost_1h = 1;
		};
	};
	christmas_2022 = {
		Items = {
			minty_holiday_hook = 1;
		};
		Message = "?? Merry Christmas and happy holidays! ??";
		OneTimeReward = true;
	};
	scavenger_hunt_2022 = {
		Titles = {"_t33"};
		OneTimeReward = true;
	};
	valentine_2023 = {
		Items = {
			hollow_heart = 1;
		};
		Titles = {"_t34"};
		OneTimeReward = true;
	};
	code_red_award = {
		Items = {
			code_red = 1;
		};
		OneTimeReward = true;
	};
	metallica = {
		Items = {
			metal_season = 1;
		};
		Titles = {"_t35"};
		Badges = {2143962798};
		OneTimeReward = true;
	};
	oopsie_daisies_award = {
		Items = {
			oopsie_daisies = 1;
		};
		OneTimeReward = true;
	};
	mining_code = {
		Items = {
			charcoal_slycer = 1;
		};
		Recipes = {"recipe_motherlode_slycer"};
		OneTimeReward = true;
	};
	halloween_2024_code = {
		Items = {
			undead_candy = 1;
		};
		OneTimeReward = true;
	};
	friend_quest_2 = {
		DirewickTickets = 5;
		OneTimeReward = true;
	};
	step_right_up = {
		DirewickTickets = 5;
		OneTimeReward = true;
	};
	well_of_souls = {
		DirewickTickets = 5;
		OneTimeReward = true;
	};
	unlocking_lanterns = {
		DirewickTickets = 5;
		OneTimeReward = true;
	};
	candy_parade = {
		DirewickTickets = 5;
		OneTimeReward = true;
	};
	dead_fred_quest_2 = {
		DirewickTickets = 5;
		OneTimeReward = true;
	};
	festival_fiend_2 = {
		Items = {
			["Flotsam Direwick 2024"] = 1;
			allseeing_grave_spade = 1;
		};
		ProfileBanners = {"event_direwick2024"};
		Titles = {"_t46"};
		Badges = {3189832780132872};
		DirewickTickets = 10;
		OneTimeReward = true;
	};
	ghostly_slycer = {
		Items = {
			ghostly_slycer = 1;
		};
		OneTimeReward = true;
	};
	hallowheel_orange = {
		Coins = 20;
	};
	hallowheel_purple = {
		Items = {
			xp_boost_1h = 1;
		};
	};
	hallowheel_black = {
		Items = {
			direwick_chest_2024 = 1;
		};
	};
	hallowheel_white = {
		Items = {
			cursed_scallywag = 1;
		};
	};
	rudolph_golden_ravager = {
		Items = {
			rudolph_golden_ravager = 1;
		};
		OneTimeReward = true;
	};
	week_of_festivities = {
		Titles = {"_t41"};
		Gems = 10;
		OneTimeReward = true;
	};
	tis_the_season = {
		Titles = {"_t42"};
		Gems = 10;
		OneTimeReward = true;
	};
	build_a_snowman = {
		Gems = 10;
		OneTimeReward = true;
	};
	stockpile = {
		Gems = 10;
		OneTimeReward = true;
	};
	cookie_crumbles = {
		Gems = 10;
		OneTimeReward = true;
	};
	santas_little_helper = {
		Items = {
			gingerbread_cabin = 1;
			winter_crate_2023 = 5;
		};
		Titles = {"_t43"};
		OneTimeReward = true;
	};
	winter_2023_code = {
		Items = {
			holiday_splinter = 1;
		};
		Message = "?? Happy Holidays! ??";
		OneTimeReward = true;
	};
	the_hunt = {
		Items = {
			electroslycer = 1;
		};
		OneTimeReward = true;
	};
	high_voltage = {
		Items = {
			electroslycer_sc = 1;
		};
		XP = 1000;
		OneTimeReward = true;
	};
	machine_dagger_caution = {
		Items = {
			machine_dagger_caution = 1;
		};
		OneTimeReward = true;
	};
	machine_dagger_warning = {
		Items = {
			machine_dagger_warning = 1;
		};
		OneTimeReward = true;
	};
	pride_2024_code = {
		Items = {
			slyce_of_pride_2024 = 1;
		};
		OneTimeReward = true;
	};
	iridescent_slycer_code = {
		Items = {
			iridescent_slycer = 1;
		};
		OneTimeReward = true;
	};
	TheGames2024Gem1 = {
		Items = {};
		Badges = {4187252497388950};
		OneTimeReward = true;
	};
	TheGames2024Gem2 = {
		Items = {};
		Badges = {1012621411120678};
		OneTimeReward = true;
	};
	TheGames2024Gem3 = {
		Items = {};
		Badges = {2006923887102173};
		OneTimeReward = true;
	};
	TheGames2024Gem4 = {
		Items = {};
		Badges = {973925309725532};
		OneTimeReward = true;
	};
	TheGames2024Gem5 = {
		Items = {};
		Badges = {1957839903805140};
		OneTimeReward = true;
	};
	TheGames2024Quest1 = {
		Items = {};
		Badges = {2831053100811427};
		OneTimeReward = true;
	};
	TheGames2024Quest2 = {
		Items = {};
		Badges = {1433987187440310};
		OneTimeReward = true;
	};
	TheGames2024Quest3 = {
		Items = {};
		Badges = {914106327785506};
		OneTimeReward = true;
	};
	TheGames2024QuestCompletion = {
		Items = {
			unity_of_the_games = 1;
		};
		Badges = {};
		OneTimeReward = true;
	};
	TheGames2024GemCompletion = {
		Items = {
			bejeweled_slycer = 1;
		};
		Badges = {};
		OneTimeReward = true;
	};
	created_recycled_drainpipe = {
		Items = {
			recycled_drainpipe = 1;
		};
	};
	created_iridescent_slycer = {
		Items = {
			iridescent_slycer = 1;
		};
	};
	recipe_iridescent_slycer_reward = {
		Recipes = {"recipe_iridescent_slycer"};
		OneTimeReward = true;
	};
	created_iron_slycer = {
		Items = {
			iron_slycer = 1;
		};
	};
	created_steel_slycer = {
		Items = {
			steel_slycer = 1;
		};
	};
	created_reclaimed_slycer = {
		Items = {
			reclaimed_slycer = 1;
		};
	};
	created_railroad_wrench = {
		Items = {
			railroad_wrench = 1;
		};
	};
	created_frigid_frostar = {
		Items = {
			frigid_frostar = 1;
		};
	};
	created_rune_of_cataclysm = {
		Items = {
			rune_of_cataclysm = 1;
		};
	};
	created_golden_sun = {
		Items = {
			golden_sun = 1;
		};
	};
	created_oath_of_darkness = {
		Items = {
			oath_of_darkness = 1;
		};
	};
	created_rose_gold_blossom = {
		Items = {
			rose_gold_blossom = 1;
		};
	};
	created_molten_railroad_wrench = {
		Items = {
			molten_railroad_wrench = 1;
		};
	};
	created_radioactive_slycer = {
		Items = {
			radioactive_slycer = 1;
		};
	};
	created_searing_rune = {
		Items = {
			searing_rune = 1;
		};
	};
	created_noxium_vulcani = {
		Items = {
			noxium_vulcani = 1;
		};
	};
	created_super_cyan = {
		Items = {
			super_cyan = 1;
		};
	};
	created_sapphire_longsword = {
		Items = {
			sapphire_longsword = 1;
		};
	};
	created_enhanced_baseball_bat = {
		Items = {
			enhanced_baseball_bat = 1;
		};
	};
	created_rings_of_saturn = {
		Items = {
			rings_of_saturn = 1;
		};
	};
	created_light_blade = {
		Items = {
			light_blade = 1;
		};
	};
	created_shattered_planet = {
		Items = {
			shattered_planet = 1;
		};
	};
	created_illuminated_light_blade = {
		Items = {
			illuminated_light_blade = 1;
		};
	};
	created_void_blade = {
		Items = {
			void_blade = 1;
		};
	};
	created_crown_jewel = {
		Items = {
			crown_jewel = 1;
		};
	};
	created_shadowveil = {
		Items = {
			shadowveil = 1;
		};
	};
	created_daemonium = {
		Items = {
			daemonium = 1;
		};
	};
	created_death_adder = {
		Items = {
			death_adder = 1;
		};
	};
	created_motherlode_slycer = {
		Items = {
			motherlode_slycer = 1;
		};
	};
	created_gold_pickaxe = {
		Items = {
			gold_pickaxe = 1;
		};
	};
	created_tormented_pickaxe = {
		Items = {
			tormented_pickaxe = 1;
		};
	};
	created_prospector_khopesh = {
		Items = {
			prospector_khopesh = 1;
		};
	};
	collect_loot_100_reward = {
		Items = {
			element_of_ice = 1;
		};
	};
	revive_players_50_reward = {
		Items = {
			element_of_earth = 1;
		};
	};
	escape_10_reward = {
		Items = {
			element_of_wind = 1;
		};
	};
	kills_100_reward = {
		Items = {
			element_of_fire = 1;
		};
	};
	winner_25_reward = {
		Items = {
			element_of_lightning = 1;
		};
	};
}
local var346 = var9_result1_2.RewardOverride[var9_result1_2.ServerType]
if var346 then
	for i, v in pairs(var346) do
		module[i] = var9_result1.DeepCopy(v)
	end
end
for i_2, v_2 in pairs(module) do
	if v_2.Coins then
		local var353 = module[i_2]
		var353.Coins *= var9_result1_2.COIN_MULTIPLIER
	end
end
return module