-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNIBnBhcmFtcwVub2RlcwxpdGVyYXRlTm9kZXMEdHlwZQdhZGROb2RlBHRhc2sGbW9kdWxlPENhbid0IHByb2Nlc3MgdHJlZTsgdGFzayBsZWFmIG5vZGUgaGFzIG5vIGxpbmtlZCB0YXNrIG1vZHVsZQZhc3NlcnQFc3RhcnQDcnVuBmZpbmlzaAlvbnN1Y2Nlc3MGb25mYWlsBHRyZWU8Q2FuJ3QgcHJvY2VzcyB0cmVlOyB0cmVlIGxlYWYgbm9kZSBoYXMgbm8gbGlua2VkIHRyZWUgb2JqZWN0DmFsd2F5c19zdWNjZWVkPENhbid0IHByb2Nlc3MgdHJlZTsgc3VjY2VlZCBkZWNvcmF0b3Igd2l0aCBtdWx0aXBsZSBjaGlsZHJlbgdzdWNjZWVkC2Fsd2F5c19mYWlsOUNhbid0IHByb2Nlc3MgdHJlZTsgZmFpbCBkZWNvcmF0b3Igd2l0aCBtdWx0aXBsZSBjaGlsZHJlbgRmYWlsBmludmVydDtDYW4ndCBwcm9jZXNzIHRyZWU7IGludmVydCBkZWNvcmF0b3Igd2l0aCBtdWx0aXBsZSBjaGlsZHJlbixDYW4ndCBwcm9jZXNzIHRyZWU7IGhhbmdpbmcgaW52ZXJ0IGRlY29yYXRvcgZyZXBlYXQ7Q2FuJ3QgcHJvY2VzcyB0cmVlOyByZXBlYXQgZGVjb3JhdG9yIHdpdGggbXVsdGlwbGUgY2hpbGRyZW4sQ2FuJ3QgcHJvY2VzcyB0cmVlOyBoYW5naW5nIHJlcGVhdCBkZWNvcmF0b3IFY291bnQHcmVwZ29hbAhyZXBjb3VudApjaGlsZGluZGV4C2JyZWFrb25mYWlsCHNlcXVlbmNlO0Nhbid0IHByb2Nlc3MgdHJlZTsgc2VxdWVuY2UgY29tcG9zaXRlIG5vZGUgaGFzIG5vIGNoaWxkcmVuCHNlbGVjdG9yO0Nhbid0IHByb2Nlc3MgdHJlZTsgc2VsZWN0b3IgY29tcG9zaXRlIG5vZGUgaGFzIG5vIGNoaWxkcmVuBnJhbmRvbTlDYW4ndCBwcm9jZXNzIHRyZWU7IHJhbmRvbSBjb21wb3NpdGUgbm9kZSBoYXMgbm8gY2hpbGRyZW4HaW5kaWNlcwVwYWlycwZ3ZWlnaHQEcm9vdDdDYW4ndCBwcm9jZXNzIHRyZWU7IHJvb3Qgbm9kZSBmb3VuZCBhdCBub25yb290IGxvY2F0aW9uBWVycm9yG1Byb2Nlc3NOb2RlOiBiYWQgbm9kZS50eXBlIAh0b3N0cmluZwtQcm9jZXNzTm9kZQdydW5uaW5nBm9iamVjdAVpbmRleAZwYXVzZWQEd2Fybj5ub2RlLnJ1biBkaWQgbm90IGNhbGwgc3VjY2VzcywgcnVubmluZyBvciBmYWlsLCBhY3RpbmcgYXMgZmFpbA9iYWQgbm9kZS5zdGF0dXMPYmFkIHRyZWUgcmVzdWx0BG1hdGgNYmFkIG5vZGUudHlwZQlzZXRPYmplY3QFY2xvbmUHX19pbmRleAxzZXRtZXRhdGFibGUDbmV3CFNlcXVlbmNlCFNlbGVjdG9yBlJhbmRvbQdTdWNjZWVkBEZhaWwGSW52ZXJ0BlJlcGVhdARUYXNrBFRyZWUAEgYABwAAADn7AQAAlQABAN4AAAD7AAAA+wMBABwCAwCVAQIAmgADAAEAAADGAAAA3gACAPsAAgArACMA+wADAA4AAgDGAAAAggACAPsBBACVAAEA3gAEAPsDBQBNAgOfAQAAAE0BAlwCAAAA+wIEAIcAAQLeAAIA+wEEAPsFBQBNBAWfAQAAAE0DBFwCAAAAHAIDAPEBAgACAAAAqQAAAakAAQDeAAMA+wIBABwBAgCVAAEA3gAAAPsABgD7AQIA+wIBAJ8AAwH7AQEA+wIAAIcAAQJSAQAA+wQBABwDBACVAgMA+wMDAIIBBAADAgAAAAAAAPA/AwEDAgAsAAEYAAAAAQAAAAAAAQACAAEAAQACAAABAAAAAAAAAAEAAAAAAAAAAAAAAAEAAAABAAAAAgAAAQAAAAAALQAAAAAFAAMAAAAOjAAAAIwBAADGAgAAxgMAANkEAAASAQH/EgIAABIBAv8SAQP/EgEA/xICAQASAgIAwQAAAIIEAgAAAQAoAwEYAAABAQEAAAAAAAAAAAApAAAAAAYBAQAAAAziAQEAMAABcQAAAAD7AgAA+wUAABwEBQCVAwQCagECA1ICAQD7BAAAHAMEAIICAwADAwQFAQACAAAAAAAA8D8AQQUBGAAAAAEAAAAAAQAAAEIAAAAAEQIBAAAA0gXZAgAAEgABABIAAAASAgAA2QMBABIAAQBNBABxAAAAAPAEMwABAACATQYAnwIAAABNBQagAwAAAIEBBQQEAAAAbwYEAKQEBgAAAFBAnwQDAeIFBwBvBgEAMAYFcQAAAAAcBwEAlQYHCGoFAQZSBAUAHAYBAE0HAJ8CAAAATQYHoAMAAABNBQb8CQAAADAFBPwJAAAATQcAnwIAAABNBgegAwAAAE0FBjYKAAAAMAUENgoAAABNBwCfAgAAAE0GB6ADAAAATQUG/wsAAAAwBQT/CwAAAKkFAQAwBQR8DAAAAKkFAAAwBQSUDQAAAIIAAQBNBABxAAAAAPAEIQAOAACATQYAnwIAAABNBQZVDgAAAIEBBQQPAAAAbwYPAKQEBgAAAFBAnwQDAeIFBwBvBg4AMAYFcQAAAAAcBwEAlQYHCGoFAQZSBAUAHAYBAE0GAJ8CAAAATQUGVQ4AAAAwBQRVDgAAAKkFAQAwBQR8DAAAAKkFAAAwBQSUDQAAAIIAAQBNBABxAAAAAPAERQAQAACATQgAnwIAAABNBwhcEQAAABwGBwCMBwEA1AYCAAcAAACpBQABqQUBAIEBBQQSAAAAbwYSAKQEBgAAAFBAnwQDAU0GAJ8CAAAATQUGXBEAAAATBAUADgQhAIwHAACMCAAAxgkAAMYKAADZBAIAEgEI/xIAAQASAQn/EgEK/xIBB/8SAAAAEgIAAMYFAADGBgAAwQcAAGQEDgBNCgd8DAAAACoKBAAAAACAqQoBADAKB3wMAAAATQoHlA0AAAAqCgQAAAAAgKkKAQAwCgeUDQAAAG4E8f8DAAAAggABAOIFBwBvBhMAMAYFcQAAAAAcBwEAlQYHCGoFAQZSBAUAHAYBAKkFAQAwBQR8DAAAAIIAAQBNBABxAAAAAPAERQAUAACATQgAnwIAAABNBwhcEQAAABwGBwCMBwEA1AYCAAcAAACpBQABqQUBAIEBBQQVAAAAbwYVAKQEBgAAAFBAnwQDAU0GAJ8CAAAATQUGXBEAAAATBAUADgQhAIwHAACMCAAAxgkAAMYKAADZBAIAEgEI/xIAAQASAQn/EgEK/xIBB/8SAAAAEgIAAMYFAADGBgAAwQcAAGQEDgBNCgd8DAAAACoKBAABAACAqQoAADAKB3wMAAAATQoHlA0AAAAqCgQAAQAAgKkKAAAwCgeUDQAAAG4E8f8DAAAAggABAOIFBwBvBhYAMAYFcQAAAAAcBwEAlQYHCGoFAQZSBAUAHAYBAKkFAAAwBQSUDQAAAIIAAQBNBABxAAAAAPAEUQAXAACATQgAnwIAAABNBwhcEQAAABwGBwCMBwEA1AYCAAcAAACpBQABqQUBAIEBBQQYAAAAbwYYAKQEBgAAAFBAnwQDAU0IAJ8CAAAATQcIXBEAAAAcBgcADQYCAAgAAACpBQABqQUBAIEBBQQZAAAAbwYZAKQEBgAAAFBAnwQDAYwHAACMCAAAxgkAAMYKAADZBAIAEgEI/xIAAQASAQn/EgEK/xIBB/8SAAAAEgIAAMYFAADGBgAAwQcAAGQEHgBNCgd8DAAAACoKBQABAACAqQoAADAKB3wMAAAAZQAHAE0KB3wMAAAAKgoEAAAAAICpCgEAMAoHfAwAAABNCgeUDQAAACoKBQAAAACAqQoBADAKB5QNAAAAZQAHAE0KB5QNAAAAKgoEAAEAAICpCgAAMAoHlA0AAABuBOH/AwAAAIIAAQBNBABxAAAAAPAEfAAaAACATQgAnwIAAABNBwhcEQAAABwGBwCMBwEA1AYCAAcAAACpBQABqQUBAIEBBQQbAAAAbwYbAKQEBgAAAFBAnwQDAU0IAJ8CAAAATQcIXBEAAAAcBgcADQYCAAgAAACpBQABqQUBAIEBBQQcAAAAbwYcAKQEBgAAAFBAnwQDAeIGBwBvBxoAMAcGcQAAAAAcCAEAlQcICGoGAQdSBAYAHAUBAE0IAJ8CAAAATQcIGh0AAAAOBwwATQgAnwIAAABNBwgaHQAAAIwIAABgCAYABwAAAE0HAJ8CAAAATQYHGh0AAAArBgEAxgYAADAGBHgeAAAAjAYAADAGBGkfAAAAlQYFCDAGBPwgAAAAqQYBADAGBHwMAAAAqQYAADAGBJQNAAAATQcAnwIAAABNBgeAIQAAAIwKAACMCwAAxgwAAMYNAADZBwIAEgEL/xIAAQASAQz/EgEN/xIBCv8SAAAAEgIAAMYIAADGCQAAwQoAAGQHHABNDQp8DAAAACoNBAABAACAMAUKfAwAAABlAAcATQ0KfAwAAAAqDQQAAAAAgCsGAgAwBQp8DAAAAE0NCpQNAAAAKg0FAAAAAIArBgMAMAUKlA0AAABlAAYATQ0KlA0AAAAqDQMAAQAAgDAFCpQNAAAAbgfj/wMAAACCAAEATQQAcQAAAADwBDgAIgAAgE0IAJ8CAAAATQcIXBEAAAAcBgcAjAcBANQHAgAGAAAAqQUAAakFAQCBAQUEIwAAAG8GIwCkBAYAAABQQJ8EAwGMBwAAjAgAAMYJAADGCgAA2QQCABIBCP8SAAEAEgEJ/xIBCv8SAQf/EgAAABICAADGBQAAxgYAAMEHAABkBBQATQoHfAwAAAAqCgcAAQAAgCsJAgBSCggAKwoBAKkKAQAwCgd8DAAAAE0KB5QNAAAAKgoHAAEAAIArCQIAUgoIACsKAQCpCgEAMAoHlA0AAABuBOv/AwAAAIIAAQBNBABxAAAAAPAEOAAkAACATQgAnwIAAABNBwhcEQAAABwGBwCMBwEA1AcCAAYAAACpBQABqQUBAIEBBQQlAAAAbwYlAKQEBgAAAFBAnwQDAYwHAACMCAAAxgkAAMYKAADZBAIAEgEI/xIAAQASAQn/EgEK/xIBB/8SAAAAEgIAAMYFAADGBgAAwQcAAGQEFABNCgd8DAAAACoKBwAAAACAKwkCAFIKCAArCgEAqQoAADAKB3wMAAAATQoHlA0AAAAqCgcAAAAAgCsJAgBSCggAKwoBAKkKAAAwCgeUDQAAAG4E6/8DAAAAggABAE0EAHEAAAAA8ARNACYAAIBNCACfAgAAAE0HCFwRAAAAHAYHAIwHAQDUBwIABgAAAKkFAAGpBQEAgQEFBCcAAABvBicApAQGAAAAUECfBAMB4gUHAG8GJgAwBgVxAAAAABwHAQCVBgcIagUBBlIEBQAcBgEA/wUAAAAAAAAwBQQqKAAAAKQFKgAAAJBCTQgAnwIAAABNBghcEQAAAJ8FAgQXBSQATQsJnwIAAABNCgvLKwAAAA4KEgBNCwQqKAAAABwKCwAcDAEAlQsMCIwOAQBNDwmfAgAAAE0MD8srAAAAjA0BAKgMDwBNDwQqKAAAAEMQCg5qCw8Qiwz7/2UACQBNCgQqKAAAAE0NBCooAAAAHAwNAJULDAgcDQEAlQwNCGoMCgv7CgAAUgsJAFIMAQCfCgMBbgXb/wIAAACCAAEATQQAcQAAAADwBDoALAAAgBwGAQANBgIALQAAAKkFAAGpBQEAgQEFBC4AAABvBi4ApAQGAAAAUECfBAMB+wQAAE0FAFUOAAAAUgYBAJ8EAwGMBgEAHAQBAIwFAQCoBDAAhwcBBk0IB3wMAAAAKggGAAEAAIAcCQEAlQgJCDAIB3wMAAAAZQAIAE0IB3wMAAAAKggFAAAAAIAcCQEAlQgJLzAIB3wMAAAATQgHlA0AAAAqCAYAAQAAgBwJAQCVCAkIMAgHlA0AAABlAAgATQgHlA0AAAAqCAUAAAAAgBwJAQCVCAkvMAgHlA0AAACLBNz/ggABAKQEMQAAAABDbwYyAE0IAHEAAAAAuz8IAqQHNAAAADBDnwcCAnMFBgefBAIBggABADUDBAMGAwEDBwMIAwkEAABQQAUBAAIAAAAAAADwPwMKAwsDDAMNAw4DDwMQAxEDAgMSAxMDFAMVAxYDFwMYAxkDGgMbAxwDHQMeAx8DIAMhAyIDIwMkAyUDJgMnAygDKQQAAJBCAyoDKwIAAAAAAAAAAAMsAgAAAAAAAABAAy0EAAAAQwMuAy8EAAAwQwMBAgAlMAEYAAAAABkACgAAAAEAAAAAAAAAAAD2AAAAAQAAAQALAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAABAAAAAwAAAAEAAAAAAAAAAADrAAAAAQAAAQAWAAAAAAABAAABAAAABgAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAADEAAEBAQAAAAAAAAAAAAAAPAAAAAEAAAIAAAABAAD7AADbAAAAAQAAAQAuAAAABAAAAAEAAAAAAAAAAAAAAAAAAAACAAAAAACwAAEBAQAAAAAAAAAAAAAAUAAAAAEAAAIAAAABAAD7AADHAAAAAQAAAQBCAAAABAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAACdAAEBAQAAAAAAAAAAAAAAZAAAAAEAAAABAAAAAQAAAgAAAAEAAAABAAAAAQAA9wAADgAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAACjAAAAAQAAAQBeAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAEAAAEAAAEAAAMAAACAAAEBAQAAAAAAAAAAAAAAfwAAAAEAAAEAAAAAAQACAAAAAAEAAAEAAAABAPcAABEAAAABAAAAAAAAAAAAAAAAAAAAbQABAQEAAAAAAAAAAAAAAJQAAAABAAAAAAACAAAAAQAAAAAA+wAACgAAAAEAAAAAAAAAAAAAAAAAAABfAAEBAQAAAAAAAAAAAAAAogAAAAEAAAAAAAIAAAABAAAAAAD7AAAKAAAAAQAAAAAAAAAAAAAAAAAAAGoAAAABAAABAJcAAAABAAAAAAAAAAEAAAAAAQAAAQABAAAAAAAAAQAAAP8ABAAAAAAAAAAAAgAAAPYAABEAAAABAAAAAAAAAAAAAAIAAAAAAgAAAAEDAAAAAQAAAAABAAAAAQAAAAIAAAABAAAAAAEAAAABAAAA9AASAAAAAAAAAAAAAAIoAAAAAAwBAAEAAMkBowEAAE0BAMkAAAAADgEBAIIAAQBNAQBcAQAAAE0CAPoCAAAATQMAAgMAAAAcBAEATQUA2gQAAACpBgAAMAYA2gQAAACpBgEAMAYAyQAAAAB9A50ABAAAAIcGAQNNBwZxBQAAAPAHPwAGAACADgUCAKkFAABlAAgATQcG/AcAAAAOBwUATQcG/AcAAABSCAIA3QkAAJ8HAAFNBwY2CAAAAFIIAgDdCQAAnwcAAkcHBgAAAACApAgKAAAAkEBvCQsAnwgCAYwHAgANBwUADAAAgKkIAQAwCADaBAAAAGUAegANBw0ADQAAgE0IBv8OAAAADggGAE0IBv8OAAAAUgkCAFIKBwDdCwAAnwgAAU0DBnwPAAAAZQBrAA0HDQAQAACATQgG/w4AAAAOCAYATQgG/w4AAABSCQIAUgoHAN0LAACfCAABTQMGlBEAAABlAF0ApAgTAAAAIEFvCRQAnwgCAWUAWABNBwZxBQAAAPAHHAAVAACATQcGVRUAAADdCQAAvAcHNggAAACfBwACDQcFAAwAAICpCAEAMAgA2gQAAABlAEkADQcEAA0AAIBNAwZ8DwAAAGUAQwANBwQAEAAAgE0DBpQRAAAAZQA+AKQIEwAAACBBbwkWAJ8IAgFlADkATQcGcQUAAADwBwwAFwAAgE0HBioYAAAApAgaAABckIGMCQEATQsGKhgAAAAcCgsAnwgDAocDBwhlACoATQcGcQUAAADwBxUAGwAAgE0HBmkcAAAATQgGeB0AAACaBwcACAAAAIwHAAAwBwZpHAAAAE0DBnwPAAAAZQAaAE0IBmkcAAAAlQcIDTAHBmkcAAAATQMG/B4AAABlABIATQcGcQUAAADwBwQAHwAAgE0DBnwPAAAAZQALAE0HBnEFAAAA8AcEACAAAIBNAwaUEQAAAGUABACkBxMAAAAgQW8IIQCfBwIBSABi/8YGAACVBwQNmgMDAAcAAACMBgEAZQAGAJUHBBCaAwMABwAAAIwGAgBlAAEAjAYDAH0DAwAEAAAAUgcDACsHAQCMBwEAMAcAAgMAAACpBwAAMAcAyQAAAACCBgIAIgMxAwIDMgMzAzQDBAMGAwoDCwM1BAAAkEADNgIAAAAAAAAIQAIAAAAAAADwPwMMAw0CAAAAAAAAAEADDgMtBAAAIEEDNwMPAzgDJgMoAzkEAFyQgQMaAx8DHgMgAxMDFgM6AJkCCwEYAAEAAAIDAAEAAQABAgABAAABAAAEAAEFAAAAAQEAAQAAAQAAAAACAAAAAAEAAQAAAAECAAEAAAEBAAEAAAEAAAAAAAIAAAEAAQAAAQAAAAAAAgAAAgAAAAAEAAAAAQAAAAAAAQABAAABAQABAAABAAEAAAIAAAAABwAAAAEAAAAAAAAAAAAABgAAAAEAAAAAAAEAAAEAAAIAAAAAAQAABAAAAAEAAAMAAAABAAAEAAAAslYBAAABAAEAAAEAAgMAAAAAAAABAAACGQEAAAAKAgAAAAAVMAEA+gAAAACkAgIAAAAQQE0DAFwDAAAAnwICBBcCCgBNBwZxBAAAAPAHBwAFAACATQcGVQUAAABSCQEAvAcHBQYAAACfBwMBbgL1/wIAAACCAAEABwMyAykEAAAQQAMCAwQDDwM7AJADOwEYAAABAAAAAAABAAAAAQAAAAAA/gAFkQEAAAAPAQEAAAAx/wEAAAAAAACkAgEAAAAAQE0DAFwCAAAAnwICBBcCEgD/BwAAAAAAAKQIAQAAAABAUgkGAJ8IAgQXCAgA8AsGAAMAAIC8DQzaBAAAAJ8NAgJqDQcLZQABAGoMBwtuCPf/AgAAAGoHAQVuAu3/AgAAAOIDBwAwAQNcAgAAAE0EAAIFAAAAMAQDAgUAAABNBAD6BgAAADAEA/oGAAAA4gQJAPsFAAAwBQRuCAAAAJ49AwMEAAAApAILAAAAoECfAgMCggICAAwDKQQAAABAAwIDDwM8AzMDMgUDAgUGAz0FAQgDPgQAAKBAAJoDPAEYAAABAAAAAAABAAEAAAAAAQABAAAAAAL8AAf3AAsBAAEAAAABAAAAAQAAAAAA/AAAAJwBAAAACAICAAAAJE0CAVUAAAAA/wMAAAAAAAD7BAAA4gUDAG8GBAAwBgVxAQAAADACBVUAAAAA/wYAAAAAAAAwBgWfAgAAAFIGAwCfBAMB4gUIADADBVwFAAAAjAYBADAGBQIGAAAAxgYAADAGBfoHAAAA4gYKAPsHAQAwBwZuCQAAAJ49BQMGAAAApAQMAAAAsECfBAMCggQCAA0DDwMEAwEFAwEAAgMrAwIDMwMyBQMFBgcDPQUBCQM+BAAAsEAAsgM/ARgAAAEAAgAAAAAAAAAAAAAAAAIBAAEAAAEAAAEAAAAAAPwAAACzAQAAAAMBAAAAAAfiAQIAbwIDADACAXEAAAAAMAABnwEAAACCAQIABAMEAwEFAgABAyIAwwMAARgAAAAAAAAAwwEAAAADAQAAAAAH4gECAG8CAwAwAgFxAAAAADAAAZ8BAAAAggECAAQDBAMBBQIAAQMkAMQDAAEYAAAAAAAAAMQBAAAAAwEAAAAAB+IBAgBvAgMAMAIBcQAAAAAwAAGfAQAAAIIBAgAEAwQDAQUCAAEDJgDFAwABGAAAAAAAAADFAQAAAAMBAAAAAAfiAQIAbwIDADACAXEAAAAAMAABnwEAAACCAQIABAMEAwEFAgABAxEAyAMAARgAAAAAAAAAyAEAAAADAQAAAAAH4gECAG8CAwAwAgFxAAAAADAAAZ8BAAAAggECAAQDBAMBBQIAAQMUAMkDAAEYAAAAAAAAAMkBAAAAAwEAAAAAB+IBAgBvAgMAMAIBcQAAAAAwAAGfAQAAAIIBAgAEAwQDAQUCAAEDFwDKAwABGAAAAAAAAADKAQAAAAMBAAAAAAfiAQIAbwIDADACAXEAAAAAMAABnwEAAACCAQIABAMEAwEFAgABAxoAywMAARgAAAAAAAAAywEAAAADAQAAAAAH4gECAG8CAwAwAgFxAAAAADAAAZ8BAAAAggECAAQDBAMBBQIAAQMGAM4DAAEYAAAAAAAAAM4BAAAAAwEAAAAAB+IBAgBvAgMAMAIBcQAAAAAwAAGfAQAAAIIBAgAEAwQDAQUCAAEDDwDPAwABGAAAAAAAAADPAQAAAAQAAAECADKjAAAA/wAFAAAAAADAAQAAEgABAP8CAwAAAAAAwAMBADADAjYCAAAAwAMDADADAgUEAAAAwAMFABIAAgAwAwLaBgAAAMADBwASAAEAEgACADADAO8IAAAAwAMJADADAMIKAAAAwAMLADADAM8MAAAAwAMNADADAG4OAAAAwAMPADADALMQAAAAwAMRADADABcSAAAAwAMTADADAA4UAAAAwAMVADADAH0WAAAAwAMXADADAG4YAAAAwAMZADADALUaAAAAggACABsGAwYEAwsGBQM7BgYDPAYHAz8GCANABgkDQQYKA0IGCwNDBgwDRAYNA0UGDgNGBg8DRwYQA0gOAwQFBgcICQoLDA0ODxABAAECABYADtzyAAIMAHcAiQoAAPYYAADoABEA7wEAAP8AAAP9AAEA/wEAAP8AAAP9AAEA/wMBAAAAJAAAAPQAAAB3AAAACgAAABgAAAARAAAAAgAAAAMAAAABAAAAAgAAAAMAAAABAAAAABGyN69UoBrMC5/j+8TWiP82wi+4IIDzxVU=

-- Decompiler will be improved VERY SOON!
-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2025-12-11 01:07:37
-- Luau version 6, Types version 3
-- Time taken: 0.069991 seconds

local module_12 = {}
local function ProcessNode_upvr(arg1, arg2) -- Line 37, Named "ProcessNode"
	--[[ Upvalues[1]:
		[1]: ProcessNode_upvr (readonly)
	]]
	-- KONSTANTERROR: [0] 1. Error Block 1 start (CF ANALYSIS FAILED)
	local function _() -- Line 40, Named "iterateNodes"
		--[[ Upvalues[3]:
			[1]: arg2 (readonly)
			[2]: arg1 (readonly)
			[3]: ProcessNode_upvr (copied, readonly)
		]]
		local var149_upvw = 0
		local var150_upvw
		local var151_upvw
		local var152_upvw = 0
		return function() -- Line 44
			--[[ Upvalues[7]:
				[1]: var149_upvw (read and write)
				[2]: arg2 (copied, readonly)
				[3]: var150_upvw (read and write)
				[4]: var151_upvw (read and write)
				[5]: var152_upvw (read and write)
				[6]: arg1 (copied, readonly)
				[7]: ProcessNode_upvr (copied, readonly)
			]]
			var149_upvw += 1
			if var149_upvw == #arg2 + 1 then
				var150_upvw = nil
			end
			if not var150_upvw then
				if var151_upvw then
					return nil
				end
				var152_upvw += 1
				local var153 = arg1.params.nodes[var152_upvw]
				var150_upvw = var153
				if var152_upvw ~= #arg1.params.nodes then
					var153 = false
				else
					var153 = true
				end
				var151_upvw = var153
				var149_upvw = #arg2 + 1
				ProcessNode_upvr(var150_upvw, arg2)
			end
			return arg2[var149_upvw], #arg2 + 1, var151_upvw
		end
	end
	local function _(arg1_3) -- Line 65, Named "addNode"
		--[[ Upvalues[1]:
			[1]: arg2 (readonly)
		]]
		local module_9 = {}
		module_9.type = arg1_3
		arg2[#arg2 + 1] = module_9
		return module_9, #arg2
	end
	-- KONSTANTERROR: [0] 1. Error Block 1 end (CF ANALYSIS FAILED)
	-- KONSTANTERROR: [10] 9. Error Block 2 start (CF ANALYSIS FAILED)
	assert(arg1.params.module, "Can't process tree; task leaf node has no linked task module")
	local tbl = {
		type = "task";
	}
	arg2[#arg2 + 1] = tbl
	local var156 = tbl
	var156.start = arg1.params.module.start
	var156.run = arg1.params.module.run
	var156.finish = arg1.params.module.finish
	var156.onsuccess = true
	var156.onfail = false
	do
		return
	end
	-- KONSTANTERROR: [10] 9. Error Block 2 end (CF ANALYSIS FAILED)
	-- KONSTANTERROR: [60] 40. Error Block 3 start (CF ANALYSIS FAILED)
	-- KONSTANTERROR: [60] 40. Error Block 3 end (CF ANALYSIS FAILED)
end
local tbl_6_upvr = {
	run = function(arg1, ...) -- Line 281, Named "run"
		-- KONSTANTERROR: [0] 1. Error Block 69 start (CF ANALYSIS FAILED)
		if arg1.running then return end
		arg1.paused = false
		arg1.running = true
		-- KONSTANTERROR: [0] 1. Error Block 69 end (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [177] 119. Error Block 52 start (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [177] 119. Error Block 52 end (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [20] 14. Error Block 4 start (CF ANALYSIS FAILED)
		-- KONSTANTWARNING: Failed to evaluate expression, replaced with nil [177.1734]
		-- KONSTANTERROR: [20] 14. Error Block 4 end (CF ANALYSIS FAILED)
	end;
	setObject = function(arg1, arg2) -- Line 400, Named "setObject"
		arg1.object = arg2
		for _, v in pairs(arg1.nodes) do
			if v.type == "tree" then
				v.tree:setObject(arg2)
			end
		end
	end;
}
function tbl_6_upvr.clone(arg1) -- Line 410
	--[[ Upvalues[1]:
		[1]: tbl_6_upvr (readonly)
	]]
	local tbl_3 = {}
	for i_2, v_2 in pairs(arg1.nodes) do
		for i_3, v_3 in pairs(v_2) do
			if i_3 == "tree" then
				({})[i_3] = v_3:clone()
			else
				-- KONSTANTERROR: Expression was reused, decompilation is incorrect
				;({})[i_3] = v_3
			end
		end
		-- KONSTANTERROR: Expression was reused, decompilation is incorrect
		tbl_3[i_2] = {}
	end
	return setmetatable({
		nodes = tbl_3;
		index = arg1.index;
		object = arg1.object;
	}, {
		__index = tbl_6_upvr;
	})
end
function module_12.new(arg1, arg2) -- Line 434
	--[[ Upvalues[2]:
		[1]: ProcessNode_upvr (readonly)
		[2]: tbl_6_upvr (readonly)
	]]
	local tbl_2 = {}
	ProcessNode_upvr({
		type = "root";
		tree = arg2.tree;
		params = {};
	}, tbl_2)
	return setmetatable({
		nodes = tbl_2;
		index = 1;
		object = nil;
	}, {
		__index = tbl_6_upvr;
	})
end
function module_12.Sequence(arg1) -- Line 451
	local module_8 = {
		type = "sequence";
	}
	module_8.params = arg1
	return module_8
end
function module_12.Selector(arg1) -- Line 452
	local module_10 = {
		type = "selector";
	}
	module_10.params = arg1
	return module_10
end
function module_12.Random(arg1) -- Line 453
	local module_7 = {
		type = "random";
	}
	module_7.params = arg1
	return module_7
end
function module_12.Succeed(arg1) -- Line 456
	local module = {
		type = "always_succeed";
	}
	module.params = arg1
	return module
end
function module_12.Fail(arg1) -- Line 457
	local module_2 = {
		type = "always_fail";
	}
	module_2.params = arg1
	return module_2
end
function module_12.Invert(arg1) -- Line 458
	local module_3 = {
		type = "invert";
	}
	module_3.params = arg1
	return module_3
end
function module_12.Repeat(arg1) -- Line 459
	local module_6 = {
		type = "repeat";
	}
	module_6.params = arg1
	return module_6
end
function module_12.Task(arg1) -- Line 462
	local module_5 = {
		type = "task";
	}
	module_5.params = arg1
	return module_5
end
function module_12.Tree(arg1) -- Line 463
	local module_4 = {
		type = "tree";
	}
	module_4.params = arg1
	return module_4
end
return module_12