-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgN2E0NyYXRlUmV3YXJkU2VsZWN0ZWQETmFtZQpGaXJlU2VydmVyBkNhbWVyYQZDRnJhbWUDbmV3Bmxvb2tBdAlIZWFkU2NhbGUEbWF0aANzaW4DY29zB1ZlY3RvcjMGTmV3R3VpEENyYXRlT3BlbmluZ0NlbGwGSXRlbUlEBENlbGwFX21haWQEX3NmeAhJbnN0YW5jZQtGaWVsZE9mVmlldwRUeXBlBUtuaWZlBEl0ZW0GV2VhcG9uDUN1cnJlbnRDYW1lcmEGT2JqZWN0BUNsb25lB19vYmplY3QGaXBhaXJzC0dldENoaWxkcmVuCEJhc2VQYXJ0A0lzQQ1Ub09iamVjdFNwYWNlBlBhcmVudAdQaXZvdFRvBXBhaXJzDFRvV29ybGRTcGFjZQRTaXplAVkBWgVjbGFtcApFcXVpcEtuaWZlBktpbGxlcgNATWUNcmJ4YXNzZXRpZDovLwdJbWFnZUlkBlVzZXJJZARFbnVtDVRodW1ibmFpbFR5cGUISGVhZFNob3QNVGh1bWJuYWlsU2l6ZQtTaXplMTUweDE1MBVHZXRVc2VyVGh1bWJuYWlsQXN5bmMFSW1hZ2UIRGVlcEJvb20FQ2FiaW4KRXF1aXBDYWJpbgRMb290CkNvbnN1bWFibGULQnV0dG9uUHJlc3MHVmlzaWJsZQxRdWVzdGlvbk1hcmsGQWN0aXZlClNlbGVjdGFibGUPQXV0b0J1dHRvbkNvbG9yD0RlZmF1bHRHcmFkaWVudA5GaW5kRmlyc3RDaGlsZAdEZXN0cm95C1VJR3JhZGllbnRzBE5vbmULUkFSSVRZX05BTUUGUmFyaXR5CUFjdGl2YXRlZAdDb25uZWN0GEdldFByb3BlcnR5Q2hhbmdlZFNpZ25hbBFIZWFkU2NhbGVMaXN0ZW5lcghRdWFudGl0eQF4BFRleHQGX19pbml0DFZpc2libGVUd2VlbgZDYW5jZWwHVUlTY2FsZQlUd2VlbkluZm8FU2NhbGUGQ3JlYXRlBFBsYXkKU2V0VmlzaWJsZQpEb0NsZWFuaW5nBHRhc2sFZGVsYXkEZ2FtZQxUd2VlblNlcnZpY2UKR2V0U2VydmljZQdQbGF5ZXJzB3JlcXVpcmURUmVwbGljYXRlZFN0b3JhZ2UETG9hZAVFbnVtcwlDb25zdGFudHMNQnV0dG9uSGFuZGxlcgpHdWlIYW5kbGVyC01lbnVIYW5kbGVyCURhdGFiYXNlcwRNYWlkBUNsYXNzB05ldHdvcmsHU291bmRGWAtMb2NhbFBsYXllcgZBc3NldHMIR2V0RnJhbWUJSW52ZW50b3J5BUNPTE9SCkxJTUVfR1JFRU4KTElHSFRfQkxVRQlTb3J0T3JkZXIDR2V0A0FsbAAHBQACAAAACfsAAABvAgAA+wQBAE0DBLoBAAAAvAAAawIAAACfAAQBggABAAMDAQMCAwMAcQABGAAAAAAAAAAAAXIAAAAADAABAAAALfsBAABNAAFZAAAAAKQCAwAACBCAjAMAAG8EBACMBQAAnwIEAqQDBgAAFBCA+wkAAE0ICVkAAAAATQcI/AgAAAC7GAcCpAYLAAAokICfBgICWwUGB4wGAAD7CwAATQoLWQAAAABNCQr8CAAAALsJCQKkCA0AADCQgJ8IAgJbBwgHTDYAAqQEDwAACOCAnwQEAkw2AAKkBQ8AAAjggJ8FAQKfAwMCCQECAzABAIUBAAAAggABABADBAMFAwYEAAgQgALsUbgeheuxPwMHBAAUEIACAAAAAADgZUADCAMJAwoEACiQgAMLBAAwkIADDAQACOCAAHYAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAF3AAAAABgECAAAAMIC+wUAAE0EBTIAAAAAbwUBAJ8EAgIwAQDaAgAAADAEAO0DAAAA+wYBAE0FBu8EAAAAnwUBAjAFAMEFAAAAxgUAADAFAFwGAAAApAUIAAAQcIBvBgkAnwUCAjAFAFkJAAAATQUAWQkAAACMBgEAMAYFYQoAAAAqA/MAAQAAgPsGAgCHBQYBTQYFEQsAAADGBwAA8AZ5AAwAAIBNCATKDQAAAE0HCF8OAAAATQgAWQkAAAAwCAdIDwAAAE0IBdoQAAAAvAgIOhEAAACfCAICMAgANhIAAABNCAA2EgAAAG8JEAAwCQi6EwAAAP8IAAAAAAAApAkVAAAAQEFNCgA2EgAAALwKCmgWAAAAnwoCAJ8JAARRCQ8AbxAXALwODf4YAAAAnw4DAg4OCgBNDwA2EgAAAE0OD4UZAAAATRANhRkAAAC8Dg5GGgAAAJ8OAwJqDggNbgnw/wIAAIBNCQA2EgAAADAHCSQbAAAATQkANhIAAACkCxwAABCQgYwMAACMDQAAjA4AAG8PHQBvEB4AbxEeAIwSAABvEx8AbxQgAIwVAQBvFiEAbxchAJ8LDQC8CQnCIgAAAJ8JAAGkCSQAAAAwQlIKCACfCQIEFwkKAE0PADYSAAAATQ4PhRkAAABSEA0AvA4OoCUAAACfDgMCMA4MhRkAAABuCfX/AgAAAE0JAFkJAAAATQ8ANhIAAABNDg8vKAAAAE0NDngpAAAAPgwNJ1sLDCZNEQA2EgAAAE0QES8oAAAATQ8QeywAAABbDg8reA0OKowOAACMDwoATC4AAqQMLwAAuNCCnwwEAkMKCwwwCglhCgAAAG8JMAAwCQBcBgAAAGUAPgDwBh0AMQAAgE0IBMoNAAAATQcIlTEAAADwAQYAMgAAAG8JMwBNCgWWNAAAAHMICQorCAsA+wgDAPsLBABNCgvmNQAAAKQLOQA43GDDpAw8ADvoYMO8CAhDPQAAAJ8IBQIwCAepPgAAAG8IPwAwCABcBgAAAGUAIADwBg8AQAAAgE0IBMoNAAAATQcIakAAAABvCTMATQoFljQAAABzCAkKMAgHqT4AAABvCEEAMAgAXAYAAABlABAA8AYGAEIAAIBNCATKDQAAAE0HCGpCAAAAZQAJAPAGCABDAACATQgEyg0AAABNBwhqQgAAAG8IRAAwCABcBgAAAKkIAQAwCAeARQAAAE0JAO0DAAAATQgJfkYAAACpCQAAMAkIgEUAAABNCADtAwAAAKkJAAAwCQiDRwAAAE0IAO0DAAAAqQkAADAJCCRIAAAATQgA7QMAAACpCQAAMAkI10kAAABvCkoAvAgEA0sAAACfCAMCRwgEAAAAAAC8CQhQTAAAAJ8JAgH7CgUATQkK0k0AAAD7DgYATQ0OnE8AAABNDgXyUAAAAIcMDQ6QCwxOvAkJA0sAAACfCQMCvAkJOhEAAACfCQICMAQJJBsAAABlAAgATQUEHlEAAADZBwAAEgIHABIABAC8BQXHUgAAAJ8FAwFNBQDBBQAAAE0GAFkJAAAAbwhTALwGBpRUAAAAnwYDAtkIAQASAAAAvAYGx1IAAACfBgMCMAYFJVUAAABNBQBZCQAAAIwGAAAwBgX8UwAAAE0GAO0DAAAATQUGWVYAAABvB1cAUggCAHMGBwgwBgX1WAAAAE0GAO0DAAAATQUGWVYAAACMBwEAtwcCAAIAAACpBgABqQYBADAGBYBFAAAAggACAFkDDQMOAw8DEAMGAxEDEgMTBAAQcIADBAMUAxUDFgMXAxgDGQMaAxsDHAMCAx0EAABAQQMeAx8DIAMFAyEDIgQAEJCBAuMyNQAAAG4+AhqqKoCeoOa/AsdT9F+eoOY/AsdT9F+eoOa/AkJ3IwAAAGQ+AyMDJAQAADBCAyUCSOF6FK5H6T8CnMQgsHJoCEADJgMnApqZmZmZmek/AgAAAAAAANg/AygDCQMpBAC40IIDKgMrAywDLQMuAy8DMAMxAzIEONxgwwMzAzQEO+hgwwM1AzYDNwM4AzkDOgM7AzwDPQM+Az8DQANBA0IDQwNEA0UDRgNHA0gDSQNKAwgDSwNMA00DTgNPAgABIlABGAAAAAAAAgABAAEAAAAAAAEAAAIAAAAAAAEAAAAAAwADAAEAAQIAAQAAAAEAAAABAAAAAAAAAQAAAAAHAAEAAAAAAAAAAAEAAAAAAQAAAAAAAAAAAP4ABQAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAABAAAAAAAAAAAA/wAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAQABAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAQABAAAAAQAAAAAAAQAAAAEAAQAAAAABAAEAAAABAAADAAABAAAAAAAAAQAAAAABAAAAAAEAAAAABAAAAAEAAQAAAwAAAAAAAAAAAAAAAAAAAAEAAAIAAAAAAAAABQAAAAAAAAAAAAAAAAAABAAAAAACAAAAAAAAAAABAAAAAAAAAAAAAAIkAAAAAAkCAQAAADJNAwDBAAAAAE0CA64BAAAARwINAAAAAABNAwDBAAAAAE0CA64BAAAAvAICoQIAAACfAgIBTQIAwQAAAADGAwAAMAMCrgEAAABNAgDBAAAAAPsDAABNBgDtAwAAAE0FBisEAAAApAYHAAAYUIBvBwgAnwYCAuIHCgAqAQMAAAAAAIwIAQBlAAEAjAgAADAIB4QJAAAAvAMDlgsAAACfAwUCMAMCrgEAAABNAwDBAAAAAE0CA64BAAAAvAIC7gwAAACfAgIBggABAA0DEQNRA1IDEANTA1QDBgQAGFCAApqZmZmZmck/A1UFAQkDVgNXAIIBWAEYAAAAAAAAAQAAAAAAAAEAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAGDAAAAAAIAAQAAAA/7AQAATQABwQAAAAC8AABRAQAAAJ8AAgH7AQAATQAB7QIAAAC8AABQAwAAAJ8AAgHGAAAA3gAAAIIAAQAEAxEDWQMQA0QAmAEAARgAAAAAAAABAAAAAAABAAGZAAAAAAYCAAAAACkOAQ0ATQIAwQAAAAC8AgJRAQAAAJ8CAgFNAgDtAgAAALwCAlADAAAAnwICAcYAAADBAAAAggABAE0FAO0CAAAATQQFKwQAAABNAwSEBQAAAIwEAAC3BAIAAwAAAKkCAAGpAgEADgIEAKkFAAC8AwCpBgAAAJ8DAwGkAwkAACBwgA4CAgBvBAoAZQABAIwEAADZBQAAEgEA/58DAwHBAAAAggABAAsDEQNZAxADRANTA1UDWANaA1sEACBwgAIAAAAAAADgPwEEjAFEARgAAQAAAAABAAAAAAEBAAMAAAAAAAAAAAAAAQEAAAACAAAAAAAAAAAFAI0AAAAAFwAAAQIAbaMAAACkAAEAAAAAQG8CAgC8AAAWAwAAAJ8AAwKkAQEAAAAAQG8DBAC8AQEWAwAAAJ8BAwKkAgYAAABQQKQFAQAAAABATQQFPwcAAABNAwR+CAAAAJ8CAgJSAwIAbwQJAJ8DAgJSBAIAbwUKAJ8EAgJSBQIAbwYLAJ8FAgJSBgIAbwcMAJ8GAgJSBwIAbwgNAJ8HAgJSCAIAbwkOAJ8IAgJSCQIAbwoPAJ8JAgJSCgIAbwsQAJ8KAgJSCwIAbwwRAJ8LAgJSDAIAbw0SAJ8MAgJSDQIAbw4TAJ8NAgKkEAEAAAAAQE0PEFAEAAAATQ4PMRQAAACkEQEAAAAAQE0QET8HAAAATQ8QgRUAAABNEAYaFgAAAG8RFwCfEAICTRIE7RgAAABNERI8GQAAAE0TBO0YAAAATRITwxoAAABNFAO5GwAAAE0TFPIcAAAATRQIfx0AAABvFR4AnxQCAlIVCwBvFh8AnxUCAsAWIAASAAYAEgAKABIAFAASAAEAEgAOABIADwASAAQAEgAMADAWFQEhAAAAwBYiABIAAAAwFhWpIwAAAMAWJAAwFhVQJQAAAIIVAgAmA1wEAAAAQANdA14DXwNgBAAAUEADYQNiA2MDZANlA2YDZwNoA1UDaQNqA2sDbANtA24DbwNwA3EDcgNzA3QDSAN1A3YDDgYCA1AGAwNYBgUDRAMCAwUBAAEYAAEAAAAAAAEAAAAAAAMAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAIAAAEAAAEAAAEAAAMAAAAAAAEAAAAAAAEAAAACAAAAAQAAAAEAAAADAAAAAgAAAgAAAAAAAAAAAABgAAAACgAAEwEAAAAABmqtbnSP3t22kzzrnpkdz3katXkAWGkEdQ==

-- Decompiler will be improved VERY SOON!
-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2025-12-11 01:07:12
-- Luau version 6, Types version 3
-- Time taken: 0.006909 seconds

local Load = require(game.ReplicatedStorage.Load)
local var1_result1_upvr_3 = Load("Constants")
local var1_result1_upvr_2 = Load("GuiHandler")
local var4 = Load("Class")("CrateOpeningCell")
local var1_result1_upvr_4 = Load("Maid")
local any_Get_result1_upvr = Load("Databases").Get("All")
local Players_upvr = game:GetService("Players")
local LocalPlayer_upvr = game.Players.LocalPlayer
local Assets_upvr = game.ReplicatedStorage.Assets
local var1_result1_upvr = Load("Network")
function var4.__init(arg1, arg2, arg3, arg4) -- Line 34
	--[[ Upvalues[8]:
		[1]: var1_result1_upvr_2 (readonly)
		[2]: var1_result1_upvr_4 (readonly)
		[3]: any_Get_result1_upvr (readonly)
		[4]: Players_upvr (readonly)
		[5]: LocalPlayer_upvr (readonly)
		[6]: Assets_upvr (readonly)
		[7]: var1_result1_upvr_3 (readonly)
		[8]: var1_result1_upvr (readonly)
	]]
	-- KONSTANTERROR: [0] 1. Error Block 1 start (CF ANALYSIS FAILED)
	local any_NewGui_result1 = var1_result1_upvr_2.NewGui("CrateOpeningCell")
	arg1.ItemID = arg2
	arg1.Cell = any_NewGui_result1
	arg1._maid = var1_result1_upvr_4.new()
	arg1._sfx = nil
	arg1.Camera = Instance.new("Camera")
	arg1.Camera.FieldOfView = 1
	-- KONSTANTERROR: [0] 1. Error Block 1 end (CF ANALYSIS FAILED)
	-- KONSTANTERROR: [31] 21. Error Block 52 start (CF ANALYSIS FAILED)
	local var16 = any_Get_result1_upvr[arg2]
	if var16.Type == "Knife" then
		local Weapon = any_NewGui_result1.Item.Weapon
		Weapon.CurrentCamera = arg1.Camera
		arg1._object = var16.Object:Clone()
		arg1._object.Name = "Object"
		for _, v in ipairs(arg1._object:GetChildren()) do
			if v:IsA("BasePart") then
				({})[v] = arg1._object.CFrame:ToObjectSpace(v.CFrame)
			end
		end
		arg1._object.Parent = Weapon
		arg1._object:PivotTo(CFrame.new(0, 0, 0, 5.58793545e-08, -0.707106829, -0.707106829, 0, 0.707106769, -0.707106769, 1, 3.7252903e-08, 3.7252903e-08))
		-- KONSTANTERROR: Expression was reused, decompilation is incorrect
		for i_2, v_2 in pairs({}) do
			i_2.CFrame = arg1._object.CFrame:ToWorldSpace(v_2)
		end
		arg1.Camera.FieldOfView = arg1._object.Size.Y / 3.051 * 0.79 + math.clamp(arg1._object.Size.Z * 0.375 - 0.8, 0, 10)
		arg1._sfx = "EquipKnife"
		-- KONSTANTWARNING: GOTO [220] #144
	end
	-- KONSTANTERROR: [31] 21. Error Block 52 end (CF ANALYSIS FAILED)
end
local TweenService_upvr = game:GetService("TweenService")
function var4.SetVisible(arg1, arg2) -- Line 130
	--[[ Upvalues[1]:
		[1]: TweenService_upvr (readonly)
	]]
	local var25
	if arg1._maid.VisibleTween ~= nil then
		arg1._maid.VisibleTween:Cancel()
		arg1._maid.VisibleTween = nil
	end
	local tbl = {}
	if arg2 ~= false then
		var25 = 1
	else
		var25 = 0
	end
	tbl.Scale = var25
	arg1._maid.VisibleTween = TweenService_upvr:Create(arg1.Cell.UIScale, TweenInfo.new(0.2), tbl)
	arg1._maid.VisibleTween:Play()
end
function var4.Destroy(arg1, arg2) -- Line 140
	if arg2 then
		arg1._maid:DoCleaning()
		arg1.Cell:Destroy()
		local var27_upvw
	else
		if 0 >= var27_upvw.Cell.UIScale.Scale then
			local _ = false
			-- KONSTANTWARNING: Skipped task `defvar` above
		else
		end
		if true then
			var27_upvw:SetVisible(false)
		end
		-- KONSTANTERROR: Expression was reused, decompilation is incorrect
		if true then
		else
		end
		task.delay(0, function() -- Line 152
			--[[ Upvalues[1]:
				[1]: var27_upvw (read and write)
			]]
			var27_upvw._maid:DoCleaning()
			var27_upvw.Cell:Destroy()
			var27_upvw = nil
		end)
	end
end
return var4