-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgNEB0VuYWJsZWQGUGFyZW50BGdhbWUHUGxheWVycxZHZXRQbGF5ZXJGcm9tQ2hhcmFjdGVyCkRpc2Nvbm5lY3QETG9vdAxHZXRBdHRyaWJ1dGUKSXRlbVJld2FyZA9WRlhBZGRDb2luc0xvb3QGQm9yZGVyBEZpcmUOR2V0RGVzY2VuZGFudHMIQmFzZVBhcnQDSXNBBE5hbWUMVHJhbnNwYXJlbmN5CE1lc2hQYXJ0AAlUZXh0dXJlSUQFRGVjYWwMQmlsbGJvYXJkR3VpBHRhc2sFZGVsYXkMV2FpdEZvckNoaWxkB1RvdWNoZWQHQ29ubmVjdAlMb290QWRkZWQJd29ya3NwYWNlA01hcA5GaW5kRmlyc3RDaGlsZApMb290U3Bhd25zB0Rlc3Ryb3kKRnVzZVNwYXducwRUZWFtBVRFQU1TBktpbGxlcgRuYW1lBXBjYWxsCkdldFNlcnZpY2URQ29sbGVjdGlvblNlcnZpY2UHcmVxdWlyZRFSZXBsaWNhdGVkU3RvcmFnZQRMb2FkCkd1aUhhbmRsZXIHTmV0d29yawlDb25zdGFudHMFRW51bXMLTWVudUhhbmRsZXINQnV0dG9uSGFuZGxlcglEYXRhYmFzZXMDR2V0CExvb3RDZWxsCEdldEZyYW1lCVBsYXllckhVRAtMb2NhbFBsYXllcgZBc3NldHMIQmFja3BhY2sJTUFYX0lURU1TCk1lbWJlcnNoaXAMTUFYX0JBQ0tQQUNLFkdldEluc3RhbmNlQWRkZWRTaWduYWwGaXBhaXJzCUdldFRhZ2dlZA5Jc0Rlc2NlbmRhbnRPZgZUZWFtSUQZR2V0QXR0cmlidXRlQ2hhbmdlZFNpZ25hbApCaW5kRXZlbnRzAAcCAAEAAAAF+wAAAKkBAAAwAQDwAAAAAIIAAQABAwEAhgEAARgAAAAAAYcAAAAADAEFAAAAZA4AYgBNAQAkAAAAAA4BXwCkAgIAAAAQQE0BAlADAAAATQMAJAAAAAC8AQGJBAAAAJ8BAwIOAVUA+wIAAJoBUwACAAAA+wIBALwCAhoFAAAAnwICAfsDAgBNAgMkAAAAAG8EBgC8AgISBwAAAJ8CAwL7BQMAhwQFAk0DBLgIAAAAKwMPAPsEBABvBgkA+wgCAE0HCCQAAAAAbwkGALwHBxIHAAAAnwcDAvsJAgBNCAnGCgAAALwEBN0LAAAAnwQFAfsEAgC8BARHDAAAAJ8EAgRkBCwAbwsNALwJCP4OAAAAnwkDAg4JEABNCQi6DwAAAPAJDQAKAAAAjAkBADAJCNkQAAAAbwsRALwJCP4OAAAAnwkDAg4JGwBvCRIAMAkIhBMAAABlABcAbwsUALwJCP4OAAAAnwkDAg4JBACMCQEAMAkI2RAAAABlAA4AbwsVALwJCP4OAAAAnwkDAg4JCQCpCQEAMAkI8BYAAACkCRkAAGBwgYwKAwDZCwAAEgAIAJ8JAwFuBNP/AgAAAIIAAQAaAwIDAwQAABBAAwQDBQMGAwcDCAMJAwoDCwMMAw0DDgMPAxADEQMSAxMDFAMVAxYDAQMXAxgEAGBwgQEAbwABGAAAAAABAAAAAAAAAAABAAAAAQAAAAEAAAAAAAABAAAAAQEAAAAAAAAAAAAAAAAAAAIAAAAAAgAAAAAAAAAAAQAAAQAAAAABAAAAAwAAAAABAAAAAgAAAAABAAABAAAAAADzABRwAAAAAAcBAwAAABTGAQAAbwUAAIwGBAC8AwDTAQAAAJ8DBAJNAgMsAgAAANkEAAASAgAAEgEB/xIAAAASAgEAEgICALwCAscDAAAAnwIDAlIBAgDBAQAAggABAAQDCwMZAxoDGwEBbBwBGAABAAAAAAAAAAAAAAAAAAAAAB8AbgAAAAAGAAAAAAARpAEBAAAAAECkAwEAAAAAQG8FAgC8AwMSAwAAAJ8DAwC8AQEDBAAAAJ8BAAJNAAFIBQAAALwAAFAGAAAAnwACAYIAAQAHAx0EAAAAQAMeAwgDHwMgAyEAnQEAARgAAAAAAAAAAAAAAAAAAAAAAZ4AAAAABgAAAAAAEaQBAQAAAABApAMBAAAAAEBvBQIAvAMDEgMAAACfAwMAvAEBAwQAAACfAQACTQABgwUAAAC8AABQBgAAAJ8AAgGCAAEABwMdBAAAAEADHgMIAx8DIgMhAKABAAEYAAAAAAAAAAAAAAAAAAAAAAGhAAAAAAUAAgAAABf7AgAATQECbAAAAABNAAG6AQAAAPsEAQBNAwRiAgAAAE0CA5UDAAAATQECWgQAAACaAAkAAQAAAKQABgAAAFBAwAEHAJ8AAgGkAAYAAABQQMABCACfAAIBggABAAkDIwMQAyQDJQMmAycEAABQQAYDBgQCAwSbAQABGAAAAAAAAAAAAAAAAAAAAQAAAAMAAAAEnAAAAAAbAAABAACOAaMAAAD/AAAAAAAAAKQBAQAAAABAbwMCALwBARYDAAAAnwEDAqQCAQAAAABAbwQEALwCAhYDAAAAnwIDAqQDBgAAAFBApAYBAAAAAEBNBQY/BwAAAE0EBX4IAAAAnwMCAlIEAwBvBQkAnwQCAlIFAwBvBgoAnwUCAlIGAwBvBwsAnwYCAlIHAwBvCAwAnwcCAlIIAwBvCQ0AnwgCAlIJAwBvCg4AnwkCAlIKAwBvCw8AnwoCAk0LCn8QAAAAbwwRAJ8LAgJSDAMAbw0SAJ8MAgJNDQQaEwAAAG8OFACfDQICTQ4BMRUAAACkEQEAAAAAQE0QET8HAAAATQ8QgRYAAABNEAQaEwAAAG8RFwCfEAIC/xEAAAAAAABNFAY4GAAAAG8XGQC8FQ4SGgAAAJ8VAwKHExQVTRIToBsAAADAExwAEgAOABIACwASAAUAGBMAXB0AAACkEwEAAAAAQG8VBAC8ExMWAwAAAJ8TAwJvFREAvBMTXh4AAACfEwMCNRUAXB0AAAC8ExPHHwAAAJ8TAwGkEyEAAAAAQqQUAQAAAABAbxYEALwUFBYDAAAAnxQDAm8WEQC8FBQFIgAAAJ8UAwCfEwAEURMKAKQaJAAAADBCvBgXrSUAAACfGAMCDhgEADUYAFwdAAAAUhkXAJ8YAgFuE/X/AgAAgG8VJgC8Ew4WJwAAAJ8TAwLAFSgAEgAOABIABgC8ExPHHwAAAJ8TAwH/FQAAAAAAALwTBe8pAAAAnxMDAYIAAgAqAwMEAAAAQAMEAygDKQMqBAAAUEADKwMsAy0DLgMvAzADMQMyAzMDNAMHAzUDNgM3AzgDOQM6AzsDPAMIAz0GAgMcAz4DGwM/BAAAAEIDQAMdBAAAMEIDQQNCA0MGBQNEAgIFAQABGAAAAAMAAAAAAAEAAAAAAAQAAAAAAAAAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAEAAAADAAADAAAABAABAAAAAAABAAAAAQABAAAAAAAAAABNAAAAAAAlAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAEAAAAAAAEAAAD+AAgAAAAAAAAAAAALAAAAAAcBAAAAAAZ53xhVV1P+a9sa6W+axM0wCccPIUsbclQ=

-- Decompiler will be improved VERY SOON!
-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2025-12-11 01:07:08
-- Luau version 6, Types version 3
-- Time taken: 0.007068 seconds

local Load = require(game.ReplicatedStorage.Load)
local _ = Load("GuiHandler")
local var3_result1_upvr = Load("Network")
local Load_result1_upvr = Load("Constants")
local LocalPlayer_upvr = game:GetService("Players").LocalPlayer
local any_Get_result1_upvr = Load("Databases").Get("Loot")
function LootAdded(arg1) -- Line 108
	--[[ Upvalues[3]:
		[1]: LocalPlayer_upvr (readonly)
		[2]: any_Get_result1_upvr (readonly)
		[3]: var3_result1_upvr (readonly)
	]]
	local var10_upvw
	var10_upvw = arg1:WaitForChild("Border", 4).Touched:Connect(function(arg1_2) -- Line 111
		--[[ Upvalues[5]:
			[1]: LocalPlayer_upvr (copied, readonly)
			[2]: var10_upvw (read and write)
			[3]: arg1 (readonly)
			[4]: any_Get_result1_upvr (copied, readonly)
			[5]: var3_result1_upvr (copied, readonly)
		]]
		-- KONSTANTERROR: [0] 1. Error Block 1 start (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [0] 1. Error Block 1 end (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [1] 2. Error Block 2 start (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [1] 2. Error Block 2 end (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [4] 4. Error Block 3 start (CF ANALYSIS FAILED)
		local any_GetPlayerFromCharacter_result1 = game.Players:GetPlayerFromCharacter(arg1_2.Parent)
		-- KONSTANTERROR: [4] 4. Error Block 3 end (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [14] 10. Error Block 4 start (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [14] 10. Error Block 4 end (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [99] 73. Error Block 19 start (CF ANALYSIS FAILED)
		-- KONSTANTERROR: [99] 73. Error Block 19 end (CF ANALYSIS FAILED)
	end)
end
game:GetService("CollectionService"):GetInstanceAddedSignal("Loot"):Connect(LootAdded)
for _, v in ipairs(game:GetService("CollectionService"):GetTagged("Loot")) do
	if v:IsDescendantOf(workspace) then
		LootAdded(v)
	end
end
LocalPlayer_upvr:GetAttributeChangedSignal("TeamID"):Connect(function() -- Line 155
	--[[ Upvalues[2]:
		[1]: LocalPlayer_upvr (readonly)
		[2]: Load_result1_upvr (readonly)
	]]
	if LocalPlayer_upvr.Team.Name == Load_result1_upvr.TEAMS.Killer.name then
		pcall(function() -- Line 157
			workspace:FindFirstChild(workspace:GetAttribute("Map")).LootSpawns:Destroy()
		end)
		pcall(function() -- Line 160
			workspace:FindFirstChild(workspace:GetAttribute("Map")).FuseSpawns:Destroy()
		end)
	end
end)
var3_result1_upvr:BindEvents({})
return {}