-- Saved by UniversalSynSaveInstance (Join to Copy Games) https://discord.gg/wx4ThpAsmw

-- Bytecode (Base64):
-- BgP7AQRnYW1lClN0YXJ0ZXJHdWkOQ2hhdFdpbmRvd1NpemUHR2V0Q29yZQR0YXNrBHdhaXQKRGlzY29ubmVjdApSZW1vdmVJdGVtCkZpcmVTZXJ2ZXIHVmlzaWJsZQZJc0Rvd24JU2V0VG9nZ2xlCVBsYXlTb3VuZAlDYXJkUGxhY2UKU2V0RW5hYmxlZARMaXN0A25ldwRUeXBlBUNsb25lBENlbGwGUGFyZW50BU1vdmVyCUFjdGl2YXRlZAdDb25uZWN0EFVzZXJJbnB1dFNlcnZpY2UKR2V0U2VydmljZQxNb3VzZUVuYWJsZWQPS2V5Ym9hcmRFbmFibGVkCk1vdXNlRW50ZXIKTW91c2VMZWF2ZQdVSVNjYWxlBVNjYWxlCEl0ZW1JbmZvCFF1YW50aXR5BXRhYmxlBmluc2VydAdBZGRJdGVtBmlwYWlycwdEZXN0cm95C1JlZnJlc2hMaXN0ClJlbW92ZUljb24ORmluZEZpcnN0Q2hpbGQJWHNFbmFibGVkBXBhaXJzCkNsZWFyQm9hcmQIQ2hhdExvZ3MLR2V0Q2hpbGRyZW4JVGV4dExhYmVsA0lzQQROYW1lDE5ld0NoYXRFbnRyeQdDaGF0QmFyAARUZXh0CUNsZWFyQ2hhdAVwcmludAZHT1QgSVQGU3RhdHVzBEVudW0VVGV4dENoYXRNZXNzYWdlU3RhdHVzB1N1Y2Nlc3MHUGxheWVycwpUZXh0U291cmNlBlVzZXJJZBFHZXRQbGF5ZXJCeVVzZXJJZANMb2cLTGF5b3V0T3JkZXIKQCUqJSo6ICAlKhBIYXNWZXJpZmllZEJhZGdlA+6AgAZmb3JtYXQFQ09MT1IFV0hJVEUKVGV4dENvbG9yMwRDaGF0BUFsZXJ0BEJsaXARSW5jb21pbmdUcmFkZUNoYXQGUmlnaHRzDEdldEF0dHJpYnV0ZUVZb3UgYXJlIHRyYWRpbmcgd2l0aCBhIFBMQVlFUi4gVGhpcyB1c2VyIGlzIE5PVCBhIG1vZCwgYWRtaW4sIG9yIGRldi4MTElHSFRfWUVMTE9XC0NoYXRFZmZlY3RzA0Rldj5Zb3UgYXJlIHRyYWRpbmcgd2l0aCBhbiBvZmZpY2lhbCBTdXJ2aXZlIHRoZSBLaWxsZXIgZGV2ZWxvcGVyLgRCTFVFBUFkbWluOllvdSBhcmUgdHJhZGluZyB3aXRoIGFuIG9mZmljaWFsIFN1cnZpdmUgdGhlIEtpbGxlciBhZG1pbi4DUkVEA01vZDhZb3UgYXJlIHRyYWRpbmcgd2l0aCBhbiBvZmZpY2lhbCBTdXJ2aXZlIHRoZSBraWxsZXIgbW9kLgpMSU1FX0dSRUVOIuKaoO+4jyA8Zm9udCBjb2xvcj0iIyUqIj4lKjwvZm9udD4FVG9IZXgNU2VuZENoYXRJbnRybwxUZXh0Q2hhbm5lbHMMVHJhZGVDaGFubmVsCVNlbmRBc3luYwZzdHJpbmcDbGVuBFNlbmQER1JFWRBCYWNrZ3JvdW5kQ29sb3IzBXNwYXduAiUqBkNvbG9yMwdmcm9tUkdCBFNFTkQNU2VuZFRyYWRlQ2hhdAZTZWxlY3QIRGVzZWxlY3QFR3JpZDEJUmVhZHlJY29uE0dyZWVuT3V0bGluZUVuYWJsZWQKRG9DbGVhbmluZxNOVU1fVklQX1RSQURFX1NMT1RTEFVubG9ja1RyYWRpbmdWSVAKR2FtZXBhc3NlcwpUcmFkaW5nVklQDEFic29sdXRlU2l6ZQFYD05VTV9UUkFERV9TTE9UUxlHZXRBdHRyaWJ1dGVDaGFuZ2VkU2lnbmFsGlRoaXNQbGF5ZXJHYW1lcGFzc0xpc3RlbmVyG090aGVyUGxheWVyR2FtZXBhc3NMaXN0ZW5lcgtUcmFkaW5nV2l0aAxTZXRBdHRyaWJ1dGUFVGl0bGURVHJhZGluZyB3aXRoICUqJSoPQ29udGVudFByb3ZpZGVyF3JieGFzc2V0aWQ6Ly8xNTk4NjMwNTc3B1ByZWxvYWQWVHJhZGluZyBjaGF0IHdpdGggQCUqLh1UeXBlIGhlcmUgdG8gY2hhdCB3aXRoIEAlKi4uLg9QbGFjZWhvbGRlclRleHQMU3RhcnRUcmFkaW5nCFJvdGF0aW9uAm9zBHRpbWUIdG9zdHJpbmcOVHJhZGVHZW5lcmF0b3IKUnVuU2VydmljZQ1SZW5kZXJTdGVwcGVkCUhlYXJ0YmVhdA5TdGFydENvdW50ZG93bglTdG9wU291bmQPQ2FuY2VsQ291bnRkb3duCENhcmRMaWZ0B1JlYWR5VXAEbWF0aANhYnMNVHJhZGVDb21wbGV0ZRhUcmFkZVJlcXVlc3RPcHRpb25DaG9zZW4IT25JbnZva2UPVHJhZGluZ0Rpc2FibGVkDnRyYWRlX3JlcXVlc3RzBlRlYW1JRAVMb2JieQhJbnN0YW5jZRBCaW5kYWJsZUZ1bmN0aW9uEFNlbmROb3RpZmljYXRpb24ESWNvbghDYWxsYmFjawdCdXR0b24xB0J1dHRvbjIFVHJhZGUPIHdhbnRzIHRvIHRyYWRlF3JieGFzc2V0aWQ6Ly82NTU5Mjk1NDg4BkFjY2VwdAdEZWNsaW5lB1NldENvcmUSUHJvbXB0VHJhZGVSZXF1ZXN0BWRlbGF5EVRyYWRlU2Vzc2lvbkVuZGVkC0ltYWdlQ29sb3IzF3JieGFzc2V0aWQ6Ly82NTU5Mjk1MjQzBUltYWdlBkNhbmNlbAtSZXZlcnRTdGF0ZQ1DYW5jZWxSZWFkeVVwC0xvY2FsUGxheWVyCkdhbWVwYXNzSWQWUHJvbXB0R2FtZVBhc3NQdXJjaGFzZQ1DdXJyZW50UGxheWVyDFNldEludmVudG9yeQtPcGVuU3VibWVudQlJbnZlbnRvcnkGS25pdmVzBE1vZGUNSW52ZW50b3J5TW9kZQdUcmFkaW5nD0VuZFRyYWRlU2Vzc2lvbglDbG9zZU1lbnUHRGVmYXVsdBZUcmFkZVNlbGVjdGlvbkJpbmRhYmxlEk1hcmtldHBsYWNlU2VydmljZRFSZXBsaWNhdGVkU3RvcmFnZQtUZXh0U2VydmljZQ9UZXh0Q2hhdFNlcnZpY2UHcmVxdWlyZQRMb2FkBE1haWQKR3VpSGFuZGxlcgtNZW51SGFuZGxlcg1JbnZlbnRvcnlDZWxsDUJ1dHRvbkhhbmRsZXIJQ29uc3RhbnRzBUVudW1zB1NvdW5kRlgJRGF0YWJhc2VzA0dldANBbGwIU2V0dGluZ3MMV2FpdEZvckNoaWxkB1V0aWxpdHkHTmV0d29yawlQbGF5ZXJHdWkMR2V0U2NyZWVuR3VpB1RyYWRlVUkIR2V0RnJhbWUJSW50ZXJmYWNlB0J1dHRvbnMKQ2hhdFdpbmRvdxBPdGhlclBsYXllck9mZmVyD090aGVyUGxheWVyR3JpZAlZb3VyT2ZmZXIIWW91ckdyaWQOVHJhZGluZ1ZJUExvY2sIQWRkRnJhbWUDQWRkDEdyaWRUZW1wbGF0ZQZSZW1vdmUJQ291bnRkb3duDUNvdW50ZG93blRleHQPTWVzc2FnZVJlY2VpdmVkCUZvY3VzTG9zdBhHZXRQcm9wZXJ0eUNoYW5nZWRTaWduYWwOVHJhZGluZ1N0YXJ0ZWQJSXRlbUFkZGVkDE9mZmVyQ2hhbmdlZAhTZXRSZWFkeQxGaW5hbFJlZnJlc2gQQ291bnRkb3duU3RhcnRlZBFDb3VudGRvd25DYW5jZWxlZApCaW5kRXZlbnRzCldyYXBUb2dnbGUJU2F2ZVN0YXRlCkxlZ2FjeVdyYXAGVW5sb2NrBUNsb3NlBkxpc3RlbgAxAwABAAAAF6QBAQAAAABATQABCwIAAABvAgMAvAAAiwQAAACfAAMCKwAEAKQABwAAGFCAnwABAUgA8/+kAQEAAAAAQE0AAQsCAAAAbwIDALwAAIsEAAAAnwADAt4AAACCAAEACAMBBAAAAEADAgMDAwQDBQMGBAAYUIAAbgABGAAAAAAAAAAAAAEAAP8DAAAAAAAAAAABbwAAAAAFAAQAAAAM+wAAALwAABoAAAAAnwACAfsAAQBvAgEA+wMCAPsEAwC8AABrAgAAAJ8ABQGCAAEAAwMHAwgDCQCgAQABGAAAAAABAAAAAAAAAaEAAAAAAgABAAAABfsAAACpAQEAMAEAgAAAAACCAAEAAQMKAKYBAAEYAAAAAAGnAAAAAAIAAQAAAAX7AAAAqQEAADABAIAAAAAAggABAAEDCgCpAQABGAAAAAABqgAAAAANAw8AAAC8AfsEAACHAwQAKwMEAPsDAAD/BAAAAAAAAGoEAwArAjoA+wMBALwDA0sAAAAAnwMCAg4DBgD7AwEAqQUAAKkGAQC8AwMxAQAAAJ8DBAH7BAIATQME9wIAAABvBAMAnwMCAfsFAwD7BgQAhwQFBhwDBAANAw0ABAAAgPsFAwD7BgUAhwQFBhwDBAANAwcABAAAgPsDAQCpBQAAvAMDngUAAACfAwMBZQAFAPsDAQCpBQEAvAMDngUAAACfAwMB+wMFAJoAEQADAAAA+wMGAPsHAwCHBgcAHAUGAPsGBwC3BQIABgAAAKkEAAGpBAEAMAQDgAYAAAD7AwgAqQUBALwDA54FAAAAnwMDAfsEBQCaAAUABAAAAPsECQBNAwTrBwAAACsDAwD7BAoATQME6wcAAAD7BQsAhwQFAfsGDABNBQbvCAAAAE0GBBEJAAAAUgcBAIwIAQCpCQEAnwUFAsYGAAD7BwUAmgBEAAcAAAD7Bw0AvAcHOgoAAACfBwICTQgF7QsAAAAwCAckDAAAAPsICAC8CAhLAAAAAJ8IAgIwCAeABgAAAPsLAACHCgsAHAkKAJUICQ1NCgdVDgAAAE0JCh4PAAAA2QsAABIBBv8SAg4AEgABABIACAC8CQnHEAAAAJ8JAwJSBgkApAoSAAAAEEFvDBMAvAoKFhQAAACfCgMCTQkKUBUAAAAOCRsApAoSAAAAEEFvDBMAvAoKFhQAAACfCgMCTQkKLRYAAAAOCRIATQoF7QsAAABNCQoUFwAAANkLAQASAAcAvAkJxxAAAACfCQMBTQoF7QsAAABNCQrdGAAAANkLAgASAAcAvAkJxxAAAACfCQMBTQgF7QsAAABNBwgrGQAAAIwIAQAwCAeEGgAAAE0JBe0LAAAATQgJHhsAAABNBwhZHAAAAKkIAAAwCAeABgAAAE0HBe0LAAAAMAMHJAwAAAD7CQAAhwgJAJ40CAQFAAAAUgkFAKQHHwAAeNCBnwcDAcEGAACCAAEAIAMLAwwDDQMOAgAAAAAAAAAAAw8DCgMQAxEDEgMTAxQDFQIAAAAAAADwPwMWAxcDGAMBBAAAEEEDGQMaAxsDHAMdAx4DHwMgAyEDIgMjAyQEAHjQgQMBAgN3JQEYAAAAAQAAAAMBAAAAAAEAAAAAAAMAAAAAAwAAAAAAAAAAAAAAAQAAAAAAAgAAAAADAAABAAAAAAAAAAAAAAEAAAAABQAAAAAAAAAAAAEAAQAAAAAAAAAAAQIAAAIAAAABAAAAAgAAAAAAAgAAAAIAAAAAAAAAAAAAAAAFAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAADAAAAAAAAAAAFAAAAAAAAAQAAAAAAAAAAAQAAAAIAAAAAAAAAAgB5AAAAAAwCCAAAAGv7AwAAhwIDAPsEAQCHAwQAKwMEAPsDAQD/BAAAAAAAAGoEAwArASIA+wMCALwDA0sAAAAAnwMCAg4DBgD7AwIAqQUAAKkGAQC8AwMxAQAAAJ8DBAH7BQAA+wYDAIcEBQYcAwQADQMNAAIAAID7BQAA+wYEAIcEBQYcAwQADQMHAAIAAID7AwIAqQUAALwDA54DAAAAnwMDAWUABQD7AwIAqQUBALwDA54DAAAAnwMDAfsDBACaABoAAwAAAPsDBQAcBgIADQYCAAIAAICpBQABqQUBALwDA54DAAAAnwMDAfsDAgC8AwNLAAAAAJ8DAgIrAwsA+wMGAPsHAACHBgcAHAUGAPsGBwC3BQIABgAAAKkEAAGpBAEAMAQDgAQAAACkAwYAAABQQPsGAQCHBAYAnwMCBFEDAwC8CAdQBwAAAJ8IAgFuA/z/AgAAgPsDAQD/BAAAAAAAAGoEAwCkAwYAAABQQFIEAgCfAwIEUQMGADUIAHgIAAAAUgkAAFIKBwCpCwEAnwgEAW4D+f8CAACA+wQGAE0DBCsJAAAAjAQBADAEA4QKAAAAggABAAsDCwMMAgAAAAAAAAAAAw8DCgMmBAAAUEADJwMlAx8DIAC2ASgBGAAAAgAAAQAAAAMDAAAAAAEAAAAAAAQAAAAAAAAAAAAAAAEAAAAAAAIAAAAABAAAAQAAAAAAAAAAAQAAAAABAAAAAAAAAAAAAAUAAAAAAAEAAP8ABAAAAAIAAAAAAQAAAAAA/wAEAAAAAAACtwAAAAAJAQIAAAAXpAEBAAAAAED7BAAA+wUBAIcCBAWfAQIEUQENAE0GBe0CAAAAbwgDALwGBgMEAAAAnwYDAg4GBgBNBwXtAgAAAE0GB6wDAAAAMAAGgAUAAABuAfL/AgAAgIIAAQAGAyYEAAAAQAMUAykDKgMKAOMBKwEYAAAAAAAAAAEAAAAAAAABAAAAAAD+AAXkAAAAAAwAAQAAABWkAAEAAAAAQPsBAACfAAIEFwAKAKQFAwAAACBAUgYEAJ8FAgRRBQMAvAoJUAQAAACfCgIBbgX8/wIAAIBuAPX/AgAAAP8AAAAAAAAA3gAAAIIAAQAFAywEAAAAQAMmBAAAIEADJwDrAS0BGAAAAAAAAQAAAAABAAD/AP8ABgAAAewAAAAACAABAAAAHPsBAABNAAF2AAAAALwAAGgBAAAAnwACBGQADABvBwIAvAUE/gMAAACfBQMCDgUHAE0FBLoEAAAA8AUEAAUAAAC8BQRQBgAAAJ8FAgFuAPP/AgAAAPsBAABNAAEuBwAAAG8BCAAwAQD1CQAAAIIAAQAKAy4DLwMwAzEDMgMzAycDNAM1AzYA9QE3ARgAAAAAAAAAAQAAAAAAAAAAAQAA/gAFAAAAAAAB9gAAAAAKAQQAAABTpAEBAAAAAEBvAgIAnwECAU0BAOwDAAAApAIHAAYUQMDxAQIAAgAAAIIAAQD7AwAATQIDdggAAABNAQLyCQAAALwBAToKAAAAnwECAqQDDAAAALBATQIDUA0AAABNBQBUDgAAAE0EBeYPAAAAvAICYRAAAACfAgMCTQMA9REAAABvBBIAMAQBuhMAAACMBAAAMAQBABQAAABvBRUATQcCuhMAAABNCQIGFgAAAA4JAgBvCBcAZQABAG8IGABSCQMAvAUFjRkAAACfBQUCUgQFADAEAfURAAAA+wYBAE0FBu0aAAAATQQFOBsAAAAwBAFzHAAAAPsFAABNBAV2CAAAADAEASQdAAAA+wYCAE0FBsceAAAATQQFHh8AAAD7BwAATQYHgCAAAABWBQYAMAUEgCAAAAD7BQMATQQF9yEAAABvBSIAnwQCAYIAAQAjAzgEAAAAQAM5AzoDOwM8Az0EBhRAwAMuAzMDEwMBBAAAsEADPgM/A0ADQQM2A0IDMgNDA0QDRQNGAzUDRwNIA0kDSgMVA0sDTAMKAw0DTQD+AU4BGAAAAAABAAAAAAABAgAAAAAAAAABAAAAAAAAAAAAAAEAAQAAAQAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAABAAAAAAIAAAAAAAAAAAAAAQAAAAAB/wAAAAAKAQMAAABXbwMAALwBABIBAAAAnwEDAm8CAgD7BQAATQQF7QMAAABNAwQuBAAAAG8GBQC8BAASAQAAAJ8EAwIOBCkA+wYBAE0FBioAAAAATQQF8AYAAAB9BAgAAQAAAG8CBwD7BQAATQQF7QMAAABNAwRmCAAAAGUAGwD7BgEATQUGKgAAAABNBAUaCQAAAH0ECAABAAAAbwIKAPsFAABNBAXtAwAAAE0DBAULAAAAZQANAPsGAQBNBQYqAAAAAE0EBTkMAAAAfQQHAAEAAABvAg0A+wUAAE0EBe0DAAAATQMEPA4AAAD7BgIATQUGdg8AAABNBAXyEAAAALwEBDoRAAAAnwQCAm8FEgAwBQS6EwAAAIwF/v8wBQQAFAAAAG8GFQC8CAMfFgAAAJ8IAgJSCQIAvAYGjRcAAACfBgQCUgUGADAFBPUYAAAA+wYCAE0FBnYPAAAAMAUEJBkAAACCAAEAGgNPA1ADUQNIA1IDUwNUA1UDVgNXA1gDWQNaA1sDXAMuAzMDEwNCAzIDQwNdA14DRwM2AxUAkwJfARgAAAAAAQEAAAAAAgAAAAABAAAAAAAAAQEAAAAAAAEAAAAAAAABAQAAAAAAAQAAAAAAAAEBAAAAAAQAAAAAAAAAAQAAAQAAAQAAAAAAAAAAAAABAAAAAAEVAQAAAAUAAgAAAA77AgAATQEChwAAAABNAAF0AQAAAPsEAQBNAwQuAgAAAE0CA/UDAAAAvAAAYwQAAACfAAMBggABAAUDYANhAzQDNgNiALQCAAEYAAAAAAAAAAAAAAAAAAE1AQAAAAgABAAAAFb7AAAAKwATAPsCAQBNAQIuAAAAAE0AAfUBAAAA8AANAAIAAAD7AwEATQIDLgAAAABNAQL1AQAAALsrAQKkAAUAABAwgJ8AAgKMAWQAYAECAAAAAACCAAEAqQABAN4AAAD7AQEATQAB5AYAAAD7AwIATQID7QcAAABNAQI5CAAAADABAJ8JAAAApAAMAAAsoIDAAQ0AEgIDABICAQCfAAIB+wEBAE0AAS4AAAAAbwECADABAPUBAAAAjAIDAIwAAQCMAf//qAAQAPsEAQBNAwTkBgAAAG8FDgBSBwIAvAUFjQ8AAACfBQMCUgQFADAEA/UBAAAApAMRAABAoICMBAEAnwMCAYsA8P/7AQEATQAB5AYAAACkARQAAEwggYwCAACMA3gAjAT/AJ8BBAIwAQCfCQAAAPsBAQBNAAHkBgAAAG8BFQAwAQD1AQAAAKkAAADeAAAAggABABYDNAM2AzUDYwNkBAAQMIADZQNIA2YDZwMFA2gEACyggAYLA2kDRwMGBABAoIADagNrBABMIIEDbAELrQJtARgAAAAAAAAAAAAAAAAAAAAAAAAAAAABAwABAAAAAAAAAAAAAQAAAAAAAwAAAAAAAgAAAAEAAAAAAAAAAAAAAQAAAP4FAAAAAAAAAAAAAAEAAAAAAAEAAS4BAAAAAgEAAAAABQ4AAwA1AQAbAAAAAJ8BAQGCAAEAAQNtAMQCAAEYAAEAAAJFAQAAAAYAAgAAAB37AQAATQABLgAAAAD7BQAATQQFLgAAAABNAwT1AQAAALsrAwKkAgQAAAwggJ8CAgKMA2QAYAMHAAIAAAD7AwEATQID7QUAAABNAQIFBgAAAGUABQD7AwEATQID7QUAAABNAQI4BwAAADABAHMIAAAAggABAAkDNAM2A2MDZAQADCCAA0gDWQNJA0oAygIAARgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUsBAAAACQIEAAAAIaQCAQAAAABA+wUAAIcDBQCfAgIEUQIIAA4BBAC8BwaUAgAAAJ8HAgFlAAMAvAcG0wMAAACfBwIBbgL3/wIAAID7AwEAmgAFAAMAAAD7AwIATQID6wQAAAArAgMA+wMDAE0CA+sEAAAATQQCpwUAAABNAwQDBgAAADABA4AHAAAAggABAAgDJgQAAABAA24DbwMQA3ADcQMKAM4CcgEYAAAAAAAAAQEAAAACAAD8AAcAAAAAAAAAAAABAAAAAAABTwEAAAAGAAcAAAAZ+wAAALwAAFEAAAAAnwACAfsAAQCpAQAAMAEAgAEAAAD7AQMATQAB9AIAAADeAAIA+wAEAPsEBQD7BQYAhwMEBRwCAwD7AwIAtwICAAMAAACpAQABqQEBADABAIABAAAAggABAAMDcwMKA3QA2gJ1ARgAAAAAAQAAAAEAAAABAAAAAAAAAAAAAAABWwEAAAADAAEAAAAM+wEAAE0AATwAAAAAbwIBALwAABICAAAAnwADAg4AAwA1AACZAwAAAJ8AAQGCAAEABAN2A3cDUAN1AOkCAAEYAAAAAAAAAAABAAACagEAAAADAAEAAAAM+wEAAE0AATwAAAAAbwIBALwAABICAAAAnwADAg4AAwA1AACZAwAAAJ8AAQGCAAEABAN2A3cDUAN1AO4CAAEYAAAAAAAAAAABAAACbwEAAAAFAAEAAAAhpAACAAAEAICfAAEB+wIAAE0BAnEDAAAATQABeQQAAAD7BAAATQMEJAUAAABNAgNxAwAAAE0BAnkEAAAAfQEQAAAAAAD7AQAATQABKwYAAAD7BAAATQMEKwYAAABNAgOECAAAAHgBAgcwAQCECAAAAKQAAgAABACAnwABAUgA4/+CAAEACQMFAwYEAAQAgAN4A3kDFQMfArgehetRuJ4/AyAAnQMAARgAAAABAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAQAA/gSeAQAAAAkBDQAAALsB+wIAAE0BAjwAAAAAbwMBALwBARICAAAAnwEDAisBBgBNAQA8AAAAAG8DAQC8AQESAgAAAJ8BAwIOAQQA+wMCAE0CA/QDAAAAKwIDAPsDAgBNAgOgBAAAAN4CAQD7AgMAVgMBADADAoAFAAAAKwEdAPsCBAD7BAAATQMEPAAAAABvBQEAvAMDFgYAAACfAwMCwAUHABICAAC8AwPHCAAAAJ8DAwIwAwKZCQAAAPsCBABNAwA8AAAAAG8FAQC8AwMWBgAAAJ8DAwLZBQEAEgAAALwDA8cIAAAAnwMDAjADAlwKAAAA+wIFAG8ECwBNBQC6DAAAALwCAi4NAAAAnwIEAfsEBQBNAwS6DgAAAE0CA5oPAAAAbwQQAE0GALoMAAAATQgABhEAAAAOCAIAbwcSAGUAAQBvBxMAvAQEjRQAAACfBAQCUgMEADADAvUVAAAA3gAGAPsCBQCpAwEAMAMCgAUAAACkAhcAAABgQW8EGAC8AgIWGQAAAJ8CAwJvBBoAvAICSBsAAACfAgMBNQIALxwAAACfAgEBNQIA+R0AAACfAgEB+wQHAE0DBHYeAAAATQID8h8AAABvBCAATQYAugwAAAC8BASNFAAAAJ8EAwJSAwQAMAMC9RUAAAD7AwcATQIDLiEAAABvBCIATQYAugwAAAC8BASNFAAAAJ8EAwJSAwQAMAMCrSMAAAA1AgAQJAAAAFIDAACfAgIB/wICAAAAAAD/AwAAAAAAAGoDAgD7AwAA/wQAAAAAAABqBAID3gIIADUCAGglAAAA+wMAAJ8CAgE1AgBoJQAAAFIDAACfAgIB+wIJAKkEAAC8AgIxJgAAAJ8CAwH7AgoAqQQAALwCAp4nAAAAnwIDAfsCCQCpBAAAvAICnicAAACfAgMB+wILAKkEAAC8AgIxJgAAAJ8CAwH7AgcAqQMAADADAoAFAAAA+wIMAKkDAQAwAwKABQAAAKQCKgAApICCwAMrABICBQCfAgIBggABACwDdgN3A1ADdAN6AwoDewYRAxgDfAN9A34DMgN/A4ABAzADgQEDRQNGAzUDRwM2AwEEAABgQQOCAQMaA4MBA4QBAy0DNwMuAzMDhQEDNAOGAQOHAQNfAygDDAMPAwUDaAQApICCBhMDERIT4QKIAQEYAAAAAAAAAAAAAAAAAAACAAAAAAAAAAABAAAAAgEAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAABwAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAABAIAAAAEAAAAAAAAAAAAAgAAAQAAAgAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAABAAAAAgABAAABAAAA/gYAAAABAAAAAgAAAAABAAAAAAEAAAAAAQAAAAACAAAAAgAAAAMAAAAACWMBAAAABgEDAAAAFVsBAADeAQAA+wEBAIwCKABgAQYAAgAAAPsCAQD7BAAAWwMEAUMBAgPeAQEA+wECAPsEAgBNAwQ4AgAAAPsFAQAhBAUDQwIDBDACATgCAAAAggABAAQCAAAAAAAATkACmpmZmZmZuT8DiQECAAAAAACAdkAAtAMAARgAAAEAAAABAAAAAAIAAAAAAAAAAAG1AQAAAAUAAwAAAB/7AAAApAECAAAEAICfAQEC8QAZAAEAAACkAAIAAAQAgJ8AAQLeAAAA+wABAPsDAgCkBAIAAAQAgJ8EAQImAgMEuz8CAqQBBAAAADBAnwECAjABAPUFAAAA+wAAAPsBAgCaAAUAAQAAAPsAAQCpAQAAMAEAgAYAAACCAAEABwOKAQOLAQQABACAA4wBBAAAMEADNgMKAL4DAAEYAAAAAAAAAQAAAAEAAAAAAAAAAAAAAAEAAAABAAAAA78BAAAACAEGAAAAOMYBAAD7AgAAqQMBADADAoAAAAAA+wIBAKkDAQAwAwKAAAAAAIwCAACMAwAA+wUCAE0EBfcBAAAAbwUCAJ8EAgGkBQQAAAAwQG8HBQC8BQUWBgAAAJ8FAwJNBAXPBwAAANkGAAASAQP/EgEC/xICBAC8BATHCAAAAJ8EAwLeBAMA+wQFAA4EBAD7BAUAvAQEGgkAAACfBAIBpAUEAAAAMEBvBwUAvAUFFgYAAACfBQMCTQQF/QoAAADZBgEAEgEB/xICAQASAAAAvAQExwgAAACfBAMC3gQFAMEBAACCAAEACwMKAw0DjQEDAQQAADBAA44BAxoDjwEDGAMHA5ABAhUWqgORAQEYAAEAAAABAAAAAgECAAAAAAIAAAAAAAAAAAAAAAAAAAAHAAEAAAACAAAAAAAAAAAAAAAAAAAACQCrAQAAAAUBBQAAAB4OAAcA+wEAAKkDAACpBAEAvAEBMQAAAACfAQQBZQAFAPsCAQBNAQKfAQAAAG8CAgCfAQIB+wECAA4BBAD7AQIAvAEBGgMAAACfAQIB+wEDAA4BBAD7AQMAvAEBGgMAAACfAQIB+wEEAKkCAAAwAgGABAAAAIIAAQAFAwwDkgEDjQEDBwMKAMkDkwEBGAABAAAAAAAAAgAAAAADAAEAAAADAAEAAAAEAAAAAcoBAAAAAwEAAAAABTUBAKsAAAAAUgIAAJ8BAgGCAAEAAQOIAQDhAwABGAAAAAAB4gEAAAAFAgEAAAAO+wQAAIcDBACeNAMEAQAAAFIEAQCkAgIAAAQAgJ8CAwE1AgB4AwAAAFIDAABSBAEAnwIDAYIAAQAEAyMDJAQABACAAyUA5wMAARgAAAAAAAAAAAEAAAAAAegBAAAABgICAAAAEhwCAQD7BQAAhwQFABwDBABgAgYAAwAAAPsDAQBNAgP3AAAAAG8DAQCfAgIB+wIAAGoBAgA1AgBoAgAAAFIDAACfAgIBggABAAMDDQOUAQMoAO4DAAEYAAAAAAAAAQAAAAACAAEAAAAB7wEAAAAFAgEAAAAMDgEFAPsDAABNAgP3AAAAAG8DAQCfAgIBNQIAzAIAAABSAwAAUgQBAJ8CAwGCAAEAAwMNA5UBA3IA+AMAARgAAQAAAAACAAAAAAH5AQAAAAUCAQAAAA37AgAAagECADUCAGgAAAAAUgMAAKkEAQCfAgMBNQIAzAEAAABSAwAAqQQBAJ8CAwGCAAEAAgMoA3IAgAQAARgAAAEAAAAAAQAAAAABAQIAAAAEAQAAAAAUpAMCAAAEAICfAwECJgIDALsCAgKkAQUAABAwgJ8BAgKMAgUAYAIFAAEAAACkAQIAAAQAgJ8BAQKVAAEGNQEA0wcAAABSAgAAnwECAYIAAQAIA4oBA4sBBAAEAIADlgEDlwEEABAwgAIAAAAAAAAQQAORAQCHBAABGAAAAAAAAAAAAAAAAQAAAAIAAAABCQIAAAABAAAAAAAENQAAVgAAAACfAAEBggABAAEDkwEAkQQAARgAAAABEgIAAAAEAAMAAAAdpAACAAAEAICMAQUAnwACATUAAFYDAAAAqQEBAJ8AAgH7AgAA+wMBAIcBAgMcAAEADQAHAAQAAAD7AQIATQABnwUAAABvAQYAnwACAWUABQD7AQIATQABnwUAAABvAQYAnwACATUAAC8HAAAAnwABAYIAAQAIAwUDBgQABACAA5MBAgAAAAAAAAAAA5IBA40BAy0AlgSYAQEYAAAAAAEAAAACAAAAAAADAAAAAAACAAAAAAMAAAIYAgAAAAYBAwAAAA77AQAAbwMAAFIEAAD7BQEAvAEBawEAAACfAQUB+wECAA4BBAD7AQIAvAEBUAIAAACfAQIBggABAAMDmQEDCQMnALEEmgEBGAAAAAAAAAABAAEAAAACMgIAAAAJAQQAAABD+wIAAE0BAqIAAAAADgEBAIIAAQD7AQEAbwMBALwBARICAAAAnwEDAisBAQCCAAEA+wECAG8DAwC8AQESAgAAAJ8BAwLwAQIABAAAAIIAAQBvAwMAvAEAEgIAAACfAQMC8AECAAQAAACCAAEApAEHAAAYUIBvAggAnwECAtkCAAASAgMAEgAAABIAAQAwAgH8CQAAAKQDCwAAAKBATQIDCwwAAABvBA0A4gUUAG8GFQAwBgW6DgAAAE0HALoWAAAAbwgXAHMGBwgwBgX1DwAAAG8GGAAwBgWuEAAAADABBUYRAAAAbwYZADAGBVMSAAAAbwYaADAGBVATAAAAvAICvxsAAACfAgQBggABABwDmwEDnAEDUAOdAQOeAQOfAQMRBAAYUIADoAEDmgEDAQQAAKBAAwIDoQEDgAEDNgOiAQOjAQOkAQOlAQUGDg8QERITA6YBAzIDpwEDqAEDqQEDqgEDqwEBIacErAEBGAAAAAAAAgAAAAAAAAIAAAAAAAAAAQAAAAAAAAIAAAABAAAAAAAHAAAAAAABAAABAAAAAAABAAABAAEAAAEAAPoAAAkpAgAAAAQABAAAACn7AAAAvAAAUQAAAACfAAIB+wABAG8CAQBvAwIAvAAALgMAAACfAAQB+wABAKkBAAAwAQCABAAAAPsDAgBNAgPrBQAAAE0BAqcGAAAATQABAwcAAACpAQAAMAEAgAQAAAD7AwMATQID6wUAAABNAQKnBgAAAE0AAQMHAAAAqQEAADABAIAEAAAApAAKAAAkgICMAQEANQIAVgsAAACfAAMBggABAAwDcwN+AzUDfwMKAxADcANxAwUDrQEEACSAgAOTAQDDBK4BARgAAAAAAQAAAAAAAQAAAAUAAAAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAUQCAAAAAgABAAAABfsAAACpAQEAMAEAogAAAACCAAEAAQObAQDRBJsBARgAAAAAAVICAAAABQABAAAAEDUAABMAAAAAqQEBAJ8AAgH7AQAATQABVQEAAACkAQQAAAwggIwCuQCMAzkAjAQ5AJ8BBAIwAQAABQAAAIIAAQAGAysDFgNqA2sEAAwggAOvAQDYBAABGAAAAAABAAAAAAAAAAAAAAFZAgAAAAIAAgAAAAs1AAATAAAAAKkBAACfAAIB+wEAAE0AAVUBAAAA+wEBADABAAACAAAAggABAAMDKwMWA68BANwEAAEYAAAAAAEAAAAAAAFdAgAAAAUABwAAAE/7AQAATQAB9wAAAABvAQEAnwACAakAAQDeAAEA+wACAKkCAACpAwEAvAAAMQIAAACfAAQB+wACAKkCAAC8AACeAwAAAJ8AAwH7AAMAqQEAADABAIAEAAAANQAAzAUAAAD7AQQAqQIBAJ8AAwH7AQUATQABVQYAAACkAQkAACBwgIwCwQCMAzwAjAQ8AJ8BBAIwAQAACgAAAPsABQCkAQkAACBwgIwCigCMAyMAjAQjAJ8BBAIwAQAACgAAAPsCBQBNAQJVBgAAAE0AAa4LAAAAbwEMADABAKkNAAAA+wMFAE0CA1UGAAAATQECrgsAAABNAAGuCwAAAG8BDAAwAQCpDQAAAPsCBQBNAQJVBgAAAE0AAZoOAAAAbwEPADABAPUQAAAA+wAGAG8CAQC8AABrEQAAAJ8AAwGCAAEAEgMNA5UBAwwDDwMKA3IDFgNqA2sEACBwgAOvAQOiAQOwAQOxAQMwA7IBAzYDCQDmBAABGAAAAAAAAQABAAAAAAABAAAAAAIAAAABAAAAAAEAAAAAAAAAAAAAAQAAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAAAAQAAAAAAAAABAAAAAAFnAgAAAAcACQAAACqpAAAA3gAAAPsAAQD7BQIA+wYDAIcEBQYcAwQADQMCAAAAAICpAgABqQIBALwAAJ4BAAAAnwADAfsABAD7BAIA+wUDAIcDBAUcAgMA+wMFALcCAgADAAAAqQEAAakBAQAwAQCAAgAAADUAAMwDAAAA+wEDAKkCAACfAAMB+wAGAPsCBwC8AABNBAAAAJ8AAwH7AAgAbwIFALwAAGsGAAAAnwADAYIAAQAHAgAAAAAAAAAAAw8DCgNyA7MBA7QBAwkA9QQAARgAAAEAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAEAAAAAAQAAAAABAAAAAAF2AgAAAAIAAgAAAAv7AAAAqQEBADABAIAAAAAA+wEBAE0AAR4BAAAAqQEAADABAIAAAAAAggABAAIDCgNMAIEFAAEYAAAAAAEAAAAAAAGCAgAAAAIAAQAAAAX7AAAAqQEAADABAIAAAAAAggABAAEDCgCFBQABGAAAAAABhgIAAAAGAAIAAAAQ+wAAAKQEAQAAAABATQMEUAIAAABNAgMxAwAAAPsFAQBNBAU8BAAAAE0DBOoFAAAAvAAA4wYAAACfAAQBggABAAcDAQQAAABAAz4DtQEDdwO2AQO3AQCMBQABGAAAAAAAAAAAAAAAAAAAAAGNAgAAAAUABAAAABX7AAAAbwIAAPsEAQBNAwS6AQAAALwAAC4CAAAAnwAEAfsAAgBvAgMA+wMBALwAAGsEAAAAnwAEAfsBAwBNAAFuBQAAAG8BBgBvAgcAnwADAYIAAQAIA7gBAzIDfwO5AQMJA7oBA7sBA7wBAJIFAAEYAAAAAAAAAAABAAAAAAABAAAAAAAClAIAAAAGAAQAAAAX+wAAAG8CAAD7BQEATQQF6gEAAABNAwTXAgAAALwAAC4DAAAAnwAEAfsBAgBNAAFuBAAAAG8BBQBvAgYAnwADAfsAAwCpAgAAqQMBALwAADEHAAAAnwAEAYIAAQAIA70BA74BA78BA38DugEDuwEDvAEDDACbBQABGAAAAAAAAAAAAAABAAAAAAACAAAAAAADnQIAAAADAAQAAAAY+wEAAE0AAYAAAAAADgAKAPsAAACpAQAAMAEAgAAAAAD7AAEAqQIAALwAADEBAAAAnwADAYIAAQD7AAIAqQEAADABAIAAAAAA+wADAG8CAgC8AABrAwAAAJ8AAwGCAAEABAMKAwwDwAEDCQCmBQABGAAAAAABAAAAAQAAAAABAwAAAAEAAAAAAacCAAAABwEIAAAALSsAAQCCAAEA+wIAAG8EAAC8AgISAQAAAJ8CAwJWAQIA+wQBAE0DBOoCAAAATQID1wMAAACaAQIAAgAAAIIAAQD7AwIA+wQDAIcCAwQcAQIA+wIEAJoBAgACAAAAggABAPsBBQBvAwQAUgQAALwBAWsFAAAAnwEEAfsCBgBNAQIvBgAAAJ8BAQH7AQcAbwMAAPsGAQBNBQbqAgAAAE0EBToHAAAAvAEBLggAAACfAQQBggABAAkDvQEDUAO+AQO/AQMlAwkDwQEDwgEDfwCzBcMBARgAAAEAAAAAAAAAAAAAAAAAAQAAAAAAAAACAAAAAAACAAAAAQAAAAAAAAAAAAK0AgAAAEUAAAECAM4EowAAAP8AAQAAAAAApAEBAAAAAEBvAwIAvAEBFgMAAACfAQMCpAIBAAAAAEBvBAQAvAICFgMAAACfAgMCpAMBAAAAAEBvBQUAvAMDFgMAAACfAwMCpAQBAAAAAEBvBgYAvAQEFgMAAACfBAMCpAUBAAAAAEBvBwcAvAUFFgMAAACfBQMCpAYBAAAAAEBvCAgAvAYGFgMAAACfBgMCpAcKAAAAkEBNCAJ+CwAAAJ8HAgJSCQcAbwoMAJ8JAgJNCAnvDQAAAJ8IAQJSCQcAbwoOAJ8JAgJSCgcAbwsPAJ8KAgJSCwcAbwwQAJ8LAgJSDAcAbw0RAJ8MAgJSDQcAbw4SAJ8NAgJSDgcAbw8TAJ8OAgJSDwcAbxAUAJ8PAgJSEAcAbxEVAJ8QAgJNERB/FgAAAG8SFwCfEQICTRIQfxYAAABvExgAnxICAk0TBjEZAAAAbxYaALwUE9MbAAAAnxQDAlIVBwBvFhwAnxUCAlIWBwBvFxQAnxYCAlIXBwBvGB0AnxcCAm8aHgC8GBPTGwAAAJ8YAwJNGQloHwAAAG8aIACfGQICTRoJGiEAAABvGyIAnxoCAm8dIwC8GxnTGwAAAJ8bAwJvHiQAvBwb0xsAAACfHAMCbx8lALwdHNMbAAAAnx0DAm8gJgC8HhzTGwAAAJ8eAwJvIScAvB8c0xsAAACfHwMCbyIoALwgHNMbAAAAnyADAm8jKQC8IRzTGwAAAJ8hAwJvJCoAvCIc0xsAAACfIgMCbyUrALwjHNMbAAAAnyMDAm8mLAC8JCHTGwAAAJ8kAwJvJi0AvCQk0xsAAACfJAMCbycuALwlJNMbAAAAnyUDAm8oLwC8JhvTGwAAAJ8mAwJvKTAAvCcb0xsAAACfJwMCqSgAADAoG4AxAAAAbyojALwoHdMbAAAAnygDAm8rIgC8KR3TGwAAAJ8pAwJvLDIAvCod0xsAAACfKgMCby0zALwrHdMbAAAAnysDAm8uNAC8LBzTGwAAAJ8sAwJvLzQAvC0s0xsAAACfLQMCby81ALwtLdMbAAAAny0DAk0uLDg0AAAAbzA2ALwuLtMbAAAAny4DAsYvAACpMAAAqTEAAE0yDaA3AAAAxjMAAMY0AADGNQAATTcqVTgAAABNNjcAOQAAAMY3AADGOAAAxjkAAMY6AADGOwAA/zwAAAAAAACpPQAAMD0AojoAAAD/PQAAAAAAAKQ+PQAA8LCD2T8AABIBL/+fPgIBqT4AADA+LIAxAAAA2T4BABIBPf8SATn/EgAWABIBPP8SATP/EgATABIAJAASATL/EgE3/xIAIQASAB8AEgARABIACwASACYAEgAXABg+AHg+AAAA2T4CABIBPP8SAT3/EgE5/xIBM/8SABMAEgE3/xIAJAASATL/GD4AaD8AAADZPgMAEgE9/xIAEwAYPgATQAAAANk+BAASAT3/GD4AL0EAAADAPkIAEgAeABg+APlDAAAAwD5EABIAHgASAA0AEgAdABIAFgAYPgAWRQAAAE1ABIdGAAAATT9AdEcAAABNPj8YSAAAADVAABZFAAAAvD4+x0kAAACfPgMBwD5KABIADQASAA4AEgAeABg+ABBLAAAA2T4IABIBMP8SAB4AEgANABIABAAYPgAbTAAAAE0/HuRNAAAATT4/Hk4AAAA1QAAbTAAAALw+PsdJAAAAnz4DAU0/Hi5PAAAATT4/uFAAAADAQFEAvD4+x0kAAACfPgMBTT4eLk8AAABvQFIAvD4+lFMAAACfPgMCwEBUABIAHgASAA0AvD4+x0kAAACfPgMB2T4LABIBPf8SABMAEgAiABIAIAAYPgDMVQAAANk+DAASAAgAEgAjABIBMv8SAA0AEgAkABIBPP8SABMAGD4AmVYAAADZPg0AEgATABIBMv8SAA0AEgAjABIACAASABsAEgEz/xIAHgASATz/EgE3/xIBOf8SATv/EgAkABg+AKtXAAAA2T4OABIALAASAC0AEgAWABIBNf8SAC4AEgE0/xg+ANNYAAAA2T4PABIBOf8SABYAEgE1/xIBNP8SACwAGD4AVlkAAADiQGQA/0EAAAEAAADAQmUAxUFCAgEAAAAwQUAIWgAAAP9BAAABAAAA2UIRABIBPP/FQUICAQAAADBBQJNbAAAA/0EAAAEAAADZQhIAEgE8/xIAFgDFQUICAQAAADBBQA1cAAAA/0EAAAEAAADAQmYAEgAWAMVBQgIBAAAAMEFAXl0AAAD/QQAAAQAAANlCFAASATz/xUFCAgEAAAAwQUDhXgAAAP9BAAABAAAAwEJnAMVBQgIBAAAAMEFAjF8AAAD/QQAAAQAAAMBCaADFQUICAQAAADBBQPRgAAAA2UEXABIBPP8SATP/EgAWADBBQMlhAAAAwEFpABIAAAASABQAEgATABIAFwAwQUANYgAAAMBBagASAAgAEgAbABIAIgASACAAMEFAjWMAAADAQWsAEgAAADBBQKI6AAAAvD4X72wAAACfPgMBTT4Mdm0AAABNPypVOAAAAMBAbgASACoAwEFvABIAKgASADYAnz4EAlI3PgBSQCgAb0E5AG9CcABvQ1IAvD4VJHEAAACfPgYCTT8Mdm0AAABNQChVOAAAANlBHQASABYAEgEx/xIBN/8SACQAEgATABIAKAASABcA2UIeABIBMf8SATf/EgE8/xIAEwASACQAEgEy/xIAFQASAD4AEgAXAJ8/BAJSOT8ATT8Mdm0AAABNQCtVOAAAAMBBcgASAB4AEgArAMBCcwASAB4Anz8EAlI7PwBNPwkaIQAAAG9AIgCfPwICTUAM+nQAAABNQiPHMwAAAE1BQlU4AAAAwEJ1ABIAAQASABIAn0ADAhhAAOZ2AAAATUAM+nQAAABNQSlVOAAAANlCIgASABoAEgEz/xIAFwASAAoAn0ADAlI4QABNQAz6dAAAAE1BJVU4AAAA2UIjABIAPwASAA4AEgAKABIBN/+fQAMCUjpAAE1ADPp0AAAAb0R3ALxCG9MbAAAAn0IDAk1BQlU4AAAA2UIkABIAHgASATv/EgAbABIAFwCfQAMB4kJ5ANlDJQASAD8AEgAOABIBPP8SABMAEgEy/xIAFwASAAoAEgAaADBDQg94AAAAvEAXp3oAAACfQAMBwS8AAIIAAgB7AwEEAAAAQAPEAQMaA8UBA8YBA8cBAxkDPgPIAQQAAJBAA8kBA8oBAxEDywEDzAEDzQEDzgEDzwED0AED0QED0gED0wED1AEDdgO1AQPVAQPWAQPXAQPYAQPZAQPaAQPbAQPcAQO7AQOmAQPdAQPeAQPfAQPgAQPhAQPiAQPjAQPkAQMQA+UBA+YBAykD5wEDCgPoAQNLA+kBA+oBA6IBA3oDFgOvAQObAQMFA2gEAPCwgwMlAygDKwMtBggDNwYJA04DYANhA+sBAxgGCgNfA20DZQMXAzQD7AEGDQM2A+0BBg4DcgN1A4gBA5EBA5MBA+4BA+8BA/ABA/EBA/IBA/MBA/QBA5gBA6wBA64BBQtaW1xdXl9gYWJjOgYZBhwGHgYfBiIGIwYkA/UBA/YBBiUGJgOxAQP3AQYpBioD+AEGKwP5AQP6AQPDAQUBeAP7ASYABAUGBwgJCgwNDg8QFBcYGRobHB0eHyAiIyQlJicoKSorLC0uLwEAAQYAAAADAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAABAAAAAAAGAAAAAAIAAAAAAAIAAAEAAAEAAAIAAAIA6AEAAAIAAAMAAAEAAAABAAAAAgACAAAAAwAAAgAAAgAAAwAAAAEAAAABAAAABAAAAAEAAAABAAAAAQAAAAEAAOABAAAAAQAAAAEAAAABAAAAAQAAAAAAAAABAAAAAQAAAAEAAAADAAACAAAAAQAAAAEAAAABAAAAAgAAAAEAAADtAAAAAQAAAAAAAQIBAQABAQECAAAAAQAAAAABAAQAAA8AAgAAAAAHAAACAAAAAAAAAAAAAAAAAAAAAAA/AAAAlgAAAAAAAC0AAAAACAAAAAoAAAAJAAAAAAAAEgAAAAAAAAAAAAADAAAAAAAaAAAAAAAAFgAAAAAAAAAAAQAAAHIAAAAGAAAAAAAAAAAAAAAEAAAAAAAADAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAABJAAAAAAAAAAAfAAAAAAB7ABUCAAEAAP8ABgABAAAA/wAHAAEAAAAA/wAKAAEAAAD/AAgAAQAAAP8ABwABAAD/AAoAAQAA/wAGAAAAAAAR6wAAAAAAHAAAAAAAAA4AAACNAAB5AAAAAQAEAAD7AAwAAAAAAAACAAAAAQAAAAAAAAAPAAAAAAAAAAAA8AAbAF4AAQAABAD7AAoAAAACAAAAAAAAAAAAAAAGAAAAAAAAAAAAAAkAAAAAAAAAAAAACwAAAAAAAAAAAAAAAAAMAQDOAAAAAAAAAAD/AAAOAAEAAAAYAAAAIAAAABMAAABqAAAAjgAAAIUAAAAVAAAAogAAADIAAAAAMA7am2jUH96MqYMEV0JotrF+wowcPB7xaQ==

-- Decompiler will be improved VERY SOON!
-- Decompiled with Konstant V2.1, a fast Luau decompiler made in Luau by plusgiant5 (https://discord.gg/brNTY8nX8t)
-- Decompiled on 2025-12-11 01:07:04
-- Luau version 6, Types version 3
-- Time taken: 0.080699 seconds

local module_upvr = {}
local TextChatService_upvr = game:GetService("TextChatService")
local Load = require(game:GetService("ReplicatedStorage").Load)
local any_new_result1_3_upvr = Load("Maid").new()
local Load_result1 = Load("GuiHandler")
local Load_result1_3_upvr = Load("MenuHandler")
local var3_result1 = Load("ButtonHandler")
local var3_result1_upvr = Load("Constants")
local Load_result1_upvr = Load("Enums")
local var3_result1_2 = Load("Databases")
local LocalPlayer_upvr = game:GetService("Players").LocalPlayer
local Load_result1_5_upvr = Load("Utility")
local Load_result1_upvr_2 = Load("SoundFX")
local Load_result1_4_upvr = Load("Network")
local any_GetFrame_result1_upvr_2 = Load_result1.GetFrame("Inventory")
local Trade_upvr = Load_result1.GetScreenGui("TradeUI"):WaitForChild("Trade")
local Interface = Trade_upvr:WaitForChild("Interface")
local Buttons_upvr = Interface:WaitForChild("Buttons")
local ChatWindow_upvr = Interface:WaitForChild("ChatWindow")
local OtherPlayerGrid_upvr = Interface:WaitForChild("OtherPlayerGrid")
local YourOffer_upvr = Interface:WaitForChild("YourOffer")
local YourGrid_upvr = Interface:WaitForChild("YourGrid")
local TradingVIPLock_upvr = Interface:WaitForChild("TradingVIPLock")
local AddFrame_upvr = YourOffer_upvr:WaitForChild("List"):WaitForChild("AddFrame")
Trade_upvr.Visible = false
local Trade_upvr_2 = Buttons_upvr:WaitForChild("Trade")
local Remove_upvr = Buttons_upvr:WaitForChild("Remove")
local Chat_upvr = Buttons_upvr:WaitForChild("Chat")
local Countdown_upvr = Interface:WaitForChild("Countdown")
local var29_upvw = false
local NUM_TRADE_SLOTS_upvw = var3_result1_upvr.NUM_TRADE_SLOTS
local var31_upvw
local var32_upvw
local var33_upvw
local var34_upvw
local var35_upvw
local tbl_upvw_2 = {}
module_upvr.TradingDisabled = false
local tbl_upvw = {}
local var39_upvw
task.spawn(function() -- Line 110
	--[[ Upvalues[1]:
		[1]: var39_upvw (read and write)
	]]
	while not game.StarterGui:GetCore("ChatWindowSize") do
		task.wait()
	end
	var39_upvw = game.StarterGui:GetCore("ChatWindowSize")
end)
Countdown_upvr.Visible = false
local OtherPlayerOffer_upvr = Interface:WaitForChild("OtherPlayerOffer")
local any_Get_result1_upvr_2 = var3_result1_2.Get("All")
local Load_result1_2_upvr = Load("InventoryCell")
local RemoveIcon_upvr = Trade_upvr:WaitForChild("RemoveIcon")
function AddItem(arg1, arg2, arg3) -- Line 119
	--[[ Upvalues[15]:
		[1]: tbl_upvw (read and write)
		[2]: var35_upvw (read and write)
		[3]: Load_result1_upvr_2 (readonly)
		[4]: tbl_upvw_2 (read and write)
		[5]: var31_upvw (read and write)
		[6]: LocalPlayer_upvr (readonly)
		[7]: AddFrame_upvr (readonly)
		[8]: NUM_TRADE_SLOTS_upvw (read and write)
		[9]: var34_upvw (read and write)
		[10]: YourOffer_upvr (readonly)
		[11]: OtherPlayerOffer_upvr (readonly)
		[12]: any_Get_result1_upvr_2 (readonly)
		[13]: Load_result1_2_upvr (readonly)
		[14]: RemoveIcon_upvr (readonly)
		[15]: Load_result1_4_upvr (readonly)
	]]
	local var53
	if not var53 then
		var53 = tbl_upvw
		var53[arg1] = {}
	end
	if not arg3 then
		var53 = var35_upvw:IsDown()
		if var53 then
			var53 = var35_upvw:SetToggle
			var53(false, true)
		end
		var53 = Load_result1_upvr_2.PlaySound
		var53("CardPlace")
		var53 = #tbl_upvw_2[var31_upvw]
		if var53 == 0 then
			var53 = #tbl_upvw_2[LocalPlayer_upvr]
			if var53 == 0 then
				var53 = var35_upvw:SetEnabled
				var53(false)
				-- KONSTANTWARNING: GOTO [47] #40
			end
		end
		var53 = var35_upvw:SetEnabled
		var53(true)
		var53 = LocalPlayer_upvr
		local var54
		if arg1 == var53 then
			var53 = AddFrame_upvr
			if #tbl_upvw_2[arg1] >= NUM_TRADE_SLOTS_upvw then
				var54 = false
			else
				var54 = true
			end
			var53.Visible = var54
			var53 = var34_upvw:SetEnabled
			var53(true)
		end
	end
	local function INLINED_2() -- Internal function, doesn't exist in bytecode
		var53 = YourOffer_upvr.List
		return var53
	end
	if arg1 ~= LocalPlayer_upvr or not INLINED_2() then
		var53 = OtherPlayerOffer_upvr.List
	end
	local any_new_result1_2 = Load_result1_2_upvr.new(any_Get_result1_upvr_2[arg2].Type, arg2, 1, true)
	if arg1 == LocalPlayer_upvr then
		local clone_upvr = RemoveIcon_upvr:Clone()
		clone_upvr.Parent = any_new_result1_2.Cell
		clone_upvr.Visible = var34_upvw:IsDown()
		local var58_upvw
		local var59_upvr = #tbl_upvw[arg1] + 1
		var58_upvw = clone_upvr.Mover.Activated:Connect(function() -- Line 160
			--[[ Upvalues[4]:
				[1]: var58_upvw (read and write)
				[2]: Load_result1_4_upvr (copied, readonly)
				[3]: arg2 (readonly)
				[4]: var59_upvr (readonly)
			]]
			var58_upvw:Disconnect()
			Load_result1_4_upvr:FireServer("RemoveItem", arg2, var59_upvr)
		end)
		if game:GetService("UserInputService").MouseEnabled and game:GetService("UserInputService").KeyboardEnabled then
			any_new_result1_2.Cell.MouseEnter:Connect(function() -- Line 166
				--[[ Upvalues[1]:
					[1]: clone_upvr (readonly)
				]]
				clone_upvr.Visible = true
			end)
			any_new_result1_2.Cell.MouseLeave:Connect(function() -- Line 169
				--[[ Upvalues[1]:
					[1]: clone_upvr (readonly)
				]]
				clone_upvr.Visible = false
			end)
		end
	end
	var59_upvr = any_new_result1_2.Cell
	clone_upvr = var59_upvr.UIScale
	var59_upvr = 1
	clone_upvr.Scale = var59_upvr
	var59_upvr = any_new_result1_2.Cell.ItemInfo
	clone_upvr = var59_upvr.Quantity
	var59_upvr = false
	clone_upvr.Visible = var59_upvr
	clone_upvr = any_new_result1_2.Cell
	clone_upvr.Parent = var53
	var59_upvr = tbl_upvw[arg1]
	clone_upvr = table.insert
	clone_upvr(var59_upvr, any_new_result1_2)
end
function RefreshList(arg1, arg2) -- Line 182
	--[[ Upvalues[8]:
		[1]: tbl_upvw_2 (read and write)
		[2]: tbl_upvw (read and write)
		[3]: var35_upvw (read and write)
		[4]: var31_upvw (read and write)
		[5]: LocalPlayer_upvr (readonly)
		[6]: var34_upvw (read and write)
		[7]: AddFrame_upvr (readonly)
		[8]: NUM_TRADE_SLOTS_upvw (read and write)
	]]
	-- KONSTANTWARNING: Variable analysis failed. Output will have some incorrect variable assignments
	local var103 = tbl_upvw_2[arg1]
	if not tbl_upvw[arg1] then
		tbl_upvw[arg1] = {}
	end
	if not arg2 then
		if var35_upvw:IsDown() then
			var35_upvw:SetToggle(false, true)
		end
		if #tbl_upvw_2[var31_upvw] == 0 and #tbl_upvw_2[LocalPlayer_upvr] == 0 then
			var35_upvw:SetEnabled(false)
		else
			var35_upvw:SetEnabled(true)
		end
	end
	local var104
	if arg1 == LocalPlayer_upvr then
		local var105
		if #var103 == 0 then
			var104 = false
		else
			var104 = true
		end
		var34_upvw:SetEnabled(var104)
		if not var35_upvw:IsDown() then
			var104 = #tbl_upvw_2[arg1]
			if var104 >= NUM_TRADE_SLOTS_upvw then
			else
			end
			AddFrame_upvr.Visible = true
		end
	end
	for _, v in ipairs(tbl_upvw[arg1]) do
		v:Destroy()
	end
	tbl_upvw[arg1] = {}
	for _, v_2 in ipairs(var103) do
		AddItem(arg1, v_2, true)
	end
	AddFrame_upvr.UIScale.Scale = 1
end
function XsEnabled(arg1) -- Line 227
	--[[ Upvalues[2]:
		[1]: tbl_upvw (read and write)
		[2]: LocalPlayer_upvr (readonly)
	]]
	for _, v_3 in ipairs(tbl_upvw[LocalPlayer_upvr]) do
		if v_3.Cell:FindFirstChild("RemoveIcon") then
			v_3.Cell.RemoveIcon.Visible = arg1
		end
	end
end
function ClearBoard() -- Line 235
	--[[ Upvalues[1]:
		[1]: tbl_upvw (read and write)
	]]
	for _, v_4 in pairs(tbl_upvw) do
		for _, v_5 in ipairs(v_4) do
			v_5:Destroy()
		end
	end
	tbl_upvw = {}
end
function ClearChat() -- Line 245
	--[[ Upvalues[1]:
		[1]: ChatWindow_upvr (readonly)
	]]
	for _, v_6 in ChatWindow_upvr.ChatLogs:GetChildren() do
		if v_6:IsA("TextLabel") and v_6.Name ~= "NewChatEntry" then
			v_6:Destroy()
		end
	end
	ChatWindow_upvr.ChatBar.Text = ""
end
function IncomingTradeChat(arg1) -- Line 254
	--[[ Upvalues[4]:
		[1]: ChatWindow_upvr (readonly)
		[2]: var3_result1_upvr (readonly)
		[3]: Buttons_upvr (readonly)
		[4]: Load_result1_upvr_2 (readonly)
	]]
	print("GOT IT")
	local var132
	if arg1.Status ~= Enum.TextChatMessageStatus.Success then
	else
		local clone_3 = ChatWindow_upvr.ChatLogs.NewChatEntry:Clone()
		local any_GetPlayerByUserId_result1 = game.Players:GetPlayerByUserId(arg1.TextSource.UserId)
		clone_3.Name = "Log"
		clone_3.LayoutOrder = 0
		if any_GetPlayerByUserId_result1.HasVerifiedBadge then
			var132 = "?"
		else
			var132 = ""
		end
		clone_3.Text = `@{any_GetPlayerByUserId_result1.Name}{var132}:  {arg1.Text}`
		clone_3.TextColor3 = var3_result1_upvr.COLOR.WHITE
		clone_3.Parent = ChatWindow_upvr.ChatLogs
		Buttons_upvr.Chat.Alert.Visible = not ChatWindow_upvr.Visible
		Load_result1_upvr_2.PlaySound("Blip")
	end
end
TextChatService_upvr.TextChannels.TradeChannel.MessageReceived:Connect(IncomingTradeChat)
function SendChatIntro(arg1) -- Line 275
	--[[ Upvalues[3]:
		[1]: var3_result1_upvr (readonly)
		[2]: Load_result1_upvr (readonly)
		[3]: ChatWindow_upvr (readonly)
	]]
	local Rights = arg1:GetAttribute("Rights")
	local var136 = "You are trading with a PLAYER. This user is NOT a mod, admin, or dev."
	local LIGHT_YELLOW = var3_result1_upvr.COLOR.LIGHT_YELLOW
	if arg1:GetAttribute("ChatEffects") then
		if Load_result1_upvr.Rights.Dev <= Rights then
			var136 = "You are trading with an official Survive the Killer developer."
			LIGHT_YELLOW = var3_result1_upvr.COLOR.BLUE
		elseif Load_result1_upvr.Rights.Admin <= Rights then
			var136 = "You are trading with an official Survive the Killer admin."
			LIGHT_YELLOW = var3_result1_upvr.COLOR.RED
		elseif Load_result1_upvr.Rights.Mod <= Rights then
			var136 = "You are trading with an official Survive the killer mod."
			LIGHT_YELLOW = var3_result1_upvr.COLOR.LIME_GREEN
		end
	end
	local clone = ChatWindow_upvr.ChatLogs.NewChatEntry:Clone()
	clone.Name = "Log"
	clone.LayoutOrder = -2
	clone.Text = `?? <font color="#{LIGHT_YELLOW:ToHex()}">{var136}</font>`
	clone.Parent = ChatWindow_upvr.ChatLogs
end
local var139_upvw = false
function SendTradeChat() -- Line 301
	--[[ Upvalues[4]:
		[1]: var139_upvw (read and write)
		[2]: ChatWindow_upvr (readonly)
		[3]: var3_result1_upvr (readonly)
		[4]: TextChatService_upvr (readonly)
	]]
	if var139_upvw or ChatWindow_upvr.ChatBar.Text == "" or 100 < string.len(ChatWindow_upvr.ChatBar.Text) then
	else
		var139_upvw = true
		ChatWindow_upvr.Send.BackgroundColor3 = var3_result1_upvr.COLOR.GREY
		task.spawn(function() -- Line 308
			--[[ Upvalues[2]:
				[1]: TextChatService_upvr (copied, readonly)
				[2]: ChatWindow_upvr (copied, readonly)
			]]
			TextChatService_upvr.TextChannels.TradeChannel:SendAsync(ChatWindow_upvr.ChatBar.Text)
		end)
		ChatWindow_upvr.ChatBar.Text = ""
		for i_8 = 3, 1, -1 do
			ChatWindow_upvr.Send.Text = `{i_8}`
			task.wait(1)
		end
		ChatWindow_upvr.Send.BackgroundColor3 = Color3.fromRGB(0, 120, 255)
		ChatWindow_upvr.Send.Text = "SEND"
		var139_upvw = false
	end
end
ChatWindow_upvr.Send.Activated:Connect(SendTradeChat)
ChatWindow_upvr.ChatBar.FocusLost:Connect(function(arg1) -- Line 324
	if arg1 then
		SendTradeChat()
	end
end)
ChatWindow_upvr.ChatBar:GetPropertyChangedSignal("Text"):Connect(function() -- Line 330
	--[[ Upvalues[2]:
		[1]: ChatWindow_upvr (readonly)
		[2]: var3_result1_upvr (readonly)
	]]
	local var144 = ChatWindow_upvr
	if 100 < string.len(ChatWindow_upvr.ChatBar.Text) then
		var144 = var3_result1_upvr.COLOR.RED
	else
		var144 = var3_result1_upvr.COLOR.WHITE
	end
	var144.ChatBar.TextColor3 = var144
end)
function GreenOutlineEnabled(arg1, arg2) -- Line 334
	--[[ Upvalues[4]:
		[1]: tbl_upvw (read and write)
		[2]: LocalPlayer_upvr (readonly)
		[3]: YourGrid_upvr (readonly)
		[4]: OtherPlayerGrid_upvr (readonly)
	]]
	local _, ipairs_result2_2, ipairs_result3_2 = ipairs(tbl_upvw[arg1])
	local var152
	for _, v_7 in var152, ipairs_result2_2, ipairs_result3_2 do
		if arg2 then
			v_7:Select()
		else
			v_7:Deselect()
		end
	end
	local function INLINED_3() -- Internal function, doesn't exist in bytecode
		var152 = YourGrid_upvr.List
		return var152
	end
	if arg1 ~= LocalPlayer_upvr or not INLINED_3() then
		var152 = OtherPlayerGrid_upvr.List
	end
	var152.Grid1.ReadyIcon.Visible = arg2
end
function UnlockTradingVIP() -- Line 346
	--[[ Upvalues[7]:
		[1]: any_new_result1_3_upvr (readonly)
		[2]: TradingVIPLock_upvr (readonly)
		[3]: NUM_TRADE_SLOTS_upvw (read and write)
		[4]: var3_result1_upvr (readonly)
		[5]: AddFrame_upvr (readonly)
		[6]: tbl_upvw_2 (read and write)
		[7]: LocalPlayer_upvr (readonly)
	]]
	any_new_result1_3_upvr:DoCleaning()
	TradingVIPLock_upvr.Visible = false
	local var153 = var3_result1_upvr
	NUM_TRADE_SLOTS_upvw = var153.NUM_VIP_TRADE_SLOTS
	if #tbl_upvw_2[LocalPlayer_upvr] >= NUM_TRADE_SLOTS_upvw then
		var153 = false
	else
		var153 = true
	end
	AddFrame_upvr.Visible = var153
end
local var154_upvw
function StartTrading(arg1) -- Line 353
	--[[ Upvalues[13]:
		[1]: LocalPlayer_upvr (readonly)
		[2]: NUM_TRADE_SLOTS_upvw (read and write)
		[3]: var3_result1_upvr (readonly)
		[4]: TradingVIPLock_upvr (readonly)
		[5]: any_new_result1_3_upvr (readonly)
		[6]: Trade_upvr (readonly)
		[7]: var31_upvw (read and write)
		[8]: ChatWindow_upvr (readonly)
		[9]: tbl_upvw_2 (read and write)
		[10]: var34_upvw (read and write)
		[11]: var35_upvw (read and write)
		[12]: var154_upvw (read and write)
		[13]: AddFrame_upvr (readonly)
	]]
	-- KONSTANTWARNING: Variable analysis failed. Output will have some incorrect variable assignments
	local TradingVIP = LocalPlayer_upvr.Gamepasses:GetAttribute("TradingVIP")
	if not TradingVIP then
		TradingVIP = arg1.Gamepasses:GetAttribute("TradingVIP")
	end
	if not TradingVIP or not var3_result1_upvr.NUM_VIP_TRADE_SLOTS then
	end
	NUM_TRADE_SLOTS_upvw = var3_result1_upvr.NUM_TRADE_SLOTS
	TradingVIPLock_upvr.Visible = not TradingVIP
	if not TradingVIP then
		any_new_result1_3_upvr.ThisPlayerGamepassListener = LocalPlayer_upvr.Gamepasses:GetAttributeChangedSignal("TradingVIP"):Connect(function() -- Line 361
			--[[ Upvalues[1]:
				[1]: LocalPlayer_upvr (copied, readonly)
			]]
			if LocalPlayer_upvr.Gamepasses:GetAttribute("TradingVIP") then
				UnlockTradingVIP()
			end
		end)
		any_new_result1_3_upvr.OtherPlayerGamepassListener = arg1.Gamepasses:GetAttributeChangedSignal("TradingVIP"):Connect(function() -- Line 366
			--[[ Upvalues[1]:
				[1]: arg1 (readonly)
			]]
			if arg1.Gamepasses:GetAttribute("TradingVIP") then
				UnlockTradingVIP()
			end
		end)
	end
	Trade_upvr:SetAttribute("TradingWith", arg1.Name)
	if arg1.HasVerifiedBadge then
	else
	end
	Trade_upvr.Title.TextLabel.Text = `Trading with {arg1.Name}{""}`
	var31_upvw = arg1
	Trade_upvr.Visible = true
	game:GetService("ContentProvider"):Preload("rbxassetid://1598630577")
	ClearBoard()
	ClearChat()
	ChatWindow_upvr.ChatLogs.NewChatEntry.Text = `Trading chat with @{arg1.Name}.`
	ChatWindow_upvr.ChatBar.PlaceholderText = `Type here to chat with @{arg1.Name}...`
	SendChatIntro(arg1)
	tbl_upvw_2 = {
		[arg1] = {};
		[LocalPlayer_upvr] = {};
	}
	RefreshList(LocalPlayer_upvr)
	RefreshList(arg1)
	var34_upvw:SetToggle(false)
	var35_upvw:SetEnabled(false)
	var34_upvw:SetEnabled(false)
	var154_upvw:SetToggle(false)
	ChatWindow_upvr.Visible = false
	AddFrame_upvr.Visible = true
	task.spawn(function() -- Line 413
		--[[ Upvalues[1]:
			[1]: Trade_upvr (copied, readonly)
		]]
		task.wait()
		while Trade_upvr.Parent.AbsoluteSize.X <= Trade_upvr.AbsoluteSize.X do
			Trade_upvr.UIScale.Scale = Trade_upvr.UIScale.Scale - 0.03
			task.wait()
		end
	end)
end
local CountdownText_upvr = Countdown_upvr:WaitForChild("Countdown"):WaitForChild("CountdownText")
local Icon_upvr = Countdown_upvr.Countdown:WaitForChild("Icon")
function StartCountdown(arg1) -- Line 426
	--[[ Upvalues[6]:
		[1]: Countdown_upvr (readonly)
		[2]: CountdownText_upvr (readonly)
		[3]: Load_result1_upvr_2 (readonly)
		[4]: var33_upvw (read and write)
		[5]: Icon_upvr (readonly)
		[6]: var32_upvw (read and write)
	]]
	Countdown_upvr.Visible = true
	CountdownText_upvr.Visible = true
	Load_result1_upvr_2.PlaySound("TradeGenerator")
	local var163_upvw = 0
	local var164_upvw = 0
	var33_upvw = game:GetService("RunService").RenderStepped:Connect(function(arg1_2) -- Line 436
		--[[ Upvalues[3]:
			[1]: var163_upvw (read and write)
			[2]: var164_upvw (read and write)
			[3]: Icon_upvr (copied, readonly)
		]]
		var163_upvw = arg1_2 * 60
		if var164_upvw < 40 then
			var164_upvw += var163_upvw * 0.1
		end
		Icon_upvr.Rotation += var164_upvw % 360
	end)
	if var32_upvw then
		var32_upvw:Disconnect()
	end
	local var166_upvw
	var32_upvw = game:GetService("RunService").Heartbeat:Connect(function() -- Line 446
		--[[ Upvalues[3]:
			[1]: var166_upvw (read and write)
			[2]: CountdownText_upvr (copied, readonly)
			[3]: arg1 (readonly)
		]]
		if var166_upvw ~= os.time() then
			var166_upvw = os.time()
			CountdownText_upvr.Text = tostring(arg1 - os.time())
			if var166_upvw == arg1 then
				CountdownText_upvr.Visible = false
			end
		end
	end)
end
function CancelCountdown(arg1) -- Line 457
	--[[ Upvalues[5]:
		[1]: var35_upvw (read and write)
		[2]: Load_result1_upvr_2 (readonly)
		[3]: var33_upvw (read and write)
		[4]: var32_upvw (read and write)
		[5]: Countdown_upvr (readonly)
	]]
	if arg1 then
		var35_upvw:SetToggle(false, true)
	else
		Load_result1_upvr_2.StopSound("TradeGenerator")
	end
	if var33_upvw then
		var33_upvw:Disconnect()
	end
	if var32_upvw then
		var32_upvw:Disconnect()
	end
	Countdown_upvr.Visible = false
end
local tbl = {
	TradingStarted = {function(arg1) -- Line 481
		StartTrading(arg1)
	end};
	ItemAdded = {function(arg1, arg2) -- Line 487
		--[[ Upvalues[1]:
			[1]: tbl_upvw_2 (read and write)
		]]
		table.insert(tbl_upvw_2[arg1], arg2)
		AddItem(arg1, arg2)
	end};
	OfferChanged = {function(arg1, arg2) -- Line 494
		--[[ Upvalues[2]:
			[1]: tbl_upvw_2 (read and write)
			[2]: Load_result1_upvr_2 (readonly)
		]]
		if #arg2 < #tbl_upvw_2[arg1] then
			Load_result1_upvr_2.PlaySound("CardLift")
		end
		tbl_upvw_2[arg1] = arg2
		RefreshList(arg1)
	end};
	SetReady = {function(arg1, arg2) -- Line 504
		--[[ Upvalues[1]:
			[1]: Load_result1_upvr_2 (readonly)
		]]
		if arg2 then
			Load_result1_upvr_2.PlaySound("ReadyUp")
		end
		GreenOutlineEnabled(arg1, arg2)
	end};
	FinalRefresh = {function(arg1, arg2) -- Line 512
		--[[ Upvalues[1]:
			[1]: tbl_upvw_2 (read and write)
		]]
		tbl_upvw_2[arg1] = arg2
		RefreshList(arg1, true)
		GreenOutlineEnabled(arg1, true)
	end};
	CountdownStarted = {function(arg1) -- Line 519
		local var180
		if 5 < math.abs(os.time() - arg1) then
			var180 = os.time() + 4
		end
		StartCountdown(var180)
	end};
	CountdownCanceled = {function() -- Line 529
		CancelCountdown()
	end};
}
function tbl.TradeComplete() -- Line 534
	--[[ Upvalues[3]:
		[1]: tbl_upvw_2 (read and write)
		[2]: var31_upvw (read and write)
		[3]: Load_result1_upvr_2 (readonly)
	]]
	task.wait(5)
	CancelCountdown(true)
	if #tbl_upvw_2[var31_upvw] ~= 0 then
		Load_result1_upvr_2.StopSound("TradeGenerator")
	else
		Load_result1_upvr_2.StopSound("TradeGenerator")
	end
	ClearBoard()
end
local Settings_upvr = LocalPlayer_upvr:WaitForChild("Settings")
function tbl.PromptTradeRequest(arg1) -- Line 551
	--[[ Upvalues[4]:
		[1]: module_upvr (readonly)
		[2]: Settings_upvr (readonly)
		[3]: LocalPlayer_upvr (readonly)
		[4]: Load_result1_4_upvr (readonly)
	]]
	if module_upvr.TradingDisabled then
	else
		if not Settings_upvr:GetAttribute("trade_requests") then return end
		if LocalPlayer_upvr:GetAttribute("TeamID") ~= "Lobby" then return end
		if arg1:GetAttribute("TeamID") ~= "Lobby" then return end
		local BindableFunction_upvr = Instance.new("BindableFunction")
		function BindableFunction_upvr.OnInvoke(arg1_3) -- Line 561
			--[[ Upvalues[3]:
				[1]: Load_result1_4_upvr (copied, readonly)
				[2]: arg1 (readonly)
				[3]: BindableFunction_upvr (readonly)
			]]
			Load_result1_4_upvr:FireServer("TradeRequestOptionChosen", arg1_3, arg1)
			if BindableFunction_upvr then
				BindableFunction_upvr:Destroy()
			end
		end
		game.StarterGui:SetCore("SendNotification", {
			Title = "Trade";
			Text = arg1.Name.." wants to trade";
			Icon = "rbxassetid://6559295488";
			Callback = BindableFunction_upvr;
			Button1 = "Accept";
			Button2 = "Decline";
		})
	end
end
function tbl.TradeSessionEnded() -- Line 579
	--[[ Upvalues[4]:
		[1]: any_new_result1_3_upvr (readonly)
		[2]: Trade_upvr (readonly)
		[3]: YourGrid_upvr (readonly)
		[4]: OtherPlayerGrid_upvr (readonly)
	]]
	any_new_result1_3_upvr:DoCleaning()
	Trade_upvr:SetAttribute("TradingWith", "")
	Trade_upvr.Visible = false
	YourGrid_upvr.List.Grid1.ReadyIcon.Visible = false
	OtherPlayerGrid_upvr.List.Grid1.ReadyIcon.Visible = false
	task.delay(1, CancelCountdown)
end
function tbl.TradingDisabled() -- Line 593
	--[[ Upvalues[1]:
		[1]: module_upvr (readonly)
	]]
	module_upvr.TradingDisabled = true
end
Load_result1_4_upvr:BindEvents(tbl)
local ImageColor3_upvr = Remove_upvr.Mover.ImageColor3
var34_upvw = var3_result1.WrapToggle(Remove_upvr.Mover, function() -- Line 600
	--[[ Upvalues[1]:
		[1]: Remove_upvr (readonly)
	]]
	XsEnabled(true)
	Remove_upvr.Mover.ImageColor3 = Color3.fromRGB(185, 57, 57)
end, function() -- Line 604
	--[[ Upvalues[2]:
		[1]: Remove_upvr (readonly)
		[2]: ImageColor3_upvr (readonly)
	]]
	XsEnabled(false)
	Remove_upvr.Mover.ImageColor3 = ImageColor3_upvr
end)
local var189_upvw = var34_upvw
local any_SaveState_result1_upvr = Load_result1_5_upvr:SaveState(Trade_upvr_2, "ImageColor3", "Image", "Text")
var35_upvw = var3_result1.WrapToggle(Trade_upvr_2.Mover, function() -- Line 614
	--[[ Upvalues[7]:
		[1]: Load_result1_upvr_2 (readonly)
		[2]: var29_upvw (read and write)
		[3]: var189_upvw (read and write)
		[4]: AddFrame_upvr (readonly)
		[5]: LocalPlayer_upvr (readonly)
		[6]: Trade_upvr_2 (readonly)
		[7]: Load_result1_4_upvr (readonly)
	]]
	Load_result1_upvr_2.PlaySound("ReadyUp")
	var29_upvw = true
	var189_upvw:SetToggle(false, true)
	var189_upvw:SetEnabled(false)
	AddFrame_upvr.Visible = false
	GreenOutlineEnabled(LocalPlayer_upvr, true)
	Trade_upvr_2.Mover.ImageColor3 = Color3.fromRGB(193, 60, 60)
	Trade_upvr_2.ImageColor3 = Color3.fromRGB(138, 35, 35)
	Trade_upvr_2.Mover.Icon.Image = "rbxassetid://6559295243"
	Trade_upvr_2.Mover.Icon.Icon.Image = "rbxassetid://6559295243"
	Trade_upvr_2.Mover.TextLabel.Text = "Cancel"
	Load_result1_4_upvr:FireServer("ReadyUp")
end, function() -- Line 629
	--[[ Upvalues[9]:
		[1]: var29_upvw (read and write)
		[2]: var189_upvw (read and write)
		[3]: tbl_upvw_2 (read and write)
		[4]: LocalPlayer_upvr (readonly)
		[5]: AddFrame_upvr (readonly)
		[6]: NUM_TRADE_SLOTS_upvw (read and write)
		[7]: Load_result1_5_upvr (readonly)
		[8]: any_SaveState_result1_upvr (readonly)
		[9]: Load_result1_4_upvr (readonly)
	]]
	-- KONSTANTWARNING: Variable analysis failed. Output will have some incorrect variable assignments
	var29_upvw = false
	local var193
	if #tbl_upvw_2[LocalPlayer_upvr] == 0 then
		var193 = false
	else
		var193 = true
	end
	var189_upvw:SetEnabled(var193)
	var193 = #tbl_upvw_2[LocalPlayer_upvr]
	if var193 >= NUM_TRADE_SLOTS_upvw then
	else
	end
	AddFrame_upvr.Visible = true
	var193 = false
	GreenOutlineEnabled(LocalPlayer_upvr, var193)
	var193 = any_SaveState_result1_upvr
	Load_result1_5_upvr:RevertState(var193)
	var193 = "CancelReadyUp"
	Load_result1_4_upvr:FireServer(var193)
end)
var154_upvw = var3_result1.WrapToggle(Chat_upvr.Mover, function() -- Line 641
	--[[ Upvalues[2]:
		[1]: ChatWindow_upvr (readonly)
		[2]: Chat_upvr (readonly)
	]]
	ChatWindow_upvr.Visible = true
	Chat_upvr.Alert.Visible = false
end, function() -- Line 645
	--[[ Upvalues[1]:
		[1]: ChatWindow_upvr (readonly)
	]]
	ChatWindow_upvr.Visible = false
end)
local any_GetFrame_result1_upvr = Load_result1.GetFrame("Inventory")
local MarketplaceService_upvr = game:GetService("MarketplaceService")
local any_Get_result1_upvr = var3_result1_2.Get("Gamepasses")
Unlock = var3_result1.LegacyWrap(TradingVIPLock_upvr.Chat.Mover, function() -- Line 652
	--[[ Upvalues[2]:
		[1]: MarketplaceService_upvr (readonly)
		[2]: any_Get_result1_upvr (readonly)
	]]
	MarketplaceService_upvr:PromptGamePassPurchase(game.Players.LocalPlayer, any_Get_result1_upvr.TradingVIP.GamepassId)
end) -- Setting global
local function _() -- Line 658
	--[[ Upvalues[4]:
		[1]: any_GetFrame_result1_upvr_2 (readonly)
		[2]: var31_upvw (read and write)
		[3]: Load_result1_4_upvr (readonly)
		[4]: Load_result1_3_upvr (readonly)
	]]
	any_GetFrame_result1_upvr_2:SetAttribute("CurrentPlayer", var31_upvw.Name)
	Load_result1_4_upvr:FireServer("SetInventory", var31_upvw)
	Load_result1_3_upvr.OpenSubmenu("Inventory", "Knives")
end
local function _() -- Line 667
	--[[ Upvalues[4]:
		[1]: any_GetFrame_result1_upvr (readonly)
		[2]: Load_result1_upvr (readonly)
		[3]: Load_result1_3_upvr (readonly)
		[4]: var189_upvw (read and write)
	]]
	any_GetFrame_result1_upvr:SetAttribute("Mode", Load_result1_upvr.InventoryMode.Trading)
	Load_result1_3_upvr.OpenSubmenu("Inventory", "Knives")
	var189_upvw:SetToggle(false, true)
end
var3_result1.LegacyWrap(Trade_upvr:WaitForChild("Close").Mover, function() -- Line 678
	--[[ Upvalues[4]:
		[1]: ChatWindow_upvr (readonly)
		[2]: var154_upvw (read and write)
		[3]: Trade_upvr (readonly)
		[4]: Load_result1_4_upvr (readonly)
	]]
	if ChatWindow_upvr.Visible then
		ChatWindow_upvr.Visible = false
		var154_upvw:SetToggle(false)
	else
		Trade_upvr.Visible = false
		Load_result1_4_upvr:FireServer("EndTradeSession")
	end
end)
Load_result1_4_upvr:Listen({
	TradeSelectionBindable = function(arg1) -- Line 691, Named "TradeSelectionBindable"
		--[[ Upvalues[8]:
			[1]: any_GetFrame_result1_upvr (readonly)
			[2]: Load_result1_upvr (readonly)
			[3]: tbl_upvw_2 (read and write)
			[4]: LocalPlayer_upvr (readonly)
			[5]: NUM_TRADE_SLOTS_upvw (read and write)
			[6]: Load_result1_4_upvr (readonly)
			[7]: Load_result1_3_upvr (readonly)
			[8]: any_GetFrame_result1_upvr_2 (readonly)
		]]
		if not arg1 then
		else
			if not any_GetFrame_result1_upvr:GetAttribute("Mode") == Load_result1_upvr.InventoryMode.Trading then return end
			if #tbl_upvw_2[LocalPlayer_upvr] == NUM_TRADE_SLOTS_upvw then return end
			Load_result1_4_upvr:FireServer("AddItem", arg1)
			Load_result1_3_upvr.CloseMenu()
			any_GetFrame_result1_upvr_2:SetAttribute("Mode", Load_result1_upvr.InventoryMode.Default)
		end
	end;
})
return module_upvr